const styles = {
  safeArea: 'flex-1 bg-ku-background',
  content: 'self-center w-full max-w-[720px]',
  listContent: 'px-[24px] pb-[24px]',
  intro: 'pb-[16px] pt-[8px]',
  title: 'text-ku-text-strong font-ku-bold text-ku-title',
  subtitle: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[4px]',
  searchField: 'items-center bg-ku-surface border-ku-border-accent rounded-[18px] border flex-row min-h-[56px] px-[12px] mt-[8px]',
  searchIcon: 'items-center justify-center h-[40px] w-[40px]',
  searchInput: 'text-ku-text-strong flex-1 font-ku-regular text-ku-body min-h-[52px] px-[8px]',
  sectionHeading: 'items-center flex-row justify-between mb-[8px] mt-[8px]',
  sectionTitle: 'text-ku-text-strong font-ku-semibold text-ku-subtitle',
  sectionCount: 'text-ku-text-muted font-ku-medium text-ku-meta',
  conversationList: 'gap-[8px]',
  conversationRow: 'items-center bg-ku-white border-ku-border-accent rounded-[16px] border flex-row min-h-[88px] p-[12px] active:bg-ku-surface-muted',
  avatar: 'items-center rounded-ku-pill shrink-0 h-[48px] justify-center w-[48px]',
  avatarText: 'text-ku-primary-deep font-ku-bold text-ku-body-small',
  avatarSmall: 'h-[36px] w-[36px]',
  avatarSmallText: 'text-ku-primary-deep font-ku-bold text-ku-label',
  rowCopy: 'flex-1 min-w-0 ml-[12px]',
  questTitle: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  participant: 'text-ku-primary font-ku-medium text-ku-label mt-[1px]',
  latestMessage: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[4px]',
  rowMeta: 'items-end self-start ml-[8px]',
  rowTime: 'text-ku-text-muted font-ku-regular text-ku-caption',
  unreadBadge: 'items-center bg-ku-primary rounded-ku-pill h-[22px] justify-center min-w-[22px] mt-[8px] px-[5px]',
  unreadText: 'text-ku-white font-ku-bold text-ku-caption',
  emptyState: 'items-center justify-center px-[24px] py-[64px]',
  emptyIcon: 'items-center bg-ku-surface-accent rounded-ku-pill h-[68px] justify-center mb-[16px] w-[68px]',
  emptyTitle: 'text-ku-text-strong font-ku-semibold text-ku-emphasis-large text-center',
  emptyDescription: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[4px] text-center',
  detailHeader: 'bg-ku-surface border-b-ku-border-subtle border-b',
  brandRow: 'items-center flex-row justify-start min-h-[48px] px-[16px] pt-[4px]',
  backButton: 'items-center justify-center rounded-ku-pill h-[48px] w-[48px] active:bg-ku-surface-muted',
  identityRow: 'items-center flex-row min-h-[72px] px-[16px] pb-[12px] pt-[4px]',
  identityCopy: 'flex-1 min-w-0 ml-[10px]',
  identityTitle: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  identityMeta: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[1px]',
  headerActions: 'items-center flex-row ml-[8px]',
  headerAction: 'items-center justify-center rounded-ku-pill h-[44px] w-[44px] active:bg-ku-surface-muted',
  contextCard: 'items-center bg-ku-surface-accent border-ku-border-accent rounded-[16px] border flex-row mx-[24px] mt-[16px] p-[12px]',
  contextIcon: 'items-center bg-ku-white rounded-[12px] h-[40px] justify-center w-[40px]',
  contextCopy: 'flex-1 min-w-0 ml-[10px]',
  contextLabel: 'text-ku-text-muted font-ku-medium text-ku-label',
  contextTitle: 'text-ku-primary font-ku-semibold text-ku-body-small mt-[1px]',
  contextAction: 'items-center justify-center min-h-[40px] ml-[8px] px-[4px]',
  contextActionText: 'text-ku-primary font-ku-semibold text-ku-label',
  searchPanel: 'bg-ku-background px-[24px] pb-[4px] pt-[12px]',
  compactSearchField: 'items-center bg-ku-surface border-ku-border-accent rounded-[18px] border flex-row min-h-[52px] px-[8px]',
  compactSearchInput: 'text-ku-text-strong flex-1 font-ku-regular text-ku-body-small min-h-[48px] px-[6px]',
  scopeSwitch: 'bg-ku-surface-muted rounded-ku-pill flex-row mt-[8px] p-[3px]',
  scopeItem: 'items-center flex-1 justify-center min-h-[36px] px-[8px]',
  scopeItemActive: 'bg-ku-white rounded-ku-pill',
  scopeText: 'text-ku-text-secondary font-ku-medium text-ku-label',
  scopeTextActive: 'text-ku-primary font-ku-semibold',
  resultMeta: 'text-ku-text-muted font-ku-medium text-ku-label px-[24px] pt-[12px]',
  messageContent: 'px-[24px] pt-[20px]',
  dateSeparator: 'self-center bg-ku-surface-muted rounded-ku-pill px-[10px] py-[5px]',
  dateText: 'text-ku-text-muted font-ku-medium text-ku-caption',
  messageRow: 'items-end flex-row mt-[16px]',
  messageRowMe: 'justify-end',
  messageAvatar: 'items-center rounded-ku-pill h-[32px] justify-center mr-[8px] w-[32px]',
  messageAvatarText: 'text-ku-primary-deep font-ku-bold text-ku-caption',
  messageStack: 'max-w-[78%] min-w-0',
  messageStackMe: 'items-end',
  messageBubble: 'bg-ku-surface-muted rounded-[18px] px-[14px] py-[10px]',
  messageBubbleMe: 'bg-ku-success-light rounded-[18px] px-[14px] py-[10px]',
  messageText: 'text-ku-text-strong font-ku-regular text-ku-body-small',
  messageMeta: 'text-ku-text-muted font-ku-regular text-ku-caption mt-[4px] px-[4px]',
  attachmentBubble: 'items-center bg-ku-success-light rounded-[18px] flex-row min-h-[60px] mt-[4px] px-[10px] py-[8px]',
  attachmentBubbleOther: 'bg-ku-surface-muted',
  attachmentIcon: 'items-center bg-ku-surface-accent rounded-[10px] h-[40px] justify-center w-[40px]',
  attachmentCopy: 'flex-1 min-w-0 ml-[8px]',
  attachmentName: 'text-ku-text-strong font-ku-medium text-ku-body-small',
  attachmentMeta: 'text-ku-text-muted font-ku-regular text-ku-caption mt-[1px]',
  fileList: 'gap-[8px] px-[24px] pt-[16px]',
  fileRow: 'items-center bg-ku-white border-ku-border-accent rounded-[14px] border flex-row min-h-[68px] p-[10px] active:bg-ku-surface-muted',
  fileType: 'items-center rounded-[10px] h-[42px] justify-center w-[42px]',
  fileTypePdf: 'bg-ku-surface-danger',
  fileTypeImage: 'bg-ku-surface-accent',
  fileCopy: 'flex-1 min-w-0 ml-[10px]',
  fileName: 'text-ku-text-strong font-ku-medium text-ku-body-small',
  fileMeta: 'text-ku-text-muted font-ku-regular text-ku-caption mt-[2px]',
  searchEmpty: 'items-center px-[24px] py-[56px]',
  searchEmptyText: 'text-ku-text-secondary font-ku-regular text-ku-body-small text-center',
  composerWrap: 'bg-ku-background border-ku-border-subtle border-t px-[16px] pb-[8px] pt-[8px]',
  composer: 'items-center bg-ku-surface-muted rounded-[24px] flex-row min-h-[56px] px-[6px]',
  composerButton: 'items-center justify-center rounded-ku-pill h-[44px] w-[44px] active:bg-ku-surface',
  composerInput: 'text-ku-text-strong flex-1 font-ku-regular text-ku-body-small min-h-[48px] px-[8px]',
  sendButton: 'items-center bg-ku-primary rounded-ku-pill h-[42px] justify-center w-[42px]',
} as const;

export default styles;
