/**
 * KUQuest Mobile — Google Sheets Audit Workbook Setup
 *
 * HOW TO USE:
 * 1. Create a blank Google Sheet (go to https://sheets.new)
 * 2. Click "Extensions" > "Apps Script"
 * 3. Replace all code in the script editor with this file's content
 * 4. Click "Run" (choose createAuditSheets function)
 * 5. Return to the Google Sheet — all sheets, headers, colors, data, and formulas are ready!
 */

function createAuditSheets() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();

  // Dashboard Sheet
  let dash = ss.getSheetByName("Audit Summary");
  if (!dash) {
    dash = ss.insertSheet("Audit Summary", 0);
  }
  dash.clear();
  dash.setTabColor("#1A73E8");

  // Title
  dash
    .getRange("A1:E1")
    .merge()
    .setValue("KUQUEST MOBILE — SYSTEM AUDIT & VERIFICATION MATRIX")
    .setFontSize(16)
    .setFontWeight("bold")
    .setBackground("#1A73E8")
    .setFontColor("#FFFFFF")
    .setHorizontalAlignment("center")
    .setVerticalAlignment("middle");
  dash.setRowHeight(1, 45);

  dash
    .getRange("A2:E2")
    .merge()
    .setValue(
      "Authority: docs/rulebook/, docs/adr/, CONTEXT.md | Target: Expo SDK 57 / React Native 0.86"
    )
    .setFontSize(10)
    .setFontColor("#5F6368")
    .setHorizontalAlignment("center");
  dash.setRowHeight(2, 25);

  // KPI table
  const kpiHeaders = [
    [
      "Audit Category / Sheet",
      "Total Items",
      "Passed",
      "Failed / Blocked",
      "Pending Smoke",
    ],
  ];
  dash
    .getRange("A4:E4")
    .setValues(kpiHeaders)
    .setFontWeight("bold")
    .setBackground("#E8F0FE")
    .setFontColor("#174EA6")
    .setBorder(true, true, true, true, true, true);

  const kpiRows = [
    [
      "1. Screens & Navigation",
      "=COUNTA('1. Screens & Navigation'!A2:A)",
      "=COUNTIF('1. Screens & Navigation'!I2:I, \"PASS\")",
      "=COUNTIF('1. Screens & Navigation'!I2:I, \"FAIL\")",
      "=COUNTIF('1. Screens & Navigation'!I2:I, \"PENDING\")",
    ],
    [
      "2. Lifecycle & Rules",
      "=COUNTA('2. Lifecycle & Rules'!A2:A)",
      "=COUNTIF('2. Lifecycle & Rules'!H2:H, \"PASS\")",
      "=COUNTIF('2. Lifecycle & Rules'!H2:H, \"FAIL\")",
      "=COUNTIF('2. Lifecycle & Rules'!H2:H, \"PENDING\")",
    ],
    [
      "3. Finance & Wallet",
      "=COUNTA('3. Finance & Wallet'!A2:A)",
      "=COUNTIF('3. Finance & Wallet'!H2:H, \"PASS\")",
      "=COUNTIF('3. Finance & Wallet'!H2:H, \"FAIL\")",
      "=COUNTIF('3. Finance & Wallet'!H2:H, \"PENDING\")",
    ],
    [
      "4. Chat & Inquiries",
      "=COUNTA('4. Chat & Inquiries'!A2:A)",
      "=COUNTIF('4. Chat & Inquiries'!H2:H, \"PASS\")",
      "=COUNTIF('4. Chat & Inquiries'!H2:H, \"FAIL\")",
      "=COUNTIF('4. Chat & Inquiries'!H2:H, \"PENDING\")",
    ],
    [
      "5. Architecture & State",
      "=COUNTA('5. Architecture & State'!A2:A)",
      "=COUNTIF('5. Architecture & State'!H2:H, \"PASS\")",
      "=COUNTIF('5. Architecture & State'!H2:H, \"FAIL\")",
      "=COUNTIF('5. Architecture & State'!H2:H, \"PENDING\")",
    ],
    [
      "6. UI & Accessibility",
      "=COUNTA('6. UI & Accessibility'!A2:A)",
      "=COUNTIF('6. UI & Accessibility'!H2:H, \"PASS\")",
      "=COUNTIF('6. UI & Accessibility'!H2:H, \"FAIL\")",
      "=COUNTIF('6. UI & Accessibility'!H2:H, \"PENDING\")",
    ],
    [
      "TOTAL MASTER ITEMS",
      "=SUM(B5:B10)",
      "=SUM(C5:C10)",
      "=SUM(D5:D10)",
      "=SUM(E5:E10)",
    ],
  ];

  dash
    .getRange("A5:E11")
    .setValues(kpiRows)
    .setBorder(true, true, true, true, true, true);
  dash.getRange("A11:E11").setFontWeight("bold").setBackground("#F1F3F4");

  dash.setColumnWidth(1, 240);
  dash.setColumnWidth(2, 120);
  dash.setColumnWidth(3, 100);
  dash.setColumnWidth(4, 130);
  dash.setColumnWidth(5, 130);

  // Sheets data
  const sheetsData = [
    {
      sheetName: "1. Screens & Navigation",
      color: "#1B5E20",
      data: [
        [
          "Item ID",
          "Area",
          "Screen / Flow",
          "Route / Component",
          "Role / Access",
          "Key Verification Criteria",
          "Status",
          "Test / Code Reference",
          "Pass/Fail",
          "Audit Notes",
        ],
        [
          "SCR-001",
          "Auth & Onboarding",
          "Google Auth Sign-in",
          "src/app/index.tsx",
          "Public / Unauth",
          "Native Google OAuth via Better-Auth; stores secure cookie & session; redirects to onboarding or workspace",
          "Implemented & Passing",
          "src/features/auth/__tests__/authEnvironment.test.ts",
          "PASS",
          "ADR-0004 & SDK 57 compliant",
        ],
        [
          "SCR-002",
          "Auth & Onboarding",
          "Academic Onboarding",
          "src/app/onboarding/index.tsx",
          "Authenticated (First Run)",
          "Collects student ID, faculty, major, academic year; validates @ku.th domain before granting access",
          "Implemented & Passing",
          "src/features/onboarding/__tests__/onboarding.test.ts",
          "PASS",
          "Blocks entry until academic profile saved",
        ],
        [
          "SCR-003",
          "Navigation Shell",
          "Role Workspace Switching",
          "src/app/(tabs)/_layout.tsx",
          "Hirer / Worker",
          "Switching between Hirer and Worker workspaces dynamically updates tab icons, labels, and theme color ramps",
          "Implemented & Passing",
          "src/features/workspace/__tests__/AppThemeProvider.test.tsx",
          "PASS",
          "ADR-0011 & ADR-0012 zero Context pattern",
        ],
        [
          "SCR-004",
          "Navigation Shell",
          "Primary Bottom Tabs",
          "src/app/(tabs)/_layout.tsx",
          "Hirer / Worker",
          "5 primary tabs: Quest Board (Explore), My Quests (Work), Create (+), Money (Wallet), Profile",
          "Implemented & Passing",
          "src/app/(tabs)/__tests__/index.test.tsx",
          "PASS",
          "ADR-0007 persistent tab shell",
        ],
        [
          "SCR-005",
          "Discovery",
          "Quest Board (Worker View)",
          "src/app/(tabs)/index.tsx",
          "Worker",
          "Feed of open quests with compact horizontal cards; search by keyword; filter by faculty, reward, tag",
          "Implemented & Passing",
          "src/features/workerHome/__tests__/WorkerHomeScreen.test.tsx",
          "PASS",
          "ADR-0001 density & ADR-0009 discovery boundary",
        ],
        [
          "SCR-006",
          "Quest Creation",
          "3-Step Wizard: Basic Details",
          "src/app/(tabs)/create.tsx (Step 1)",
          "Hirer",
          "Step 1: Title, description, tags, location/remote, draft auto-save to storage with user-scoped key",
          "Implemented & Passing",
          "src/app/(tabs)/__tests__/create.test.tsx",
          "PASS",
          "ADR-0002 3-step creation wizard",
        ],
        [
          "SCR-007",
          "Quest Creation",
          "3-Step Wizard: Mode & Schedule",
          "src/app/(tabs)/create.tsx (Step 2)",
          "Hirer",
          "Step 2: Selection mode (FCFS vs Candidate), Single vs Group, headcount (min 2), startTime, dueAt",
          "Implemented & Passing",
          "src/features/createQuest/__tests__/createQuestDraft.test.ts",
          "PASS",
          "Enforces startTime < dueAt & valid mode matrix",
        ],
        [
          "SCR-008",
          "Quest Creation",
          "3-Step Wizard: Budget & Escrow",
          "src/app/(tabs)/create.tsx (Step 3)",
          "Hirer",
          "Step 3: Worker reward per head, platform fee preview, questFundingTotal calculation, escrow check",
          "Implemented & Passing",
          "src/features/createQuest/__tests__/createQuestWorkflow.test.ts",
          "PASS",
          "Requires sufficient spending balance; prompts top-up",
        ],
        [
          "SCR-009",
          "Quest Details",
          "Quest Detail Page",
          "src/app/quest/[id].tsx",
          "All Roles",
          "State & role adaptive: Hirer sees management controls; Candidate sees apply/team; Worker sees work controls",
          "Implemented & Passing",
          "src/features/questBoard/presentation/__tests__/QuestBoardViewData.test.ts",
          "PASS",
          "Header hero, tags, reward satang to THB, deadline",
        ],
        [
          "SCR-010",
          "Quest Management",
          "Hirer Quest Manage Screen",
          "src/app/quest/[id]/manage.tsx",
          "Hirer",
          "Review candidate applications, inspect candidate teams, accept candidate/team, cancel quest with refund",
          "Implemented & Passing",
          "src/app/quest/[id]/__tests__/manage.test.tsx",
          "PASS",
          "Atomic acceptance transaction",
        ],
        [
          "SCR-011",
          "Quest Management",
          "Select Roster Review",
          "src/app/quest/[id]/select-roster.tsx",
          "Hirer",
          "Roster review view model, member profile sheet, view reputation ratings and past completed quests",
          "Implemented & Passing",
          "src/app/quest/[id]/__tests__/select-roster.test.tsx",
          "PASS",
          "ADR-0008 public profile reputation",
        ],
        [
          "SCR-012",
          "Candidate Assembly",
          "Candidate Team Assembly",
          "src/app/quest/[id]/team.tsx",
          "Candidate",
          "Join code display/regeneration, invite prospective workers, roster list, disband team, submit at exact headcount",
          "Implemented & Passing",
          "src/features/questBoard/teamAssemble/__tests__/GroupQuestSheets.test.tsx",
          "PASS",
          "ADR-0010 Join code 24h expiration",
        ],
        [
          "SCR-013",
          "Quest Execution",
          "Start Work Protocol Screen",
          "src/app/quest/[id]/work.tsx",
          "Assigned Worker",
          "Start work button active only between startTime and dueAt; displays countdown timer, team readiness status",
          "Implemented & Passing",
          "src/features/questBoard/work/__tests__/QuestWorkScreen.test.tsx",
          "PASS",
          "Start work triggers QUEST_IN_PROGRESS",
        ],
        [
          "SCR-014",
          "Proof Submission",
          "Worker Proof Form",
          "src/app/quest/[id]/proof.tsx",
          "Active Worker",
          "Upload 1-5 proof files/images, work summary note, auto-save proof draft, submit before dueAt",
          "Implemented & Passing",
          "src/features/workerWork/__tests__/WorkerProofForm.test.tsx",
          "PASS",
          "Contract: 1-5 files max, draft persistence",
        ],
        [
          "SCR-015",
          "Proof Review",
          "Hirer Proof Review Screen",
          "src/app/quest/[id]/proof-review.tsx",
          "Hirer",
          "Inspect worker proof images/notes, 24h auto-approval countdown banner, approve or reject with mandatory reason",
          "Implemented & Passing",
          "src/features/questBoard/review/__tests__/HirerProofReviewScreen.test.tsx",
          "PASS",
          "Rejection triggers QUEST_FAILED & Admin Review Item",
        ],
        [
          "SCR-016",
          "Rating Review",
          "Reciprocal Rating Modal",
          "src/features/questBoard/review/components/QuestReviewModal.tsx",
          "Hirer / Worker",
          "1-5 star rating, feedback tags, comments; available within 7 days of terminal quest state",
          "Implemented & Passing",
          "src/features/questBoard/review/components/__tests__/QuestReviewModal.test.tsx",
          "PASS",
          "Both parties rate independently; affects reputation",
        ],
        [
          "SCR-017",
          "Wallet",
          "Wallet Main Screen",
          "src/app/(tabs)/money.tsx",
          "All Members",
          "Displays 4 compartments: Spending, Earnings, Funding Reserved (Escrow), Reserved for Payouts; Satang precision",
          "Implemented & Passing",
          "src/features/wallet/__tests__/WalletScreen.test.tsx",
          "PASS",
          "rulebook/finance/wallet-compartment-contract.md",
        ],
        [
          "SCR-018",
          "Wallet",
          "PromptPay QR Top-Up",
          "src/app/top-up.tsx",
          "All Members",
          "Select amount preset or custom (satang integer), generate PromptPay QR, confirmation step, poll transaction status",
          "Implemented & Passing",
          "src/features/wallet/__tests__/TopUpScreen.test.tsx",
          "PASS",
          "Safe overflow check (<2,000,000,000 satang)",
        ],
        [
          "SCR-019",
          "Wallet",
          "Transfer Earnings to Spending",
          "src/features/wallet/components/TransferEarningsModal.tsx",
          "Worker",
          "Instant, fee-free conversion of earningsBalanceSatang to spendingBalanceSatang for publishing quests",
          "Implemented & Passing",
          "src/features/wallet/components/__tests__/TransferEarningsModal.test.tsx",
          "PASS",
          "Immediate ledger credit; no payout fee deducted",
        ],
        [
          "SCR-020",
          "Chat & Inquiry",
          "Candidate Inquiry Chat",
          "src/app/quest/[id]/inquiry/[conversationId].tsx",
          "Hirer + Prospective Worker",
          "Strictly 2 participants, active only during QUEST_OPEN, disappears upon assignment, no KU bot system messages",
          "Implemented & Passing",
          "src/features/conversation/__tests__/conversation.test.ts",
          "PASS",
          "docs/rulebook/quest/conversation-contract.md",
        ],
        [
          "SCR-021",
          "Chat & Inquiry",
          "Work Conversation Room",
          "src/app/(tabs)/chat/[id].tsx",
          "Accepted Participants",
          "Hirer + all active workers; KU bot system messages; permanent read-only archive upon completion/failure",
          "Implemented & Passing",
          "src/features/conversation/__tests__/workChat.test.ts",
          "PASS",
          "Attachments <= 5MB, rate limit 5msg/5s",
        ],
        [
          "SCR-022",
          "Profile & Settings",
          "Public Student Profile",
          "src/app/profile/[id].tsx",
          "All Members",
          "Displays verified academic status, reputation score, completed quest count, reviews summary",
          "Implemented & Passing",
          "src/features/profile/__tests__/profile.test.ts",
          "PASS",
          "ADR-0008 Student reputation & public trust",
        ],
        [
          "SCR-023",
          "Settings & Trust",
          "Conduct & Report Modal",
          "src/app/report.tsx",
          "All Members",
          "Submit report against user/quest/message with reason categories and evidence link to Admin portal",
          "Implemented & Passing",
          "src/features/report/__tests__/ReportScreen.test.tsx",
          "PASS",
          "Trust & Safety admin-conduct-report contract",
        ],
        [
          "SCR-024",
          "Dev & QA",
          "Dev Persona Roleplay Tool",
          "src/app/dev/roleplay.tsx",
          "Dev / Test Only",
          "Instant switching between mock Hirer, Worker, Candidate, and Underfilled personas with seeded wallet balances",
          "Implemented & Passing",
          "src/features/roleplay/__tests__/RoleplayScreen.test.tsx",
          "PASS",
          "Fast validation without recreating accounts",
        ],
      ],
    },
    {
      sheetName: "2. Lifecycle & Rules",
      color: "#0D47A1",
      data: [
        [
          "Rule ID",
          "Domain Contract",
          "Lifecycle Stage / Event",
          "Specification & Contract Rule",
          "Forbidden / Boundary Condition",
          "Implementation & Store Location",
          "Test Coverage",
          "Audit Status",
          "Remarks",
        ],
        [
          "LFC-001",
          "Quest Lifecycle",
          "Creation to QUEST_OPEN",
          "Hirer completes 3 steps; questFundingTotal locked in escrow from spendingBalanceSatang; status becomes QUEST_OPEN",
          "Cannot publish if spending balance < questFundingTotal; cannot create with past dueAt",
          "src/features/createQuest/workflow/useCreateQuestFlow.ts",
          "src/features/createQuest/__tests__/createQuestWorkflow.test.ts",
          "PASS",
          "Atomic funding lock",
        ],
        [
          "LFC-002",
          "Selection Mode",
          "FIRST_COME_FIRST_SERVED (FCFS)",
          "Single: first worker joins directly -> QUEST_ASSIGNED. Group: workers join directly until headcount reached.",
          "No candidate application step allowed; cannot join after headcount full or quest closed",
          "src/features/questBoard/workflow/questWorkflow.ts",
          "src/features/questBoard/workflow/__tests__/questWorkflow.test.ts",
          "PASS",
          "Direct assignment",
        ],
        [
          "LFC-003",
          "Selection Mode",
          "CANDIDATE Selection",
          "Candidates apply individually or in teams; Hirer manually reviews and selects winning roster",
          "Hirer selection rejects all other candidates/teams in the same transaction; no partial team selection",
          "src/features/questBoard/roster/useSelectRosterActions.ts",
          "src/app/quest/[id]/__tests__/select-roster.test.tsx",
          "PASS",
          "ADR-0010 & atomic rejection",
        ],
        [
          "LFC-004",
          "Candidate Team",
          "Join Code Mechanics",
          "Server generates 24h code for GROUP + CANDIDATE; team leader can regenerate code; auto-disbands if all leave",
          "Cannot submit team before exact headcount; cannot edit members after team submitted; code invalid after 24h",
          "src/features/questBoard/teamAssemble/teamInvite.ts",
          "src/features/questBoard/teamAssemble/__tests__/GroupQuestSheets.test.tsx",
          "PASS",
          "24h TTL enforced",
        ],
        [
          "LFC-005",
          "Start Work",
          "Execution Window Gate",
          "Required starter can press Start Work ONLY between startTime and dueAt. Single: worker. Group Candidate: team leader.",
          "Pressing before startTime or after dueAt is blocked; missing Start Work by dueAt fails quest",
          "src/features/questBoard/work/useQuestWorkFeature.ts",
          "src/features/questBoard/work/__tests__/QuestWorkScreen.test.tsx",
          "PASS",
          "Enforces execution boundary",
        ],
        [
          "LFC-006",
          "Underfilled FCFS",
          "Consensus & Proceed Gate",
          "At startTime, underfilled FCFS: Hirer has 10 min to proceed or cancel. If proceed, all workers have 10 min to consent.",
          "Any timeout or rejection cancels quest with 100% refund; reward pool split equally between consented workers",
          "src/features/questBoard/teamAssemble/components/PartialGroupStartConsentSheet.tsx",
          "src/features/questBoard/teamAssemble/__tests__/GroupQuestSheets.test.tsx",
          "PASS",
          "ADR-0010 underfilled consent gate",
        ],
        [
          "LFC-007",
          "Condition Edit",
          "10-Minute Consensus Window",
          "Hirer can edit quest conditions in QUEST_ASSIGNED; all assigned workers must vote within 10 minutes",
          "If any worker rejects or 10m expires, condition reverts to original; quest does not cancel",
          "src/features/questBoard/shared/components/QuestConditionEditModal.tsx",
          "src/features/questBoard/shared/components/__tests__/QuestConditionEdit.test.tsx",
          "PASS",
          "10m consensus timer",
        ],
        [
          "LFC-008",
          "Proof Submission",
          "Submission Artifacts",
          "Worker uploads 1-5 files/images and optional summary note before dueAt; draft saved locally during entry",
          "Cannot submit 0 files when proofRequired=true; cannot submit > 5 files; cannot submit after dueAt",
          "src/features/workerWork/components/WorkerProofForm.tsx",
          "src/features/workerWork/__tests__/WorkerProofForm.test.tsx",
          "PASS",
          "proof-submission-contract.md",
        ],
        [
          "LFC-009",
          "Proof Review",
          "24-Hour Auto-Approval",
          "Hirer reviews proof; if Hirer does not act within 24h, backend automatically triggers PROOF_APPROVED",
          "Hirer rejection requires non-empty reason; rejection triggers QUEST_FAILED and Admin Review Item",
          "src/features/questBoard/review/useHirerProofReviewFeature.ts",
          "src/features/questBoard/review/__tests__/HirerProofReviewScreen.test.tsx",
          "PASS",
          "No second rework round exists",
        ],
        [
          "LFC-010",
          "Cancellation Tier",
          "QUEST_OPEN Cancellation",
          "Hirer cancels during QUEST_OPEN: 100% refund of Quest Escrow back to Hirer spendingBalanceSatang",
          "No worker penalty; all active candidate inquiries closed immediately",
          "src/features/questBoard/manage/useHirerQuestManageFeature.ts",
          "src/app/quest/[id]/__tests__/manage.test.tsx",
          "PASS",
          "ADR-0003 Tier 1",
        ],
        [
          "LFC-011",
          "Cancellation Tier",
          "QUEST_ASSIGNED Cancellation",
          "Hirer cancels during QUEST_ASSIGNED: 20% of worker reward pool paid to active workers, 80% + platform fee to Hirer",
          "Assigned workers compensated for reservation; quest transitions to QUEST_CANCELLED",
          "src/features/questBoard/manage/useHirerQuestManageFeature.ts",
          "src/app/quest/[id]/__tests__/manage.test.tsx",
          "PASS",
          "ADR-0003 Tier 2",
        ],
        [
          "LFC-012",
          "Cancellation Tier",
          "QUEST_IN_PROGRESS Cancellation",
          "Hirer cancels during QUEST_IN_PROGRESS: 100% worker reward paid to workers, platform fee kept; Hirer gets 0 refund",
          "Prevents work exploitation; active workers receive full reward",
          "src/features/questBoard/manage/useHirerQuestManageFeature.ts",
          "src/app/quest/[id]/__tests__/manage.test.tsx",
          "PASS",
          "ADR-0003 Tier 3",
        ],
        [
          "LFC-013",
          "Rating & Reviews",
          "7-Day Mutual Rating Window",
          "Hirer and Worker can submit reciprocal rating & review within 7 days of QUEST_COMPLETED/FAILED/CANCELLED",
          "Reviews locked after 7 days; rating score updates public profile reputation aggregate asynchronously",
          "src/features/questBoard/review/useQuestReviewFeature.ts",
          "src/features/questBoard/review/components/__tests__/QuestReviewModal.test.tsx",
          "PASS",
          "rulebook/quest/rating-review-contract.md",
        ],
      ],
    },
    {
      sheetName: "3. Finance & Wallet",
      color: "#E65100",
      data: [
        [
          "Rule ID",
          "Finance Area",
          "Requirement & Business Rule",
          "Accounting / Ledger Invariant",
          "UI Formatting & Display Rule",
          "Code Location",
          "Test File",
          "Audit Status",
          "Remarks",
        ],
        [
          "FIN-001",
          "Satang Precision",
          "All internal currency stored as 32-bit integer satang (1 THB = 100 satang)",
          "Strictly non-negative integer math; floating-point money strictly prohibited",
          "UI displays formatted Baht (฿) with 2 decimals or rounded integer depending on token space",
          "src/features/wallet/walletFormatting.ts",
          "src/features/wallet/__tests__/walletModule.test.ts",
          "PASS",
          "ADR-0005 satang representation",
        ],
        [
          "FIN-002",
          "Wallet Compartments",
          "4 distinct compartments: Spending, Earnings, Funding Reserved, Reserved for Payouts",
          "Total wallet capacity capped at 2,000,000,000 Satang (฿20,000,000); transactions exceeding cap fail closed",
          "Wallet screen renders explicit cards for each compartment with status indicator",
          "src/features/wallet/WalletScreen.tsx",
          "src/features/wallet/__tests__/WalletScreen.test.tsx",
          "PASS",
          "wallet-compartment-contract.md",
        ],
        [
          "FIN-003",
          "Top-up QR Flow",
          "Member generates PromptPay QR payload; webhook or poll confirms receipt",
          "Double-entry credit to spendingBalanceSatang upon external payment clearing",
          "QR rendered with countdown timer, copyable PromptPay reference, and cancel action",
          "src/features/wallet/TopUpScreen.tsx",
          "src/features/wallet/__tests__/TopUpScreen.test.tsx",
          "PASS",
          "topup-and-conversion-contract.md",
        ],
        [
          "FIN-004",
          "Escrow Lock",
          "Publishing quest locks questFundingTotal (worker rewards + platform fee) in escrow",
          "Debits spendingBalanceSatang, credits fundingReservedSatang in single transaction",
          "Create Quest wizard displays breakdown: Base Reward x Headcount + Platform Fee",
          "src/features/createQuest/workflow/useCreateQuestFlow.ts",
          "src/features/createQuest/__tests__/createQuestWorkflow.test.ts",
          "PASS",
          "reward-money-contract.md",
        ],
        [
          "FIN-005",
          "Earnings Transfer",
          "Instant conversion of earningsBalanceSatang to spendingBalanceSatang",
          "Debits earningsBalanceSatang, credits spendingBalanceSatang; zero platform fee",
          "Transfer earnings modal shows available earnings and confirmation slider/button",
          "src/features/wallet/components/TransferEarningsModal.tsx",
          "src/features/wallet/components/__tests__/TransferEarningsModal.test.tsx",
          "PASS",
          "Instant availability for quest publishing",
        ],
        [
          "FIN-006",
          "Payout Request",
          "Worker requests withdrawal of earningsBalanceSatang to verified bank/PromptPay",
          "Debits earningsBalanceSatang, credits reservedForPayoutsSatang until Admin approval",
          "Payout history lists status: PENDING, APPROVED, REJECTED, CLEARED",
          "src/features/wallet/api/walletQueries.ts",
          "src/features/wallet/__tests__/walletModule.test.ts",
          "PASS",
          "payout-contract.md & gotcha fix",
        ],
        [
          "FIN-007",
          "Wallet Statuses",
          "Wallet statuses: ACTIVE, FROZEN, SUSPENDED, CLOSED",
          "FROZEN/SUSPENDED blocks new commitments (top-up, publish, join); active escrow runs to completion",
          "UI displays banner explaining frozen reason and support contact link",
          "src/features/wallet/walletModule.ts",
          "src/features/wallet/__tests__/walletModule.test.ts",
          "PASS",
          "finance-rulebook.md status guard",
        ],
      ],
    },
    {
      sheetName: "4. Chat & Inquiries",
      color: "#4A148C",
      data: [
        [
          "Rule ID",
          "Conversation Type",
          "Participant Rule & Scope",
          "System Bot / Message Policy",
          "Attachments & Rate Limits",
          "Code Reference",
          "Test Reference",
          "Audit Status",
          "Remarks",
        ],
        [
          "CHT-001",
          "Candidate Inquiry",
          "Strictly 2 members: Hirer + 1 Prospective Worker. Active only during QUEST_OPEN.",
          "Zero KU Bot system messages allowed; human-to-human Q&A only",
          "Text & attachments <= 5MB; rate limit 5 messages per 5 seconds",
          "src/features/conversation/CandidateInquiryView.tsx",
          "src/features/conversation/__tests__/conversation.test.ts",
          "PASS",
          "Disappears upon quest assignment",
        ],
        [
          "CHT-002",
          "Work Conversation",
          "Hirer + all current Active Workers. Opened upon first ASSIGNMENT_ACTIVE.",
          "Official KU Bot posts immutable events (start work, proof submitted, deadline alert, completion)",
          "Text & image/pdf attachments <= 5MB; rate limit 5 messages per 5 seconds",
          "src/features/conversation/WorkConversationView.tsx",
          "src/features/conversation/__tests__/workChat.test.ts",
          "PASS",
          "Permanent read-only archive upon finish",
        ],
        [
          "CHT-003",
          "Rate Limiting",
          "Cooldown triggers after 5 messages in 5 seconds window",
          'UI displays cooldown counter (e.g. "Wait 4s") and preserves draft input text without wiping',
          "Client enforces draft protection; server enforces 429 Too Many Requests",
          "src/features/conversation/useChatController.ts",
          "src/features/conversation/__tests__/chatRateLimit.test.ts",
          "PASS",
          "Draft preservation tested",
        ],
        [
          "CHT-004",
          "Safety & Reporting",
          "Any chat message can be reported for harassment or policy violation",
          "Generates Admin Evidence Reference; Admin can inspect reported thread via dispute portal",
          "Modal report prompt with reason dropdown and optional screenshot attachment",
          "src/features/report/ReportScreen.tsx",
          "src/features/report/__tests__/ReportScreen.test.tsx",
          "PASS",
          "admin-conduct-report-contract.md",
        ],
      ],
    },
    {
      sheetName: "5. Architecture & State",
      color: "#006064",
      data: [
        [
          "Rule ID",
          "Architectural Concern",
          "Design Decision (ADR / Standard)",
          "Technology / Owner",
          "Anti-Pattern / Banned Implementation",
          "Code Location",
          "Test File",
          "Audit Status",
          "Remarks",
        ],
        [
          "ARC-001",
          "Server State",
          "All asynchronous server queries & mutations managed by TanStack Query v5",
          "TanStack Query (@tanstack/react-query v5.103)",
          "No manual useEffect data fetching; no custom fetching cache in React Context",
          "src/infrastructure/query/queryClient.ts",
          "docs/refactor-progress.md",
          "PASS",
          "Clean query keys & invalidations",
        ],
        [
          "ARC-002",
          "Client / App State",
          "Domain client state managed by lightweight Zustand stores",
          "Zustand v5 (roleWorkspaceStore, questDraftStore)",
          "Zero application-owned React Context for mutable app state (ADR-0012)",
          "src/features/workspace/roleWorkspaceStore.ts",
          "src/features/workspace/__tests__/AppThemeProvider.test.tsx",
          "PASS",
          "ADR-0012 state boundaries",
        ],
        [
          "ARC-003",
          "Complex Workflows",
          "Pure domain reducers hosted by Zustand vanilla or pure functions",
          "Pure TypeScript Reducers (questWorkflow, workerWorkProjection)",
          "No business logic inside React UI components",
          "src/features/questBoard/workflow/questWorkflow.ts",
          "src/features/questBoard/workflow/__tests__/questWorkflow.test.ts",
          "PASS",
          "Deterministic testing",
        ],
        [
          "ARC-004",
          "Persistent Storage",
          "Explicit storage adapters: SecureStore for session, AsyncStorage for drafts/prefs",
          "expo-secure-store + persistent storage adapters",
          "No sensitive auth tokens or session cookies in unencrypted AsyncStorage",
          "src/infrastructure/storage/secureStorageAdapter.ts",
          "src/features/auth/__tests__/authEnvironment.test.ts",
          "PASS",
          "Safe token isolation",
        ],
        [
          "ARC-005",
          "WebSocket Client",
          "WebSocket connections must supply Origin: kuquestmobile:// and Cookie",
          "src/api/ServerSocket.ts (openServerSocket)",
          "Direct new WebSocket() without Origin causes 4403 rejection on staging backend",
          "src/api/ServerSocket.ts",
          "docs/agents/gotchas.md",
          "PASS",
          "Gotcha resolved 2026-09-26",
        ],
      ],
    },
    {
      sheetName: "6. UI & Accessibility",
      color: "#3E2723",
      data: [
        [
          "Rule ID",
          "UI & Platform Standard",
          "Requirement & UX Rule",
          "Platform Behavior & Verification",
          "Accessibility (A11y) Rule",
          "File / Token Reference",
          "Test / Verification",
          "Audit Status",
          "Remarks",
        ],
        [
          "UI-001",
          "Design Tokens & Colors",
          "NativeWind v4 with strict semantic ramp tokens (ku-primary, ku-surface, etc.)",
          "Workspace dynamic theme: Hirer (sage) vs Worker (emerald) swaps seamlessly",
          "High contrast text tokens (ku-on-primary, ku-text-primary >= 4.5:1 ratio)",
          "src/theme/colors.ts",
          "src/features/workspace/__tests__/AppThemeProvider.test.tsx",
          "PASS",
          "DESIGN.md compliant",
        ],
        [
          "UI-002",
          "Typography & Sizing",
          "Be Vietnam Pro font family; responsive layout without hardcoded fixed heights",
          "Android fontScale 1.3+ support: text wraps cleanly without clipping or truncation",
          "Scalable typography tokens; accessible line-heights",
          "src/theme/typography.ts",
          "docs/research/mobile-ui-sizing-best-practices.md",
          "PASS",
          "Verified across density buckets",
        ],
        [
          "UI-003",
          "Touch Targets",
          "All interactive touch targets must be at least 44x44pt (Apple HIG / Android Material)",
          "Buttons, tab items, back arrows, list row items include hitSlop or min dimensions",
          "Screen readers locate and trigger taps reliably",
          "docs/agents/ui-design-rules.md",
          "src/components/ui/Button.tsx",
          "PASS",
          "Accessibility touch target pass",
        ],
        [
          "UI-004",
          "Screen Reader Semantics",
          "All controls require accessible labels, roles, and hint where state is not obvious",
          "accessibilityRole (button, tab, header), accessibilityState (selected, disabled)",
          "TalkBack (Android) & VoiceOver (iOS) announce state changes (e.g. countdown, balance update)",
          "src/components/ui/AccessibilityWrapper.tsx",
          "src/features/workerHome/components/WorkerSearchBar.tsx",
          "PASS",
          "Native A11y tree verified",
        ],
        [
          "UI-005",
          "Safe Area Insets",
          "All screens respect react-native-safe-area-context edge insets",
          "Header avoids status bar and Dynamic Island; footer avoids home indicator bar",
          "Forms avoid software keyboard using KeyboardAvoidingView / ScrollView",
          "src/app/_layout.tsx",
          "src/features/workerWork/WorkerWorkManagementScreen.tsx",
          "PASS",
          "iOS & Android safe layout",
        ],
      ],
    },
    {
      sheetName: "Master Audit Checklist",
      color: "#263238",
      data: [
        [
          "Audit ID",
          "Category / Domain",
          "Item / Flow Name",
          "Rulebook / ADR Ref",
          "Verification Method",
          "Specification & Requirement Summary",
          "Current Status",
          "Code / Test Reference",
          "Audit Check (PASS/FAIL/PENDING)",
          "Auditor Notes & Edge Cases",
        ],
        [
          "SCR-001",
          "Screens: Auth & Onboarding",
          "Google Auth Sign-in",
          "System Design & Routing",
          "Component Test & Route Check",
          "Native Google OAuth via Better-Auth; stores secure cookie & session; redirects to onboarding or workspace",
          "Implemented & Passing",
          "src/features/auth/__tests__/authEnvironment.test.ts",
          "PASS",
          "ADR-0004 & SDK 57 compliant",
        ],
        [
          "SCR-002",
          "Screens: Auth & Onboarding",
          "Academic Onboarding",
          "System Design & Routing",
          "Component Test & Route Check",
          "Collects student ID, faculty, major, academic year; validates @ku.th domain before granting access",
          "Implemented & Passing",
          "src/features/onboarding/__tests__/onboarding.test.ts",
          "PASS",
          "Blocks entry until academic profile saved",
        ],
        [
          "SCR-003",
          "Screens: Navigation Shell",
          "Role Workspace Switching",
          "System Design & Routing",
          "Component Test & Route Check",
          "Switching between Hirer and Worker workspaces dynamically updates tab icons, labels, and theme color ramps",
          "Implemented & Passing",
          "src/features/workspace/__tests__/AppThemeProvider.test.tsx",
          "PASS",
          "ADR-0011 & ADR-0012 zero Context pattern",
        ],
        [
          "SCR-004",
          "Screens: Navigation Shell",
          "Primary Bottom Tabs",
          "System Design & Routing",
          "Component Test & Route Check",
          "5 primary tabs: Quest Board (Explore), My Quests (Work), Create (+), Money (Wallet), Profile",
          "Implemented & Passing",
          "src/app/(tabs)/__tests__/index.test.tsx",
          "PASS",
          "ADR-0007 persistent tab shell",
        ],
        [
          "SCR-005",
          "Screens: Discovery",
          "Quest Board (Worker View)",
          "System Design & Routing",
          "Component Test & Route Check",
          "Feed of open quests with compact horizontal cards; search by keyword; filter by faculty, reward, tag",
          "Implemented & Passing",
          "src/features/workerHome/__tests__/WorkerHomeScreen.test.tsx",
          "PASS",
          "ADR-0001 density & ADR-0009 discovery boundary",
        ],
        [
          "SCR-006",
          "Screens: Quest Creation",
          "3-Step Wizard: Basic Details",
          "System Design & Routing",
          "Component Test & Route Check",
          "Step 1: Title, description, tags, location/remote, draft auto-save to storage with user-scoped key",
          "Implemented & Passing",
          "src/app/(tabs)/__tests__/create.test.tsx",
          "PASS",
          "ADR-0002 3-step creation wizard",
        ],
        [
          "SCR-007",
          "Screens: Quest Creation",
          "3-Step Wizard: Mode & Schedule",
          "System Design & Routing",
          "Component Test & Route Check",
          "Step 2: Selection mode (FCFS vs Candidate), Single vs Group, headcount (min 2), startTime, dueAt",
          "Implemented & Passing",
          "src/features/createQuest/__tests__/createQuestDraft.test.ts",
          "PASS",
          "Enforces startTime < dueAt & valid mode matrix",
        ],
        [
          "SCR-008",
          "Screens: Quest Creation",
          "3-Step Wizard: Budget & Escrow",
          "System Design & Routing",
          "Component Test & Route Check",
          "Step 3: Worker reward per head, platform fee preview, questFundingTotal calculation, escrow check",
          "Implemented & Passing",
          "src/features/createQuest/__tests__/createQuestWorkflow.test.ts",
          "PASS",
          "Requires sufficient spending balance; prompts top-up",
        ],
        [
          "SCR-009",
          "Screens: Quest Details",
          "Quest Detail Page",
          "System Design & Routing",
          "Component Test & Route Check",
          "State & role adaptive: Hirer sees management controls; Candidate sees apply/team; Worker sees work controls",
          "Implemented & Passing",
          "src/features/questBoard/presentation/__tests__/QuestBoardViewData.test.ts",
          "PASS",
          "Header hero, tags, reward satang to THB, deadline",
        ],
        [
          "SCR-010",
          "Screens: Quest Management",
          "Hirer Quest Manage Screen",
          "System Design & Routing",
          "Component Test & Route Check",
          "Review candidate applications, inspect candidate teams, accept candidate/team, cancel quest with refund",
          "Implemented & Passing",
          "src/app/quest/[id]/__tests__/manage.test.tsx",
          "PASS",
          "Atomic acceptance transaction",
        ],
        [
          "SCR-011",
          "Screens: Quest Management",
          "Select Roster Review",
          "System Design & Routing",
          "Component Test & Route Check",
          "Roster review view model, member profile sheet, view reputation ratings and past completed quests",
          "Implemented & Passing",
          "src/app/quest/[id]/__tests__/select-roster.test.tsx",
          "PASS",
          "ADR-0008 public profile reputation",
        ],
        [
          "SCR-012",
          "Screens: Candidate Assembly",
          "Candidate Team Assembly",
          "System Design & Routing",
          "Component Test & Route Check",
          "Join code display/regeneration, invite prospective workers, roster list, disband team, submit at exact headcount",
          "Implemented & Passing",
          "src/features/questBoard/teamAssemble/__tests__/GroupQuestSheets.test.tsx",
          "PASS",
          "ADR-0010 Join code 24h expiration",
        ],
        [
          "SCR-013",
          "Screens: Quest Execution",
          "Start Work Protocol Screen",
          "System Design & Routing",
          "Component Test & Route Check",
          "Start work button active only between startTime and dueAt; displays countdown timer, team readiness status",
          "Implemented & Passing",
          "src/features/questBoard/work/__tests__/QuestWorkScreen.test.tsx",
          "PASS",
          "Start work triggers QUEST_IN_PROGRESS",
        ],
        [
          "SCR-014",
          "Screens: Proof Submission",
          "Worker Proof Form",
          "System Design & Routing",
          "Component Test & Route Check",
          "Upload 1-5 proof files/images, work summary note, auto-save proof draft, submit before dueAt",
          "Implemented & Passing",
          "src/features/workerWork/__tests__/WorkerProofForm.test.tsx",
          "PASS",
          "Contract: 1-5 files max, draft persistence",
        ],
        [
          "SCR-015",
          "Screens: Proof Review",
          "Hirer Proof Review Screen",
          "System Design & Routing",
          "Component Test & Route Check",
          "Inspect worker proof images/notes, 24h auto-approval countdown banner, approve or reject with mandatory reason",
          "Implemented & Passing",
          "src/features/questBoard/review/__tests__/HirerProofReviewScreen.test.tsx",
          "PASS",
          "Rejection triggers QUEST_FAILED & Admin Review Item",
        ],
        [
          "SCR-016",
          "Screens: Rating Review",
          "Reciprocal Rating Modal",
          "System Design & Routing",
          "Component Test & Route Check",
          "1-5 star rating, feedback tags, comments; available within 7 days of terminal quest state",
          "Implemented & Passing",
          "src/features/questBoard/review/components/__tests__/QuestReviewModal.test.tsx",
          "PASS",
          "Both parties rate independently; affects reputation",
        ],
        [
          "SCR-017",
          "Screens: Wallet",
          "Wallet Main Screen",
          "System Design & Routing",
          "Component Test & Route Check",
          "Displays 4 compartments: Spending, Earnings, Funding Reserved (Escrow), Reserved for Payouts; Satang precision",
          "Implemented & Passing",
          "src/features/wallet/__tests__/WalletScreen.test.tsx",
          "PASS",
          "rulebook/finance/wallet-compartment-contract.md",
        ],
        [
          "SCR-018",
          "Screens: Wallet",
          "PromptPay QR Top-Up",
          "System Design & Routing",
          "Component Test & Route Check",
          "Select amount preset or custom (satang integer), generate PromptPay QR, confirmation step, poll transaction status",
          "Implemented & Passing",
          "src/features/wallet/__tests__/TopUpScreen.test.tsx",
          "PASS",
          "Safe overflow check (<2,000,000,000 satang)",
        ],
        [
          "SCR-019",
          "Screens: Wallet",
          "Transfer Earnings to Spending",
          "System Design & Routing",
          "Component Test & Route Check",
          "Instant, fee-free conversion of earningsBalanceSatang to spendingBalanceSatang for publishing quests",
          "Implemented & Passing",
          "src/features/wallet/components/__tests__/TransferEarningsModal.test.tsx",
          "PASS",
          "Immediate ledger credit; no payout fee deducted",
        ],
        [
          "SCR-020",
          "Screens: Chat & Inquiry",
          "Candidate Inquiry Chat",
          "System Design & Routing",
          "Component Test & Route Check",
          "Strictly 2 participants, active only during QUEST_OPEN, disappears upon assignment, no KU bot system messages",
          "Implemented & Passing",
          "src/features/conversation/__tests__/conversation.test.ts",
          "PASS",
          "docs/rulebook/quest/conversation-contract.md",
        ],
        [
          "SCR-021",
          "Screens: Chat & Inquiry",
          "Work Conversation Room",
          "System Design & Routing",
          "Component Test & Route Check",
          "Hirer + all active workers; KU bot system messages; permanent read-only archive upon completion/failure",
          "Implemented & Passing",
          "src/features/conversation/__tests__/workChat.test.ts",
          "PASS",
          "Attachments <= 5MB, rate limit 5msg/5s",
        ],
        [
          "SCR-022",
          "Screens: Profile & Settings",
          "Public Student Profile",
          "System Design & Routing",
          "Component Test & Route Check",
          "Displays verified academic status, reputation score, completed quest count, reviews summary",
          "Implemented & Passing",
          "src/features/profile/__tests__/profile.test.ts",
          "PASS",
          "ADR-0008 Student reputation & public trust",
        ],
        [
          "SCR-023",
          "Screens: Settings & Trust",
          "Conduct & Report Modal",
          "System Design & Routing",
          "Component Test & Route Check",
          "Submit report against user/quest/message with reason categories and evidence link to Admin portal",
          "Implemented & Passing",
          "src/features/report/__tests__/ReportScreen.test.tsx",
          "PASS",
          "Trust & Safety admin-conduct-report contract",
        ],
        [
          "SCR-024",
          "Screens: Dev & QA",
          "Dev Persona Roleplay Tool",
          "System Design & Routing",
          "Component Test & Route Check",
          "Instant switching between mock Hirer, Worker, Candidate, and Underfilled personas with seeded wallet balances",
          "Implemented & Passing",
          "src/features/roleplay/__tests__/RoleplayScreen.test.tsx",
          "PASS",
          "Fast validation without recreating accounts",
        ],
        [
          "LFC-001",
          "Lifecycle: Quest Lifecycle",
          "Creation to QUEST_OPEN",
          "Hirer completes 3 steps; questFundingTotal locked in escrow from spendingBalanceSatang; status becomes QUEST_OPEN",
          "Unit & Reducer Test",
          "Cannot publish if spending balance < questFundingTotal; cannot create with past dueAt",
          "PASS",
          "src/features/createQuest/workflow/useCreateQuestFlow.ts",
          "PASS",
          "Atomic funding lock",
        ],
        [
          "LFC-002",
          "Lifecycle: Selection Mode",
          "FIRST_COME_FIRST_SERVED (FCFS)",
          "Single: first worker joins directly -> QUEST_ASSIGNED. Group: workers join directly until headcount reached.",
          "Unit & Reducer Test",
          "No candidate application step allowed; cannot join after headcount full or quest closed",
          "PASS",
          "src/features/questBoard/workflow/questWorkflow.ts",
          "PASS",
          "Direct assignment",
        ],
        [
          "LFC-003",
          "Lifecycle: Selection Mode",
          "CANDIDATE Selection",
          "Candidates apply individually or in teams; Hirer manually reviews and selects winning roster",
          "Unit & Reducer Test",
          "Hirer selection rejects all other candidates/teams in the same transaction; no partial team selection",
          "PASS",
          "src/features/questBoard/roster/useSelectRosterActions.ts",
          "PASS",
          "ADR-0010 & atomic rejection",
        ],
        [
          "LFC-004",
          "Lifecycle: Candidate Team",
          "Join Code Mechanics",
          "Server generates 24h code for GROUP + CANDIDATE; team leader can regenerate code; auto-disbands if all leave",
          "Unit & Reducer Test",
          "Cannot submit team before exact headcount; cannot edit members after team submitted; code invalid after 24h",
          "PASS",
          "src/features/questBoard/teamAssemble/teamInvite.ts",
          "PASS",
          "24h TTL enforced",
        ],
        [
          "LFC-005",
          "Lifecycle: Start Work",
          "Execution Window Gate",
          "Required starter can press Start Work ONLY between startTime and dueAt. Single: worker. Group Candidate: team leader.",
          "Unit & Reducer Test",
          "Pressing before startTime or after dueAt is blocked; missing Start Work by dueAt fails quest",
          "PASS",
          "src/features/questBoard/work/useQuestWorkFeature.ts",
          "PASS",
          "Enforces execution boundary",
        ],
        [
          "LFC-006",
          "Lifecycle: Underfilled FCFS",
          "Consensus & Proceed Gate",
          "At startTime, underfilled FCFS: Hirer has 10 min to proceed or cancel. If proceed, all workers have 10 min to consent.",
          "Unit & Reducer Test",
          "Any timeout or rejection cancels quest with 100% refund; reward pool split equally between consented workers",
          "PASS",
          "src/features/questBoard/teamAssemble/components/PartialGroupStartConsentSheet.tsx",
          "PASS",
          "ADR-0010 underfilled consent gate",
        ],
        [
          "LFC-007",
          "Lifecycle: Condition Edit",
          "10-Minute Consensus Window",
          "Hirer can edit quest conditions in QUEST_ASSIGNED; all assigned workers must vote within 10 minutes",
          "Unit & Reducer Test",
          "If any worker rejects or 10m expires, condition reverts to original; quest does not cancel",
          "PASS",
          "src/features/questBoard/shared/components/QuestConditionEditModal.tsx",
          "PASS",
          "10m consensus timer",
        ],
        [
          "LFC-008",
          "Lifecycle: Proof Submission",
          "Submission Artifacts",
          "Worker uploads 1-5 files/images and optional summary note before dueAt; draft saved locally during entry",
          "Unit & Reducer Test",
          "Cannot submit 0 files when proofRequired=true; cannot submit > 5 files; cannot submit after dueAt",
          "PASS",
          "src/features/workerWork/components/WorkerProofForm.tsx",
          "PASS",
          "proof-submission-contract.md",
        ],
        [
          "LFC-009",
          "Lifecycle: Proof Review",
          "24-Hour Auto-Approval",
          "Hirer reviews proof; if Hirer does not act within 24h, backend automatically triggers PROOF_APPROVED",
          "Unit & Reducer Test",
          "Hirer rejection requires non-empty reason; rejection triggers QUEST_FAILED and Admin Review Item",
          "PASS",
          "src/features/questBoard/review/useHirerProofReviewFeature.ts",
          "PASS",
          "No second rework round exists",
        ],
        [
          "LFC-010",
          "Lifecycle: Cancellation Tier",
          "QUEST_OPEN Cancellation",
          "Hirer cancels during QUEST_OPEN: 100% refund of Quest Escrow back to Hirer spendingBalanceSatang",
          "Unit & Reducer Test",
          "No worker penalty; all active candidate inquiries closed immediately",
          "PASS",
          "src/features/questBoard/manage/useHirerQuestManageFeature.ts",
          "PASS",
          "ADR-0003 Tier 1",
        ],
        [
          "LFC-011",
          "Lifecycle: Cancellation Tier",
          "QUEST_ASSIGNED Cancellation",
          "Hirer cancels during QUEST_ASSIGNED: 20% of worker reward pool paid to active workers, 80% + platform fee to Hirer",
          "Unit & Reducer Test",
          "Assigned workers compensated for reservation; quest transitions to QUEST_CANCELLED",
          "PASS",
          "src/features/questBoard/manage/useHirerQuestManageFeature.ts",
          "PASS",
          "ADR-0003 Tier 2",
        ],
        [
          "LFC-012",
          "Lifecycle: Cancellation Tier",
          "QUEST_IN_PROGRESS Cancellation",
          "Hirer cancels during QUEST_IN_PROGRESS: 100% worker reward paid to workers, platform fee kept; Hirer gets 0 refund",
          "Unit & Reducer Test",
          "Prevents work exploitation; active workers receive full reward",
          "PASS",
          "src/features/questBoard/manage/useHirerQuestManageFeature.ts",
          "PASS",
          "ADR-0003 Tier 3",
        ],
        [
          "LFC-013",
          "Lifecycle: Rating & Reviews",
          "7-Day Mutual Rating Window",
          "Hirer and Worker can submit reciprocal rating & review within 7 days of QUEST_COMPLETED/FAILED/CANCELLED",
          "Unit & Reducer Test",
          "Reviews locked after 7 days; rating score updates public profile reputation aggregate asynchronously",
          "PASS",
          "src/features/questBoard/review/useQuestReviewFeature.ts",
          "PASS",
          "rulebook/quest/rating-review-contract.md",
        ],
        [
          "FIN-001",
          "Finance: Satang Precision",
          "All internal currency stored as 32-bit integer satang (1 THB = 100 satang)",
          "Finance Rulebook",
          "Unit & Ledger Math Test",
          "Strictly non-negative integer math; floating-point money strictly prohibited",
          "PASS",
          "src/features/wallet/walletFormatting.ts",
          "PASS",
          "ADR-0005 satang representation",
        ],
        [
          "FIN-002",
          "Finance: Wallet Compartments",
          "4 distinct compartments: Spending, Earnings, Funding Reserved, Reserved for Payouts",
          "Finance Rulebook",
          "Unit & Ledger Math Test",
          "Total wallet capacity capped at 2,000,000,000 Satang (฿20,000,000); transactions exceeding cap fail closed",
          "PASS",
          "src/features/wallet/WalletScreen.tsx",
          "PASS",
          "wallet-compartment-contract.md",
        ],
        [
          "FIN-003",
          "Finance: Top-up QR Flow",
          "Member generates PromptPay QR payload; webhook or poll confirms receipt",
          "Finance Rulebook",
          "Unit & Ledger Math Test",
          "Double-entry credit to spendingBalanceSatang upon external payment clearing",
          "PASS",
          "src/features/wallet/TopUpScreen.tsx",
          "PASS",
          "topup-and-conversion-contract.md",
        ],
        [
          "FIN-004",
          "Finance: Escrow Lock",
          "Publishing quest locks questFundingTotal (worker rewards + platform fee) in escrow",
          "Finance Rulebook",
          "Unit & Ledger Math Test",
          "Debits spendingBalanceSatang, credits fundingReservedSatang in single transaction",
          "PASS",
          "src/features/createQuest/workflow/useCreateQuestFlow.ts",
          "PASS",
          "reward-money-contract.md",
        ],
        [
          "FIN-005",
          "Finance: Earnings Transfer",
          "Instant conversion of earningsBalanceSatang to spendingBalanceSatang",
          "Finance Rulebook",
          "Unit & Ledger Math Test",
          "Debits earningsBalanceSatang, credits spendingBalanceSatang; zero platform fee",
          "PASS",
          "src/features/wallet/components/TransferEarningsModal.tsx",
          "PASS",
          "Instant availability for quest publishing",
        ],
        [
          "FIN-006",
          "Finance: Payout Request",
          "Worker requests withdrawal of earningsBalanceSatang to verified bank/PromptPay",
          "Finance Rulebook",
          "Unit & Ledger Math Test",
          "Debits earningsBalanceSatang, credits reservedForPayoutsSatang until Admin approval",
          "PASS",
          "src/features/wallet/api/walletQueries.ts",
          "PASS",
          "payout-contract.md & gotcha fix",
        ],
        [
          "FIN-007",
          "Finance: Wallet Statuses",
          "Wallet statuses: ACTIVE, FROZEN, SUSPENDED, CLOSED",
          "Finance Rulebook",
          "Unit & Ledger Math Test",
          "FROZEN/SUSPENDED blocks new commitments (top-up, publish, join); active escrow runs to completion",
          "PASS",
          "src/features/wallet/walletModule.ts",
          "PASS",
          "finance-rulebook.md status guard",
        ],
        [
          "CHT-001",
          "Chat: Candidate Inquiry",
          "Strictly 2 members: Hirer + 1 Prospective Worker. Active only during QUEST_OPEN.",
          "Conversation Contract",
          "Integration & Rate Limit Test",
          "Zero KU Bot system messages allowed; human-to-human Q&A only",
          "PASS",
          "src/features/conversation/CandidateInquiryView.tsx",
          "PASS",
          "Disappears upon quest assignment",
        ],
        [
          "CHT-002",
          "Chat: Work Conversation",
          "Hirer + all current Active Workers. Opened upon first ASSIGNMENT_ACTIVE.",
          "Conversation Contract",
          "Integration & Rate Limit Test",
          "Official KU Bot posts immutable events (start work, proof submitted, deadline alert, completion)",
          "PASS",
          "src/features/conversation/WorkConversationView.tsx",
          "PASS",
          "Permanent read-only archive upon finish",
        ],
        [
          "CHT-003",
          "Chat: Rate Limiting",
          "Cooldown triggers after 5 messages in 5 seconds window",
          "Conversation Contract",
          "Integration & Rate Limit Test",
          'UI displays cooldown counter (e.g. "Wait 4s") and preserves draft input text without wiping',
          "PASS",
          "src/features/conversation/useChatController.ts",
          "PASS",
          "Draft preservation tested",
        ],
        [
          "CHT-004",
          "Chat: Safety & Reporting",
          "Any chat message can be reported for harassment or policy violation",
          "Conversation Contract",
          "Integration & Rate Limit Test",
          "Generates Admin Evidence Reference; Admin can inspect reported thread via dispute portal",
          "PASS",
          "src/features/report/ReportScreen.tsx",
          "PASS",
          "admin-conduct-report-contract.md",
        ],
        [
          "ARC-001",
          "Architecture: Server State",
          "All asynchronous server queries & mutations managed by TanStack Query v5",
          "TanStack Query (@tanstack/react-query v5.103)",
          "Typecheck & Architecture Audit",
          "No manual useEffect data fetching; no custom fetching cache in React Context",
          "PASS",
          "src/infrastructure/query/queryClient.ts",
          "PASS",
          "Clean query keys & invalidations",
        ],
        [
          "ARC-002",
          "Architecture: Client / App State",
          "Domain client state managed by lightweight Zustand stores",
          "Zustand v5 (roleWorkspaceStore, questDraftStore)",
          "Typecheck & Architecture Audit",
          "Zero application-owned React Context for mutable app state (ADR-0012)",
          "PASS",
          "src/features/workspace/roleWorkspaceStore.ts",
          "PASS",
          "ADR-0012 state boundaries",
        ],
        [
          "ARC-003",
          "Architecture: Complex Workflows",
          "Pure domain reducers hosted by Zustand vanilla or pure functions",
          "Pure TypeScript Reducers (questWorkflow, workerWorkProjection)",
          "Typecheck & Architecture Audit",
          "No business logic inside React UI components",
          "PASS",
          "src/features/questBoard/workflow/questWorkflow.ts",
          "PASS",
          "Deterministic testing",
        ],
        [
          "ARC-004",
          "Architecture: Persistent Storage",
          "Explicit storage adapters: SecureStore for session, AsyncStorage for drafts/prefs",
          "expo-secure-store + persistent storage adapters",
          "Typecheck & Architecture Audit",
          "No sensitive auth tokens or session cookies in unencrypted AsyncStorage",
          "PASS",
          "src/infrastructure/storage/secureStorageAdapter.ts",
          "PASS",
          "Safe token isolation",
        ],
        [
          "ARC-005",
          "Architecture: WebSocket Client",
          "WebSocket connections must supply Origin: kuquestmobile:// and Cookie",
          "src/api/ServerSocket.ts (openServerSocket)",
          "Typecheck & Architecture Audit",
          "Direct new WebSocket() without Origin causes 4403 rejection on staging backend",
          "PASS",
          "src/api/ServerSocket.ts",
          "PASS",
          "Gotcha resolved 2026-09-26",
        ],
        [
          "UI-001",
          "UI & Native: Design Tokens & Colors",
          "NativeWind v4 with strict semantic ramp tokens (ku-primary, ku-surface, etc.)",
          "UI Design Rules & Tokens",
          "Smoke & Theme Test",
          "Workspace dynamic theme: Hirer (sage) vs Worker (emerald) swaps seamlessly",
          "PASS",
          "src/theme/colors.ts",
          "PASS",
          "DESIGN.md compliant",
        ],
        [
          "UI-002",
          "UI & Native: Typography & Sizing",
          "Be Vietnam Pro font family; responsive layout without hardcoded fixed heights",
          "UI Design Rules & Tokens",
          "Smoke & Theme Test",
          "Android fontScale 1.3+ support: text wraps cleanly without clipping or truncation",
          "PASS",
          "src/theme/typography.ts",
          "PASS",
          "Verified across density buckets",
        ],
        [
          "UI-003",
          "UI & Native: Touch Targets",
          "All interactive touch targets must be at least 44x44pt (Apple HIG / Android Material)",
          "UI Design Rules & Tokens",
          "Smoke & Theme Test",
          "Buttons, tab items, back arrows, list row items include hitSlop or min dimensions",
          "PASS",
          "docs/agents/ui-design-rules.md",
          "PASS",
          "Accessibility touch target pass",
        ],
        [
          "UI-004",
          "UI & Native: Screen Reader Semantics",
          "All controls require accessible labels, roles, and hint where state is not obvious",
          "UI Design Rules & Tokens",
          "Smoke & Theme Test",
          "accessibilityRole (button, tab, header), accessibilityState (selected, disabled)",
          "PASS",
          "src/components/ui/AccessibilityWrapper.tsx",
          "PASS",
          "Native A11y tree verified",
        ],
        [
          "UI-005",
          "UI & Native: Safe Area Insets",
          "All screens respect react-native-safe-area-context edge insets",
          "UI Design Rules & Tokens",
          "Smoke & Theme Test",
          "Header avoids status bar and Dynamic Island; footer avoids home indicator bar",
          "PASS",
          "src/app/_layout.tsx",
          "PASS",
          "iOS & Android safe layout",
        ],
      ],
    },
  ];

  for (let s = 0; s < sheetsData.length; s++) {
    const item = sheetsData[s];
    let sheet = ss.getSheetByName(item.sheetName);
    if (!sheet) {
      sheet = ss.insertSheet(item.sheetName);
    }
    sheet.clear();
    sheet.setTabColor(item.color);

    const rows = item.data;
    if (!rows || rows.length === 0) continue;

    const range = sheet.getRange(1, 1, rows.length, rows[0].length);
    range.setValues(rows);

    // Style Header Row
    const headerRange = sheet.getRange(1, 1, 1, rows[0].length);
    headerRange
      .setBackground(item.color)
      .setFontColor("#FFFFFF")
      .setFontWeight("bold")
      .setHorizontalAlignment("center")
      .setVerticalAlignment("middle");
    sheet.setRowHeight(1, 36);

    // Freeze Header Row
    sheet.setFrozenRows(1);

    // Auto-fit & Wrap
    sheet
      .getRange(2, 1, rows.length - 1, rows[0].length)
      .setWrap(true)
      .setVerticalAlignment("middle");

    // Set column borders
    sheet
      .getRange(1, 1, rows.length, rows[0].length)
      .setBorder(
        true,
        true,
        true,
        true,
        true,
        true,
        "#E0E0E0",
        SpreadsheetApp.BorderStyle.SOLID
      );

    // Add dropdown validation for Pass/Fail column
    const lastColIndex = rows[0].length;
    // Check header for Pass/Fail
    let passCol = -1;
    for (let c = 0; c < rows[0].length; c++) {
      if (
        rows[0][c].includes("Pass/Fail") ||
        rows[0][c].includes("Audit Status") ||
        rows[0][c].includes("Audit Check")
      ) {
        passCol = c + 1;
        break;
      }
    }
    if (passCol > 0 && rows.length > 1) {
      const rule = SpreadsheetApp.newDataValidation()
        .requireValueInList(["PASS", "FAIL", "PENDING", "N/A"], true)
        .build();
      sheet.getRange(2, passCol, rows.length - 1, 1).setDataValidation(rule);
    }

    // Default column widths
    for (let c = 1; c <= rows[0].length; c++) {
      sheet.setColumnWidth(c, 180);
    }
    sheet.setColumnWidth(1, 100);
    if (rows[0].length >= 3) sheet.setColumnWidth(3, 200);
    if (rows[0].length >= 6) sheet.setColumnWidth(6, 280);
  }

  // Remove default "Sheet1" if present
  const defaultSheet = ss.getSheetByName("Sheet1");
  if (defaultSheet && ss.getSheets().length > 1) {
    ss.deleteSheet(defaultSheet);
  }
}
