const styles = {
  safeArea: 'bg-ku-background flex-1',
  scrollContent: 'pb-[132px] px-[24px]',
  header: 'pt-[16px]',
  tagRow: 'flex-row flex-wrap gap-[4px] mt-[12px]',
  tag: 'bg-ku-surface-accent rounded-ku-pill px-[8px] py-[4px] text-ku-primary font-ku-medium text-ku-label',
  title: 'text-ku-text-strong font-ku-bold text-ku-title-large mt-[4px]',
  creatorRow: 'items-center flex-row mt-[12px]',
  creatorAvatar: 'items-center bg-ku-surface-success rounded-ku-pill h-[32px] justify-center w-[32px]',
  creatorCopy: 'flex-1 min-w-0 ml-[8px]',
  creatorLabel: 'text-ku-text-muted font-ku-regular text-ku-label',
  creatorValue: 'text-ku-text-strong font-ku-medium text-ku-body-small mt-[1px]',
  imageGallery: 'gap-[8px] mt-[18px]',
  imageThumbnailRow: 'flex-row gap-[8px]',
  questImage: 'bg-ku-surface-image rounded-[16px] overflow-hidden',
  questImageFeatured: 'h-[196px] w-full',
  questImageThumbnail: 'flex-1 h-[76px] min-w-0',
  questImageFallback: 'items-center bg-ku-surface-muted justify-center p-[8px]',
  questImageFallbackFeatured: 'h-[196px] w-full',
  questImageFallbackThumbnail: 'flex-1 h-[76px] min-w-0',
  questImageFallbackText: 'text-ku-text-muted font-ku-regular text-ku-label text-center mt-[4px]',
  heroCard: 'bg-ku-surface-accent border-ku-border-accent rounded-[18px] border mt-[20px] p-[16px]',
  heroPrimary: 'items-center flex-row justify-between pb-[14px]',
  heroRewardValue: 'text-ku-primary font-ku-bold text-ku-title mt-[2px]',
  heroSpots: 'bg-ku-card rounded-[12px] min-w-[78px] px-[12px] py-[8px]',
  heroSpotsLabel: 'text-ku-text-secondary font-ku-regular text-ku-label',
  heroSpotsValue: 'text-ku-primary font-ku-bold text-ku-subtitle mt-[1px]',
  heroDetails: 'border-ku-border-accent border-t flex-row pt-[14px]',
  heroItem: 'flex-1 flex-row min-w-0',
  heroItemDivider: 'border-l-ku-border-accent border-l ml-[10px] pl-[12px]',
  heroItemIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[30px] justify-center shrink-0 w-[30px]',
  heroItemCopy: 'flex-1 min-w-0 ml-[8px]',
  heroLabel: 'text-ku-text-secondary font-ku-regular text-ku-label',
  heroValue: 'text-ku-primary font-ku-bold text-ku-body mt-[2px]',
  heroDetail: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[2px]',
  heroLocation: 'items-start border-ku-border-accent border-t flex-row gap-[10px] mt-[14px] pt-[14px]',
  heroLocationCopy: 'flex-1 min-w-0',
  heroLocationValue: 'text-ku-text-strong font-ku-medium text-ku-body mt-[2px]',
  scheduleCard: 'bg-ku-surface border-ku-border-subtle rounded-[16px] border mt-[24px] p-[16px]',
  scheduleHeader: 'items-center flex-row',
  scheduleHeaderIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[36px] justify-center shrink-0 w-[36px]',
  scheduleHeaderCopy: 'flex-1 min-w-0 ml-[10px]',
  scheduleTitle: 'text-ku-text-strong font-ku-bold text-ku-section',
  scheduleDescription: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[1px]',
  scheduleTimeline: 'flex-row mt-[20px]',
  timelineRail: 'items-center w-[16px]',
  timelineDotActive: 'bg-ku-primary rounded-ku-pill h-[10px] w-[10px]',
  timelineDot: 'bg-ku-border-accent border-ku-primary border-[2px] rounded-ku-pill h-[10px] w-[10px]',
  timelineLine: 'bg-ku-border-accent flex-1 w-[2px]',
  timelineEvents: 'flex-1 gap-[24px] ml-[12px]',
  timelineEvent: 'min-h-[64px]',
  timelineLabel: 'text-ku-text-secondary font-ku-medium text-ku-label',
  timelineDate: 'text-ku-text-strong font-ku-bold text-ku-body mt-[2px]',
  timelineTimeRow: 'items-center flex-row flex-wrap gap-[4px] mt-[6px]',
  timelineTimeLabel: 'text-ku-text-secondary font-ku-regular text-ku-label',
  timelineTime: 'text-ku-primary font-ku-bold text-ku-body-small ml-[2px]',
  timelineDescription: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[6px]',
  section: 'mt-[32px]',
  sectionTitle: 'text-ku-text-strong font-ku-bold text-ku-section mb-[8px]',
  body: 'text-ku-text-secondary font-ku-regular text-ku-body',
  descriptionCard: 'bg-ku-surface border-ku-border-subtle rounded-[14px] border p-[16px]',
  requirementCard: 'bg-ku-surface border-ku-border-subtle rounded-[14px] border gap-[10px] p-[12px]',
  requirementRow: 'items-start bg-ku-surface-accent rounded-[12px] flex-row p-[12px]',
  requirementIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[32px] justify-center shrink-0 w-[32px]',
  requirementCopy: 'flex-1 min-w-0 ml-[10px]',
  requirementLabel: 'text-ku-text-muted font-ku-medium text-ku-label',
  requirementValue: 'text-ku-text-strong font-ku-medium text-ku-body-small',
  requirementDescription: 'text-ku-text-secondary font-ku-regular text-ku-meta mt-[2px]',
  confirmHeader: 'items-center flex-row justify-between',
  sheetCloseButton: 'items-center rounded-ku-pill h-[44px] justify-center ml-[8px] w-[44px] active:bg-ku-surface-muted',
  statusCard: 'items-center bg-ku-surface-success border-ku-border-success rounded-[16px] border mt-[24px] p-[16px]',
  statusCardBlocked: 'bg-ku-surface-muted border-ku-border-subtle',
  statusCardOwner: 'bg-ku-surface-accent border-ku-border-accent',
  statusCardMuted: 'bg-ku-surface-muted border-ku-border-subtle',
  statusTitle: 'text-ku-primary font-ku-bold text-ku-emphasis text-center',
  statusDescription: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[4px] text-center',
  statusAction: 'items-center border-ku-primary rounded-ku-pill border mt-[12px] min-h-[48px] justify-center px-[16px]',
  statusActionText: 'text-ku-primary font-ku-semibold text-ku-body-small',
  actionBar: 'bg-ku-background border-t-ku-border-subtle border-t bottom-0 left-0 p-[16px] absolute right-0',
  primaryAction: 'items-center bg-ku-primary rounded-ku-pill justify-center min-h-[52px] px-[24px]',
  primaryActionText: 'text-ku-white font-ku-semibold text-ku-control',
  leaveAction: 'items-center border-ku-danger-dark rounded-ku-pill border flex-row gap-[8px] justify-center min-h-[52px] px-[24px]',
  leaveActionText: 'text-ku-danger-dark font-ku-semibold text-ku-control',
  modalBackdrop: 'bg-ku-overlay flex-1 justify-end',
  confirmSheet: 'bg-ku-background rounded-tl-[24px] rounded-tr-[24px] p-[24px]',
  confirmTitle: 'text-ku-text-strong font-ku-bold text-ku-title-small',
  confirmDescription: 'text-ku-text-secondary font-ku-regular text-ku-control mt-[4px]',
  confirmSummary: 'bg-ku-surface-accent rounded-[14px] gap-[6px] mt-[16px] p-[16px]',
  confirmSummaryText: 'text-ku-text-strong font-ku-medium text-ku-body-small',
  confirmActions: 'flex-row gap-[8px] mt-[24px]',
  cancelAction: 'items-center border-ku-border rounded-ku-pill border flex-1 justify-center min-h-[50px]',
  cancelActionText: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  confirmAction: 'items-center bg-ku-primary rounded-ku-pill flex-[1.4] justify-center min-h-[50px]',
  confirmActionText: 'text-ku-white font-ku-semibold text-ku-body-small',
} as const;

export default styles;
