const styles = {
  safeArea: 'bg-ku-background flex-1',
  scrollContent: 'pb-[132px] px-[24px]',
  header: 'pt-[16px]',
  category: 'text-ku-primary font-ku-semibold text-[12px] tracking-[0.4px] uppercase',
  title: 'text-ku-text-strong font-ku-bold text-[29px] leading-[37px] mt-[4px]',
  creator: 'text-ku-text-secondary font-ku-regular text-[13px] mt-[8px]',
  heroCard: 'bg-ku-surface-accent border-ku-border-accent rounded-[18px] border mt-[24px] p-[16px]',
  heroPrimary: 'pb-[8px]',
  heroDetails: 'flex-row',
  heroItem: 'flex-1',
  heroItemDivider: 'border-l-ku-border-accent border-l ml-[8px] pl-[8px]',
  heroLabel: 'text-ku-text-secondary font-ku-regular text-[11px]',
  heroValue: 'text-ku-primary font-ku-bold text-[18px] mt-[2px]',
  heroDetail: 'text-ku-text-secondary font-ku-regular text-[11px] mt-[2px]',
  section: 'mt-[32px]',
  sectionTitle: 'text-ku-text-strong font-ku-bold text-[19px] mb-[8px]',
  body: 'text-ku-text-secondary font-ku-regular text-[15px] leading-[24px]',
  requirementCard: 'bg-ku-white border-ku-border-subtle rounded-[14px] border gap-[8px] p-[16px]',
  requirementRow: 'gap-[2px]',
  requirementLabel: 'text-ku-text-muted font-ku-medium text-[12px]',
  requirementValue: 'text-ku-text-strong font-ku-medium text-[13px] leading-[20px]',
  confirmHeader: 'items-center flex-row justify-between',
  statusCard: 'items-center bg-ku-surface-success border-ku-border-success rounded-[16px] border mt-[24px] p-[16px]',
  statusCardBlocked: 'bg-ku-surface-muted border-ku-border-subtle',
  statusTitle: 'text-ku-primary font-ku-bold text-[17px] text-center',
  statusDescription: 'text-ku-text-secondary font-ku-regular text-[13px] leading-[20px] mt-[4px] text-center',
  actionBar: 'bg-ku-background border-t-ku-border-subtle border-t bottom-0 left-0 p-[16px] absolute right-0',
  primaryAction: 'items-center bg-ku-primary rounded-ku-pill justify-center min-h-[52px] px-[24px]',
  primaryActionText: 'text-ku-white font-ku-semibold text-[15px]',
  modalBackdrop: 'bg-ku-overlay flex-1 justify-end',
  confirmSheet: 'bg-ku-background rounded-tl-[24px] rounded-tr-[24px] p-[24px]',
  confirmTitle: 'text-ku-text-strong font-ku-bold text-[22px]',
  confirmDescription: 'text-ku-text-secondary font-ku-regular text-[14px] leading-[22px] mt-[4px]',
  confirmSummary: 'bg-ku-surface-accent rounded-[14px] gap-[4px] mt-[16px] p-[16px]',
  confirmSummaryText: 'text-ku-text-strong font-ku-medium text-[14px]',
  confirmActions: 'flex-row gap-[8px] mt-[24px]',
  cancelAction: 'items-center border-ku-border rounded-ku-pill border flex-1 justify-center min-h-[50px]',
  cancelActionText: 'text-ku-text-strong font-ku-semibold text-[14px]',
  confirmAction: 'items-center bg-ku-primary rounded-ku-pill flex-[1.4] justify-center min-h-[50px]',
  confirmActionText: 'text-ku-white font-ku-semibold text-[14px]',
} as const;

export default styles;
