import type { QuestBoardQuest } from './types';

export const questFixtures: QuestBoardQuest[] = [
  {
    id: 'design-faculty-poster',
    title: 'Design a faculty event poster',
    category: 'design',
    tags: ['Design & creative', 'Campus life'],
    description: 'Create a welcoming poster for the faculty open house.',
    completionCriteria: 'A final PNG poster is approved by the event team.',
    proofRequired: 'required',
    rewardPerPerson: 700,
    headcount: 2,
    acceptedParticipants: 0,
    startDate: '2026-08-14',
    deadline: '2026-08-16',
    timeRange: '17:00–20:00',
    postedAt: '2026-08-10T09:00:00.000Z',
    location: 'On campus',
    locationMode: 'on-campus',
    participationMode: 'single',
    candidateMode: 'REVIEW',
    creator: { name: 'Nicha S.', faculty: 'Architecture' },
    studentInterestMatch: true,
    ownerStudentId: 'student-creator-1',
  },
  {
    id: 'react-bug-fix',
    title: 'Fix a small React bug',
    category: 'technology',
    tags: ['Technology'],
    description: 'Resolve a small UI issue in a student club website.',
    completionCriteria: 'The fix passes review and works on mobile.',
    proofRequired: 'optional',
    rewardPerPerson: 450,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: '2026-08-13',
    deadline: '2026-08-18',
    timeRange: '09:00–12:00',
    postedAt: '2026-08-11T09:00:00.000Z',
    location: 'Online',
    locationMode: 'online',
    participationMode: 'single',
    candidateMode: 'NO_CANDIDATE',
    creator: { name: 'Ploy K.', faculty: 'Engineering' },
    studentInterestMatch: false,
    ownerStudentId: 'student-creator-2',
  },
  {
    id: 'first-year-tutor',
    title: 'Tutor a first-year student',
    category: 'tutoring',
    tags: ['Tutoring', 'Study support'],
    description: 'Help a first-year Student understand introductory programming.',
    completionCriteria: 'Complete two agreed tutoring sessions.',
    proofRequired: 'optional',
    rewardPerPerson: 800,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: '2026-08-15',
    deadline: '2026-08-21',
    timeRange: '12:00–18:00',
    postedAt: '2026-08-08T09:00:00.000Z',
    location: 'Online or KU library',
    locationMode: 'online',
    participationMode: 'single',
    candidateMode: 'REVIEW',
    creator: { name: 'Mild P.', faculty: 'Science' },
    studentInterestMatch: true,
    ownerStudentId: 'student-creator-3',
  },
  {
    id: 'campus-food-map',
    title: 'Map the campus food spots',
    category: 'campus-life',
    tags: ['Campus life', 'Research'],
    description: 'Collect opening hours and locations for popular food spots.',
    completionCriteria: 'Submit a verified list with map pins.',
    proofRequired: 'required',
    rewardPerPerson: 250,
    headcount: 3,
    acceptedParticipants: 1,
    startDate: '2026-08-13',
    deadline: '2026-08-20',
    timeRange: '10:00–13:00',
    postedAt: '2026-08-09T09:00:00.000Z',
    location: 'On campus',
    locationMode: 'on-campus',
    participationMode: 'team',
    candidateMode: 'NO_CANDIDATE',
    creator: { name: 'Beam T.', faculty: 'Education' },
    studentInterestMatch: false,
    ownerStudentId: 'student-creator-4',
  },
  {
    id: 'club-landing-page',
    title: 'Build a club landing page',
    category: 'technology',
    tags: ['Technology', 'Web development'],
    description: 'Build a simple responsive landing page for a student club.',
    completionCriteria: 'A deployed page matches the agreed content and layout.',
    proofRequired: 'required',
    rewardPerPerson: 1400,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: '2026-08-17',
    deadline: '2026-08-26',
    timeRange: '18:00–21:00',
    postedAt: '2026-08-12T07:30:00.000Z',
    location: 'Online',
    locationMode: 'online',
    participationMode: 'single',
    candidateMode: 'REVIEW',
    creator: { name: 'First-year Club', faculty: 'Engineering' },
    studentInterestMatch: false,
    ownerStudentId: 'student-creator-5',
  },
  {
    id: 'faculty-fair-photo',
    title: 'Photograph the faculty fair',
    category: 'design',
    tags: ['Design & creative', 'Events'],
    description: 'Capture a small set of candid photos during the faculty fair.',
    completionCriteria: 'Deliver 20 edited photos within two days.',
    proofRequired: 'required',
    rewardPerPerson: 600,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: '2026-08-16',
    deadline: '2026-08-19',
    timeRange: '15:00–18:00',
    postedAt: '2026-08-11T12:00:00.000Z',
    location: 'On campus',
    locationMode: 'on-campus',
    participationMode: 'single',
    candidateMode: 'REVIEW',
    creator: { name: 'Faculty Communications', faculty: 'Agriculture' },
    studentInterestMatch: false,
    ownerStudentId: 'student-creator-6',
  },
];
