import type { QuestBoardQuest } from './types';

export const questFixtures: QuestBoardQuest[] = [
  {
    id: 'move-boxes', title: 'Help move boxes to the dorm', tags: ['moving'],
    description: 'Help carry labelled boxes from the parking area to Dorm 13.',
    completionCriteria: 'All boxes are delivered safely to the assigned room.', proofRequired: 'optional',
    rewardPerPerson: 300, headcount: 2, acceptedParticipants: 0,
    startDate: '2026-08-14', deadline: '2026-08-16', timeRange: '17:00–19:00', postedAt: '2026-08-13T15:00:00.000Z',
    location: 'หอพัก 13', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'REVIEW',
    creator: { name: 'Nicha S.', faculty: 'Architecture' },
    imageUris: [
      'https://placehold.co/800x500/E2EEE4/014925/png?text=Boxes+1',
      'https://placehold.co/800x500/E2EEE4/014925/png?text=Boxes+2',
      'https://placehold.co/800x500/E2EEE4/014925/png?text=Boxes+3',
    ],
    studentInterestMatch: true, ownerStudentId: 'student-creator-1',
  },
  {
    id: 'clean-fan', title: 'Clean a dorm fan', tags: ['cleaning'],
    description: 'Clean a shared fan under Dorm 13 before the evening.',
    completionCriteria: 'The fan is clean and working after the visit.', proofRequired: 'optional',
    rewardPerPerson: 150, headcount: 2, acceptedParticipants: 0,
    startDate: '2026-08-13', deadline: '2026-08-18', timeRange: '09:00–12:00', postedAt: '2026-08-13T14:00:00.000Z',
    location: 'ใต้หอพัก 13', locationMode: 'on-campus', participationMode: 'team', candidateMode: 'NO_CANDIDATE',
    creator: { name: 'Ploy K.', faculty: 'Engineering' }, studentInterestMatch: false, ownerStudentId: 'student-creator-2',
  },
  {
    id: 'print-documents', title: 'Photocopy course documents', tags: ['printing'],
    description: 'Photocopy course documents and deliver them to the requester.',
    completionCriteria: 'Clear copies are delivered in the requested quantity.', proofRequired: 'optional',
    rewardPerPerson: 80, headcount: 1, acceptedParticipants: 0,
    startDate: '2026-08-15', deadline: '2026-08-21', timeRange: '12:00–13:00', postedAt: '2026-08-13T13:00:00.000Z',
    location: 'ร้านถ่ายเอกสารใกล้หอพัก 13', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'NO_CANDIDATE',
    creator: { name: 'Mild P.', faculty: 'Science' }, studentInterestMatch: true, ownerStudentId: 'student-creator-3',
  },
  {
    id: 'buy-lunch', title: 'Buy lunch from the canteen', tags: ['delivery'],
    description: 'Buy a meal from the canteen and bring it to the requester.',
    completionCriteria: 'The requested meal is delivered complete and on time.', proofRequired: 'none',
    rewardPerPerson: 100, headcount: 1, acceptedParticipants: 0,
    startDate: '2026-08-13', deadline: '2026-08-20', timeRange: '10:00–13:00', postedAt: '2026-08-13T12:00:00.000Z',
    location: 'โรงอาหารกลาง', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'REVIEW',
    creator: { name: 'Beam T.', faculty: 'Education' }, studentInterestMatch: false, ownerStudentId: 'student-creator-4',
  },
  {
    id: 'run-together', title: 'Go running together', tags: ['exercise'],
    description: 'Join a relaxed evening run around campus.',
    completionCriteria: 'Complete the agreed route together.', proofRequired: 'none',
    rewardPerPerson: 120, headcount: 3, acceptedParticipants: 1,
    startDate: '2026-08-17', deadline: '2026-08-26', timeRange: '18:00–19:00', postedAt: '2026-08-13T11:00:00.000Z',
    location: 'สนามอินทรีจันทรสถิตย์', locationMode: 'on-campus', participationMode: 'team', candidateMode: 'REVIEW',
    creator: { name: 'Fern L.', faculty: 'Engineering' }, studentInterestMatch: false, ownerStudentId: 'student-creator-5',
  },
  {
    id: 'move-water-packs', title: 'Carry water packs to the dorm', tags: ['moving'],
    description: 'Help carry bottled water from the shop to Dorm 12.', completionCriteria: 'All water packs reach the dorm room.', proofRequired: 'optional',
    rewardPerPerson: 100, headcount: 1, acceptedParticipants: 0, startDate: '2026-08-15', deadline: '2026-08-17', timeRange: '15:00–16:00', postedAt: '2026-08-12T08:00:00.000Z',
    location: 'หอพัก 12', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'NO_CANDIDATE', creator: { name: 'Aom R.', faculty: 'Humanities' }, studentInterestMatch: true, ownerStudentId: 'student-creator-6',
  },
  {
    id: 'move-club-equipment', title: 'Move club equipment', tags: ['moving'],
    description: 'Move event equipment from the storage room to the activity hall.', completionCriteria: 'All listed equipment is set up in the hall.', proofRequired: 'required',
    rewardPerPerson: 250, headcount: 3, acceptedParticipants: 0, startDate: '2026-08-18', deadline: '2026-08-20', timeRange: '13:00–16:00', postedAt: '2026-08-12T08:15:00.000Z',
    location: 'อาคารกิจกรรมนิสิต', locationMode: 'on-campus', participationMode: 'team', candidateMode: 'REVIEW', creator: { name: 'Non P.', faculty: 'Student Affairs' }, studentInterestMatch: false, ownerStudentId: 'student-creator-7',
  },
  {
    id: 'clean-study-table', title: 'Clean a study table', tags: ['cleaning'],
    description: 'Wipe and organise a shared study table in the library.', completionCriteria: 'The table is clean and ready to use.', proofRequired: 'none',
    rewardPerPerson: 60, headcount: 1, acceptedParticipants: 0, startDate: '2026-08-14', deadline: '2026-08-16', timeRange: '10:00–11:00', postedAt: '2026-08-12T08:30:00.000Z',
    location: 'สำนักหอสมุด', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'NO_CANDIDATE', creator: { name: 'Pim C.', faculty: 'Engineering' }, studentInterestMatch: false, ownerStudentId: 'student-creator-8',
  },
  {
    id: 'clean-bike', title: 'Clean a bicycle', tags: ['cleaning'],
    description: 'Wash a bicycle and wipe it dry near the dorm.', completionCriteria: 'The bicycle is clean and dry.', proofRequired: 'optional',
    rewardPerPerson: 120, headcount: 1, acceptedParticipants: 0, startDate: '2026-08-16', deadline: '2026-08-19', timeRange: '16:00–17:00', postedAt: '2026-08-12T08:45:00.000Z',
    location: 'ลานจอดจักรยานหอพัก 13', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'REVIEW', creator: { name: 'Fah W.', faculty: 'Agriculture' }, studentInterestMatch: true, ownerStudentId: 'student-creator-9',
  },
  {
    id: 'print-presentation', title: 'Print presentation slides', tags: ['printing'],
    description: 'Print a set of presentation slides before class.', completionCriteria: 'The printed slides are delivered without missing pages.', proofRequired: 'optional',
    rewardPerPerson: 70, headcount: 1, acceptedParticipants: 0, startDate: '2026-08-14', deadline: '2026-08-15', timeRange: '08:00–09:00', postedAt: '2026-08-12T09:00:00.000Z',
    location: 'ร้านถ่ายเอกสารคณะวิศวกรรมศาสตร์', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'NO_CANDIDATE', creator: { name: 'Mew J.', faculty: 'Engineering' }, studentInterestMatch: false, ownerStudentId: 'student-creator-10',
  },
  {
    id: 'print-event-posters', title: 'Print event posters', tags: ['printing'],
    description: 'Print and collect posters for a faculty event.', completionCriteria: 'Ten clear posters are delivered to the organiser.', proofRequired: 'required',
    rewardPerPerson: 180, headcount: 1, acceptedParticipants: 0, startDate: '2026-08-17', deadline: '2026-08-21', timeRange: '11:00–12:00', postedAt: '2026-08-12T09:15:00.000Z',
    location: 'ร้านถ่ายเอกสารหน้า มก.', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'REVIEW', creator: { name: 'Ton K.', faculty: 'Science' }, studentInterestMatch: true, ownerStudentId: 'student-creator-11',
  },
  {
    id: 'deliver-snacks', title: 'Deliver snacks to a study group', tags: ['delivery'],
    description: 'Pick up snacks from the convenience store and deliver them to a study group.', completionCriteria: 'All requested snacks are delivered.', proofRequired: 'none',
    rewardPerPerson: 90, headcount: 1, acceptedParticipants: 0, startDate: '2026-08-15', deadline: '2026-08-18', timeRange: '14:00–15:00', postedAt: '2026-08-12T09:30:00.000Z',
    location: 'สำนักหอสมุด', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'NO_CANDIDATE', creator: { name: 'Ploy N.', faculty: 'Humanities' }, studentInterestMatch: false, ownerStudentId: 'student-creator-12',
  },
  {
    id: 'deliver-parcel', title: 'Deliver a parcel to the dorm', tags: ['delivery'],
    description: 'Collect a parcel at the campus post point and bring it to Dorm 11.', completionCriteria: 'The parcel is delivered to the requester.', proofRequired: 'optional',
    rewardPerPerson: 110, headcount: 1, acceptedParticipants: 0, startDate: '2026-08-18', deadline: '2026-08-22', timeRange: '13:00–14:00', postedAt: '2026-08-12T09:45:00.000Z',
    location: 'หอพัก 11', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'REVIEW', creator: { name: 'Beam T.', faculty: 'Education' }, studentInterestMatch: true, ownerStudentId: 'student-creator-13',
  },
  {
    id: 'walk-together', title: 'Go for a walk together', tags: ['exercise'],
    description: 'Take a relaxed walk around campus before sunset.', completionCriteria: 'Complete the planned walking route together.', proofRequired: 'none',
    rewardPerPerson: 50, headcount: 2, acceptedParticipants: 0, startDate: '2026-08-16', deadline: '2026-08-20', timeRange: '17:00–18:00', postedAt: '2026-08-12T10:00:00.000Z',
    location: 'สวนวชิรเบญจทัศ', locationMode: 'on-campus', participationMode: 'team', candidateMode: 'NO_CANDIDATE', creator: { name: 'Mint S.', faculty: 'Economics' }, studentInterestMatch: false, ownerStudentId: 'student-creator-14',
  },
  {
    id: 'play-badminton', title: 'Play badminton together', tags: ['exercise'],
    description: 'Join a friendly badminton session after class.', completionCriteria: 'Attend and play for the agreed session.', proofRequired: 'none',
    rewardPerPerson: 80, headcount: 3, acceptedParticipants: 0, startDate: '2026-08-19', deadline: '2026-08-23', timeRange: '18:00–20:00', postedAt: '2026-08-12T10:15:00.000Z',
    location: 'สนามแบดมินตัน มก.', locationMode: 'on-campus', participationMode: 'team', candidateMode: 'REVIEW', creator: { name: 'Karn P.', faculty: 'Sports Science' }, studentInterestMatch: true, ownerStudentId: 'student-creator-15',
  },
  {
    id: 'move-plants', title: 'Move plants to a new room', tags: ['moving'],
    description: 'Help move potted plants into a new dorm room.', completionCriteria: 'All plants arrive without damage.', proofRequired: 'optional',
    rewardPerPerson: 100, headcount: 1, acceptedParticipants: 0, startDate: '2026-08-20', deadline: '2026-08-24', timeRange: '09:00–10:00', postedAt: '2026-08-12T10:30:00.000Z',
    location: 'หอพัก 9', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'NO_CANDIDATE', creator: { name: 'Dao L.', faculty: 'Forestry' }, studentInterestMatch: false, ownerStudentId: 'student-creator-16',
  },
  {
    id: 'clean-fridge', title: 'Clean a dorm fridge', tags: ['cleaning'],
    description: 'Clean the inside of a small refrigerator in a dorm room.', completionCriteria: 'The refrigerator is clean and dry.', proofRequired: 'optional',
    rewardPerPerson: 140, headcount: 1, acceptedParticipants: 0, startDate: '2026-08-21', deadline: '2026-08-25', timeRange: '14:00–15:00', postedAt: '2026-08-12T10:45:00.000Z',
    location: 'หอพัก 10', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'REVIEW', creator: { name: 'Game T.', faculty: 'Veterinary Medicine' }, studentInterestMatch: true, ownerStudentId: 'student-creator-17',
  },
  {
    id: 'print-notes', title: 'Print lecture notes', tags: ['printing'],
    description: 'Print lecture notes for an afternoon class.', completionCriteria: 'The complete notes are handed over before class.', proofRequired: 'none',
    rewardPerPerson: 60, headcount: 1, acceptedParticipants: 0, startDate: '2026-08-22', deadline: '2026-08-26', timeRange: '10:00–11:00', postedAt: '2026-08-12T11:00:00.000Z',
    location: 'คณะวิทยาศาสตร์', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'NO_CANDIDATE', creator: { name: 'May K.', faculty: 'Science' }, studentInterestMatch: false, ownerStudentId: 'student-creator-18',
  },
  {
    id: 'deliver-drinks', title: 'Deliver drinks to the library', tags: ['delivery'],
    description: 'Buy drinks and bring them to a group studying at the library.', completionCriteria: 'All drinks are delivered to the correct table.', proofRequired: 'none',
    rewardPerPerson: 80, headcount: 1, acceptedParticipants: 0, startDate: '2026-08-23', deadline: '2026-08-27', timeRange: '15:00–16:00', postedAt: '2026-08-12T11:15:00.000Z',
    location: 'สำนักหอสมุด', locationMode: 'on-campus', participationMode: 'single', candidateMode: 'REVIEW', creator: { name: 'Ice N.', faculty: 'Business Administration' }, studentInterestMatch: true, ownerStudentId: 'student-creator-19',
  },
  {
    id: 'stretch-together', title: 'Stretch together after class', tags: ['exercise'],
    description: 'Do a short guided stretching session after class.', completionCriteria: 'Complete the full stretching session together.', proofRequired: 'none',
    rewardPerPerson: 50, headcount: 4, acceptedParticipants: 0, startDate: '2026-08-24', deadline: '2026-08-28', timeRange: '17:00–18:00', postedAt: '2026-08-12T11:30:00.000Z',
    location: 'ลานกิจกรรมกลางแจ้ง', locationMode: 'on-campus', participationMode: 'team', candidateMode: 'NO_CANDIDATE', creator: { name: 'Nan B.', faculty: 'Education' }, studentInterestMatch: false, ownerStudentId: 'student-creator-20',
  },
];
