import type { SupportedLocale } from "@/locales/LocaleProvider";
import type { QuestBoardQuest } from "./types";

const questImageByTag: Record<string, string> = {
  moving:
    "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=960&q=85",
  cleaning:
    "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=960&q=85",
  printing:
    "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=960&q=85",
  delivery:
    "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=960&q=85",
  exercise:
    "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=960&q=85",
};

export const QUEST_TAG_TRANSLATIONS: Record<
  string,
  Record<SupportedLocale, string>
> = {
  moving: { en: "moving", th: "ยกของ" },
  cleaning: { en: "cleaning", th: "ทำความสะอาด" },
  printing: { en: "printing", th: "ถ่ายเอกสาร" },
  delivery: { en: "delivery", th: "ส่งของ" },
  exercise: { en: "exercise", th: "ออกกำลังกาย" },
  "campus-life": { en: "campus-life", th: "ชีวิตในมหาวิทยาลัย" },
};

export function getLocalizedTag(tag: string, locale: SupportedLocale): string {
  if (locale !== "th") return tag;
  return QUEST_TAG_TRANSLATIONS[tag]?.[locale] ?? tag;
}

export type QuestTranslation = {
  title: string;
  tags?: string[];
  description: string;
  completionCriteria: string;
  location: string;
  creatorName: string;
  creatorFaculty?: string;
};

export interface LocalizedQuest extends QuestBoardQuest {
  title: string;
  tags: string[];
  description: string;
  completionCriteria: string;
  location: string;
  creator: QuestBoardQuest["creator"];
}

export interface QuestFixtureDefinition extends QuestBoardQuest {
  translations?: Partial<Record<SupportedLocale, QuestTranslation>>;
}

export const questFixtureDefinitions: QuestFixtureDefinition[] = [
  {
    id: "move-boxes",
    title: "Help move boxes to the dorm",
    tags: ["moving"],
    description: "Help carry labelled boxes from the parking area to Dorm 13.",
    completionCriteria: "All boxes are delivered safely to the assigned room.",
    proofRequired: "optional",
    rewardPerPerson: 300,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-14",
    deadline: "2026-08-16",
    timeRange: "17:00–19:00",
    postedAt: "2026-08-13T15:00:00.000Z",
    location: "หอพัก 13",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "CANDIDATE",
    creator: { name: "Nicha S.", faculty: "Architecture" },
    imageUris: [
      "https://placehold.co/800x500/E2EEE4/014925/png?text=Boxes+1",
      "https://placehold.co/800x500/E2EEE4/014925/png?text=Boxes+2",
      "https://placehold.co/800x500/E2EEE4/014925/png?text=Boxes+3",
    ],
    studentInterestMatch: true,
    ownerStudentId: "student-creator-1",
    translations: {
      th: {
        title: "ช่วยยกกล่องไปหอพัก",
        tags: ["ยกของ"],
        description: "ช่วยขนกล่องที่ติดป้ายจากลานจอดรถไปยังหอพัก 13",
        completionCriteria: "ส่งกล่องทั้งหมดถึงห้องที่กำหนดอย่างปลอดภัย",
        location: "หอพัก 13",
        creatorName: "นิชา ส.",
        creatorFaculty: "สถาปัตยกรรมศาสตร์",
      },
    },
  },
  {
    id: "clean-fan",
    title: "Clean a dorm fan",
    tags: ["cleaning"],
    description: "Clean a shared fan under Dorm 13 before the evening.",
    completionCriteria: "The fan is clean and working after the visit.",
    proofRequired: "optional",
    rewardPerPerson: 150,
    headcount: 2,
    acceptedParticipants: 0,
    startDate: "2026-08-13",
    deadline: "2026-08-18",
    timeRange: "09:00–12:00",
    postedAt: "2026-08-13T14:00:00.000Z",
    location: "ใต้หอพัก 13",
    locationMode: "on-campus",
    participationMode: "team",
    candidateMode: "NO_CANDIDATE",
    creator: { name: "Ploy K.", faculty: "Engineering" },
    studentInterestMatch: false,
    ownerStudentId: "student-creator-2",
    translations: {
      th: {
        title: "ล้างพัดลมหอพัก",
        tags: ["ทำความสะอาด"],
        description: "ทำความสะอาดพัดลมส่วนกลางใต้หอพัก 13 ก่อนช่วงเย็น",
        completionCriteria: "พัดลมสะอาดและใช้งานได้หลังทำงานเสร็จ",
        location: "ใต้หอพัก 13",
        creatorName: "พลอย เค.",
        creatorFaculty: "วิศวกรรมศาสตร์",
      },
    },
  },
  {
    id: "print-documents",
    title: "Photocopy course documents",
    tags: ["printing"],
    description:
      "Photocopy course documents and deliver them to the requester.",
    completionCriteria: "Clear copies are delivered in the requested quantity.",
    proofRequired: "optional",
    rewardPerPerson: 80,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-15",
    deadline: "2026-08-21",
    timeRange: "12:00–13:00",
    postedAt: "2026-08-13T13:00:00.000Z",
    location: "ร้านถ่ายเอกสารใกล้หอพัก 13",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "NO_CANDIDATE",
    creator: { name: "Mild P.", faculty: "Science" },
    studentInterestMatch: true,
    ownerStudentId: "student-creator-3",
    translations: {
      th: {
        title: "ถ่ายเอกสารประกอบการเรียน",
        tags: ["ถ่ายเอกสาร"],
        description: "ถ่ายเอกสารประกอบการเรียนและนำส่งให้ผู้ว่าจ้าง",
        completionCriteria: "ส่งสำเนาเอกสารที่คมชัดครบตามจำนวนที่ต้องการ",
        location: "ร้านถ่ายเอกสารใกล้หอพัก 13",
        creatorName: "มายด์ พ.",
        creatorFaculty: "วิทยาศาสตร์",
      },
    },
  },
  {
    id: "buy-lunch",
    title: "Buy lunch from the canteen",
    tags: ["delivery"],
    description: "Buy a meal from the canteen and bring it to the requester.",
    completionCriteria: "The requested meal is delivered complete and on time.",
    proofRequired: "none",
    rewardPerPerson: 100,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-13",
    deadline: "2026-08-20",
    timeRange: "10:00–13:00",
    postedAt: "2026-08-13T12:00:00.000Z",
    location: "โรงอาหารกลาง",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "CANDIDATE",
    creator: { name: "Beam T.", faculty: "Education" },
    studentInterestMatch: false,
    ownerStudentId: "student-creator-4",
    translations: {
      th: {
        title: "ซื้อข้าวจากโรงอาหาร",
        tags: ["ส่งของ"],
        description: "ซื้ออาหารจากโรงอาหารและนำไปส่งให้ผู้ว่าจ้าง",
        completionCriteria: "ส่งอาหารที่สั่งครบและตรงเวลา",
        location: "โรงอาหารกลาง",
        creatorName: "บีม ที.",
        creatorFaculty: "ศึกษาศาสตร์",
      },
    },
  },
  {
    id: "run-together",
    title: "Go running together",
    tags: ["exercise"],
    description: "Join a relaxed evening run around campus.",
    completionCriteria: "Complete the agreed route together.",
    proofRequired: "none",
    rewardPerPerson: 120,
    headcount: 3,
    acceptedParticipants: 1,
    startDate: "2026-08-17",
    deadline: "2026-08-26",
    timeRange: "18:00–19:00",
    postedAt: "2026-08-13T11:00:00.000Z",
    location: "สนามอินทรีจันทรสถิตย์",
    locationMode: "on-campus",
    participationMode: "team",
    candidateMode: "CANDIDATE",
    creator: { name: "Fern L.", faculty: "Engineering" },
    studentInterestMatch: false,
    ownerStudentId: "student-creator-5",
    translations: {
      th: {
        title: "ไปวิ่งเป็นเพื่อน",
        tags: ["ออกกำลังกาย"],
        description: "วิ่งรอบมหาวิทยาลัยด้วยกันในช่วงเย็นแบบสบาย ๆ",
        completionCriteria: "วิ่งครบเส้นทางที่ตกลงกันด้วยกัน",
        location: "สนามอินทรีจันทรสถิตย์",
        creatorName: "เฟิร์น ล.",
        creatorFaculty: "วิศวกรรมศาสตร์",
      },
    },
  },
  {
    id: "move-water-packs",
    title: "Carry water packs to the dorm",
    tags: ["moving"],
    description: "Help carry bottled water from the shop to Dorm 12.",
    completionCriteria: "All water packs reach the dorm room.",
    proofRequired: "optional",
    rewardPerPerson: 100,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-15",
    deadline: "2026-08-17",
    timeRange: "15:00–16:00",
    postedAt: "2026-08-12T08:00:00.000Z",
    location: "หอพัก 12",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "NO_CANDIDATE",
    creator: { name: "Aom R.", faculty: "Humanities" },
    studentInterestMatch: true,
    ownerStudentId: "student-creator-6",
    translations: {
      th: {
        title: "ช่วยยกแพ็กน้ำไปหอพัก",
        tags: ["ยกของ"],
        description: "ช่วยยกน้ำดื่มบรรจุขวดจากร้านค้าไปยังหอพัก 12",
        completionCriteria: "ส่งแพ็กน้ำทั้งหมดถึงห้องพัก",
        location: "หอพัก 12",
        creatorName: "อ้อม ร.",
        creatorFaculty: "มนุษยศาสตร์",
      },
    },
  },
  {
    id: "move-club-equipment",
    title: "Move club equipment",
    tags: ["moving"],
    description:
      "Move event equipment from the storage room to the activity hall.",
    completionCriteria: "All listed equipment is set up in the hall.",
    proofRequired: "required",
    rewardPerPerson: 250,
    headcount: 3,
    acceptedParticipants: 0,
    startDate: "2026-08-18",
    deadline: "2026-08-20",
    timeRange: "13:00–16:00",
    postedAt: "2026-08-12T08:15:00.000Z",
    location: "อาคารกิจกรรมนิสิต",
    locationMode: "on-campus",
    participationMode: "team",
    candidateMode: "CANDIDATE",
    creator: { name: "Non P.", faculty: "Student Affairs" },
    studentInterestMatch: false,
    ownerStudentId: "student-creator-7",
    translations: {
      th: {
        title: "ช่วยย้ายอุปกรณ์ชมรม",
        tags: ["ยกของ"],
        description:
          "ย้ายอุปกรณ์สำหรับกิจกรรมจากห้องเก็บของไปยังห้องจัดกิจกรรม",
        completionCriteria: "ติดตั้งอุปกรณ์ตามรายการทั้งหมดในห้องจัดกิจกรรม",
        location: "อาคารกิจกรรมนิสิต",
        creatorName: "นนท์ พ.",
        creatorFaculty: "กิจการนิสิต",
      },
    },
  },
  {
    id: "clean-study-table",
    title: "Clean a study table",
    tags: ["cleaning"],
    description: "Wipe and organise a shared study table in the library.",
    completionCriteria: "The table is clean and ready to use.",
    proofRequired: "none",
    rewardPerPerson: 60,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-14",
    deadline: "2026-08-16",
    timeRange: "10:00–11:00",
    postedAt: "2026-08-12T08:30:00.000Z",
    location: "สำนักหอสมุด",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "NO_CANDIDATE",
    creator: { name: "Pim C.", faculty: "Engineering" },
    studentInterestMatch: false,
    ownerStudentId: "student-creator-8",
    translations: {
      th: {
        title: "ทำความสะอาดโต๊ะอ่านหนังสือ",
        tags: ["ทำความสะอาด"],
        description: "เช็ดและจัดระเบียบโต๊ะอ่านหนังสือส่วนกลางในห้องสมุด",
        completionCriteria: "โต๊ะสะอาดและพร้อมใช้งาน",
        location: "สำนักหอสมุด",
        creatorName: "พิม ซี.",
        creatorFaculty: "วิศวกรรมศาสตร์",
      },
    },
  },
  {
    id: "clean-bike",
    title: "Clean a bicycle",
    tags: ["cleaning"],
    description: "Wash a bicycle and wipe it dry near the dorm.",
    completionCriteria: "The bicycle is clean and dry.",
    proofRequired: "optional",
    rewardPerPerson: 120,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-16",
    deadline: "2026-08-19",
    timeRange: "16:00–17:00",
    postedAt: "2026-08-12T08:45:00.000Z",
    location: "ลานจอดจักรยานหอพัก 13",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "CANDIDATE",
    creator: { name: "Fah W.", faculty: "Agriculture" },
    studentInterestMatch: true,
    ownerStudentId: "student-creator-9",
    translations: {
      th: {
        title: "ล้างจักรยาน",
        tags: ["ทำความสะอาด"],
        description: "ล้างจักรยานและเช็ดให้แห้งบริเวณใกล้หอพัก",
        completionCriteria: "จักรยานสะอาดและแห้ง",
        location: "ลานจอดจักรยานหอพัก 13",
        creatorName: "ฟ้า ว.",
        creatorFaculty: "เกษตรศาสตร์",
      },
    },
  },
  {
    id: "print-presentation",
    title: "Print presentation slides",
    tags: ["printing"],
    description: "Print a set of presentation slides before class.",
    completionCriteria:
      "The printed slides are delivered without missing pages.",
    proofRequired: "optional",
    rewardPerPerson: 70,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-14",
    deadline: "2026-08-15",
    timeRange: "08:00–09:00",
    postedAt: "2026-08-12T09:00:00.000Z",
    location: "ร้านถ่ายเอกสารคณะวิศวกรรมศาสตร์",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "NO_CANDIDATE",
    creator: { name: "Mew J.", faculty: "Engineering" },
    studentInterestMatch: false,
    ownerStudentId: "student-creator-10",
    translations: {
      th: {
        title: "พิมพ์สไลด์นำเสนอ",
        tags: ["ถ่ายเอกสาร"],
        description: "พิมพ์ชุดสไลด์นำเสนอก่อนเข้าเรียน",
        completionCriteria: "ส่งสไลด์ที่พิมพ์ครบทุกหน้า",
        location: "ร้านถ่ายเอกสารคณะวิศวกรรมศาสตร์",
        creatorName: "หมิว จ.",
        creatorFaculty: "วิศวกรรมศาสตร์",
      },
    },
  },
  {
    id: "print-event-posters",
    title: "Print event posters",
    tags: ["printing"],
    description: "Print and collect posters for a faculty event.",
    completionCriteria: "Ten clear posters are delivered to the organiser.",
    proofRequired: "required",
    rewardPerPerson: 180,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-17",
    deadline: "2026-08-21",
    timeRange: "11:00–12:00",
    postedAt: "2026-08-12T09:15:00.000Z",
    location: "ร้านถ่ายเอกสารหน้า มก.",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "CANDIDATE",
    creator: { name: "Ton K.", faculty: "Science" },
    studentInterestMatch: true,
    ownerStudentId: "student-creator-11",
    translations: {
      th: {
        title: "พิมพ์โปสเตอร์งานกิจกรรม",
        tags: ["ถ่ายเอกสาร"],
        description: "พิมพ์และรับโปสเตอร์สำหรับงานกิจกรรมของคณะ",
        completionCriteria: "ส่งโปสเตอร์ที่คมชัด 10 แผ่นให้ผู้จัดงาน",
        location: "ร้านถ่ายเอกสารหน้า มก.",
        creatorName: "ต้น เค.",
        creatorFaculty: "วิทยาศาสตร์",
      },
    },
  },
  {
    id: "deliver-snacks",
    title: "Deliver snacks to a study group",
    tags: ["delivery"],
    description:
      "Pick up snacks from the convenience store and deliver them to a study group.",
    completionCriteria: "All requested snacks are delivered.",
    proofRequired: "none",
    rewardPerPerson: 90,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-15",
    deadline: "2026-08-18",
    timeRange: "14:00–15:00",
    postedAt: "2026-08-12T09:30:00.000Z",
    location: "สำนักหอสมุด",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "NO_CANDIDATE",
    creator: { name: "Ploy N.", faculty: "Humanities" },
    studentInterestMatch: false,
    ownerStudentId: "student-creator-12",
    translations: {
      th: {
        title: "ส่งขนมให้กลุ่มอ่านหนังสือ",
        tags: ["ส่งของ"],
        description: "รับขนมจากร้านสะดวกซื้อและนำไปส่งให้กลุ่มอ่านหนังสือ",
        completionCriteria: "ส่งขนมที่สั่งครบทั้งหมด",
        location: "สำนักหอสมุด",
        creatorName: "พลอย น.",
        creatorFaculty: "มนุษยศาสตร์",
      },
    },
  },
  {
    id: "deliver-parcel",
    title: "Deliver a parcel to the dorm",
    tags: ["delivery"],
    description:
      "Collect a parcel at the campus post point and bring it to Dorm 11.",
    completionCriteria: "The parcel is delivered to the requester.",
    proofRequired: "optional",
    rewardPerPerson: 110,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-18",
    deadline: "2026-08-22",
    timeRange: "13:00–14:00",
    postedAt: "2026-08-12T09:45:00.000Z",
    location: "หอพัก 11",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "CANDIDATE",
    creator: { name: "Beam T.", faculty: "Education" },
    studentInterestMatch: true,
    ownerStudentId: "student-creator-13",
    translations: {
      th: {
        title: "ส่งพัสดุไปหอพัก",
        tags: ["ส่งของ"],
        description: "รับพัสดุที่จุดไปรษณีย์ในมหาวิทยาลัยและนำไปส่งที่หอพัก 11",
        completionCriteria: "ส่งพัสดุถึงผู้ว่าจ้าง",
        location: "หอพัก 11",
        creatorName: "บีม ที.",
        creatorFaculty: "ศึกษาศาสตร์",
      },
    },
  },
  {
    id: "walk-together",
    title: "Go for a walk together",
    tags: ["exercise"],
    description: "Take a relaxed walk around campus before sunset.",
    completionCriteria: "Complete the planned walking route together.",
    proofRequired: "none",
    rewardPerPerson: 50,
    headcount: 2,
    acceptedParticipants: 0,
    startDate: "2026-08-16",
    deadline: "2026-08-20",
    timeRange: "17:00–18:00",
    postedAt: "2026-08-12T10:00:00.000Z",
    location: "สวนวชิรเบญจทัศ",
    locationMode: "on-campus",
    participationMode: "team",
    candidateMode: "NO_CANDIDATE",
    creator: { name: "Mint S.", faculty: "Economics" },
    studentInterestMatch: false,
    ownerStudentId: "student-creator-14",
    translations: {
      th: {
        title: "ไปเดินเล่นเป็นเพื่อน",
        tags: ["ออกกำลังกาย"],
        description: "เดินเล่นรอบมหาวิทยาลัยแบบสบาย ๆ ก่อนพระอาทิตย์ตก",
        completionCriteria: "เดินครบเส้นทางที่วางแผนไว้ด้วยกัน",
        location: "สวนวชิรเบญจทัศ",
        creatorName: "มิ้นท์ ส.",
        creatorFaculty: "เศรษฐศาสตร์",
      },
    },
  },
  {
    id: "play-badminton",
    title: "Play badminton together",
    tags: ["exercise"],
    description: "Join a friendly badminton session after class.",
    completionCriteria: "Attend and play for the agreed session.",
    proofRequired: "none",
    rewardPerPerson: 80,
    headcount: 3,
    acceptedParticipants: 0,
    startDate: "2026-08-19",
    deadline: "2026-08-23",
    timeRange: "18:00–20:00",
    postedAt: "2026-08-12T10:15:00.000Z",
    location: "สนามแบดมินตัน มก.",
    locationMode: "on-campus",
    participationMode: "team",
    candidateMode: "CANDIDATE",
    creator: { name: "Karn P.", faculty: "Sports Science" },
    studentInterestMatch: true,
    ownerStudentId: "student-creator-15",
    translations: {
      th: {
        title: "เล่นแบดมินตันด้วยกัน",
        tags: ["ออกกำลังกาย"],
        description: "ร่วมเล่นแบดมินตันแบบเป็นกันเองหลังเลิกเรียน",
        completionCriteria: "เข้าร่วมและเล่นครบตามเวลาที่ตกลงกัน",
        location: "สนามแบดมินตัน มก.",
        creatorName: "กานต์ พ.",
        creatorFaculty: "วิทยาศาสตร์การกีฬา",
      },
    },
  },
  {
    id: "move-plants",
    title: "Move plants to a new room",
    tags: ["moving"],
    description: "Help move potted plants into a new dorm room.",
    completionCriteria: "All plants arrive without damage.",
    proofRequired: "optional",
    rewardPerPerson: 100,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-20",
    deadline: "2026-08-24",
    timeRange: "09:00–10:00",
    postedAt: "2026-08-12T10:30:00.000Z",
    location: "หอพัก 9",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "NO_CANDIDATE",
    creator: { name: "Dao L.", faculty: "Forestry" },
    studentInterestMatch: false,
    ownerStudentId: "student-creator-16",
    translations: {
      th: {
        title: "ช่วยย้ายต้นไม้ไปห้องใหม่",
        tags: ["ยกของ"],
        description: "ช่วยย้ายต้นไม้กระถางไปยังห้องพักใหม่",
        completionCriteria: "ต้นไม้ทั้งหมดถึงที่หมายโดยไม่เสียหาย",
        location: "หอพัก 9",
        creatorName: "ดาว ล.",
        creatorFaculty: "วนศาสตร์",
      },
    },
  },
  {
    id: "clean-fridge",
    title: "Clean a dorm fridge",
    tags: ["cleaning"],
    description: "Clean the inside of a small refrigerator in a dorm room.",
    completionCriteria: "The refrigerator is clean and dry.",
    proofRequired: "optional",
    rewardPerPerson: 140,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-21",
    deadline: "2026-08-25",
    timeRange: "14:00–15:00",
    postedAt: "2026-08-12T10:45:00.000Z",
    location: "หอพัก 10",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "CANDIDATE",
    creator: { name: "Game T.", faculty: "Veterinary Medicine" },
    studentInterestMatch: true,
    ownerStudentId: "student-creator-17",
    translations: {
      th: {
        title: "ทำความสะอาดตู้เย็นหอพัก",
        tags: ["ทำความสะอาด"],
        description: "ทำความสะอาดภายในตู้เย็นขนาดเล็กในห้องพัก",
        completionCriteria: "ตู้เย็นสะอาดและแห้ง",
        location: "หอพัก 10",
        creatorName: "เกม ที.",
        creatorFaculty: "สัตวแพทยศาสตร์",
      },
    },
  },
  {
    id: "print-notes",
    title: "Print lecture notes",
    tags: ["printing"],
    description: "Print lecture notes for an afternoon class.",
    completionCriteria: "The complete notes are handed over before class.",
    proofRequired: "none",
    rewardPerPerson: 60,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-22",
    deadline: "2026-08-26",
    timeRange: "10:00–11:00",
    postedAt: "2026-08-12T11:00:00.000Z",
    location: "คณะวิทยาศาสตร์",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "NO_CANDIDATE",
    creator: { name: "May K.", faculty: "Science" },
    studentInterestMatch: false,
    ownerStudentId: "student-creator-18",
    translations: {
      th: {
        title: "พิมพ์โน้ตการเรียน",
        tags: ["ถ่ายเอกสาร"],
        description: "พิมพ์โน้ตการเรียนสำหรับคลาสช่วงบ่าย",
        completionCriteria: "ส่งโน้ตครบถ้วนก่อนเริ่มเรียน",
        location: "คณะวิทยาศาสตร์",
        creatorName: "เมย์ เค.",
        creatorFaculty: "วิทยาศาสตร์",
      },
    },
  },
  {
    id: "deliver-drinks",
    title: "Deliver drinks to the library",
    tags: ["delivery"],
    description:
      "Buy drinks and bring them to a group studying at the library.",
    completionCriteria: "All drinks are delivered to the correct table.",
    proofRequired: "none",
    rewardPerPerson: 80,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-23",
    deadline: "2026-08-27",
    timeRange: "15:00–16:00",
    postedAt: "2026-08-12T11:15:00.000Z",
    location: "สำนักหอสมุด",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "CANDIDATE",
    creator: { name: "Ice N.", faculty: "Business Administration" },
    studentInterestMatch: true,
    ownerStudentId: "student-creator-19",
    translations: {
      th: {
        title: "ส่งเครื่องดื่มไปห้องสมุด",
        tags: ["ส่งของ"],
        description:
          "ซื้อเครื่องดื่มและนำไปส่งให้กลุ่มที่อ่านหนังสือในห้องสมุด",
        completionCriteria: "ส่งเครื่องดื่มทั้งหมดถึงโต๊ะที่ถูกต้อง",
        location: "สำนักหอสมุด",
        creatorName: "ไอซ์ น.",
        creatorFaculty: "บริหารธุรกิจ",
      },
    },
  },
  {
    id: "stretch-together",
    title: "Stretch together after class",
    tags: ["exercise"],
    description: "Do a short guided stretching session after class.",
    completionCriteria: "Complete the full stretching session together.",
    proofRequired: "none",
    rewardPerPerson: 50,
    headcount: 4,
    acceptedParticipants: 0,
    startDate: "2026-08-24",
    deadline: "2026-08-28",
    timeRange: "17:00–18:00",
    postedAt: "2026-08-12T11:30:00.000Z",
    location: "ลานกิจกรรมกลางแจ้ง",
    locationMode: "on-campus",
    participationMode: "team",
    candidateMode: "NO_CANDIDATE",
    creator: { name: "Nan B.", faculty: "Education" },
    studentInterestMatch: false,
    ownerStudentId: "student-creator-20",
    translations: {
      th: {
        title: "ยืดเหยียดร่างกายด้วยกันหลังเลิกเรียน",
        tags: ["ออกกำลังกาย"],
        description: "ทำกิจกรรมยืดเหยียดร่างกายสั้น ๆ หลังเลิกเรียน",
        completionCriteria: "ทำกิจกรรมยืดเหยียดครบทั้งช่วงด้วยกัน",
        location: "ลานกิจกรรมกลางแจ้ง",
        creatorName: "แนน บ.",
        creatorFaculty: "ศึกษาศาสตร์",
      },
    },
  },
  // Route/test-only scenario data. The adapter seeds these records, while normal discovery filters them out.
  {
    id: "team-forming-demo",
    title: "Form a campus event team",
    tags: ["campus-life"],
    description: "Join a small team to support a campus event.",
    completionCriteria: "The event support checklist is complete.",
    proofRequired: "optional",
    rewardPerPerson: 200,
    rewardSatang: 20000,
    headcount: 3,
    acceptedParticipants: 0,
    startDate: "2026-08-20",
    deadline: "2026-08-21",
    timeRange: "10:00–12:00",
    postedAt: "2026-08-12T09:00:00.000Z",
    location: "Student activity building",
    locationMode: "on-campus",
    participationMode: "team",
    candidateMode: "CANDIDATE",
    creator: { name: "Demo Hirer" },
    studentInterestMatch: false,
    ownerStudentId: "demo-hirer",
    prototypeOnly: true,
    prototypeScenario: "team-forming-demo",
    translations: {
      th: {
        title: "รวมทีมกิจกรรมในมหาวิทยาลัย",
        tags: ["ชีวิตในมหาวิทยาลัย"],
        description: "เข้าร่วมทีมเล็ก ๆ เพื่อช่วยงานกิจกรรมในมหาวิทยาลัย",
        completionCriteria: "ทำรายการตรวจสอบงานกิจกรรมให้ครบถ้วน",
        location: "อาคารกิจกรรมนิสิต",
        creatorName: "ผู้ว่าจ้างตัวอย่าง",
      },
    },
  },
  {
    id: "team-selection-demo",
    title: "Choose a campus event team",
    tags: ["campus-life"],
    description:
      "The Hirer reviews independent team proposals for a campus event.",
    completionCriteria: "The event support checklist is complete.",
    proofRequired: "optional",
    rewardPerPerson: 200,
    rewardSatang: 20000,
    headcount: 3,
    acceptedParticipants: 0,
    startDate: "2026-08-22",
    deadline: "2026-08-23",
    timeRange: "10:00–12:00",
    postedAt: "2026-08-12T09:05:00.000Z",
    location: "Student activity building",
    locationMode: "on-campus",
    participationMode: "team",
    candidateMode: "CANDIDATE",
    creator: { name: "Demo Hirer" },
    studentInterestMatch: false,
    ownerStudentId: "demo-hirer",
    prototypeOnly: true,
    prototypeScenario: "team-selection-demo",
    translations: {
      th: {
        title: "เลือกทีมกิจกรรมในมหาวิทยาลัย",
        tags: ["ชีวิตในมหาวิทยาลัย"],
        description: "ผู้ว่าจ้างตรวจสอบข้อเสนอจากหลายทีมสำหรับงานกิจกรรม",
        completionCriteria: "ทำรายการตรวจสอบงานกิจกรรมให้ครบถ้วน",
        location: "อาคารกิจกรรมนิสิต",
        creatorName: "ผู้ว่าจ้างตัวอย่าง",
      },
    },
  },
  {
    id: "single-candidate-demo",
    title: "Select a campus helper",
    tags: ["campus-life"],
    description:
      "Review several individual proposals for a campus helper Quest.",
    completionCriteria: "The campus helper checklist is complete.",
    proofRequired: "optional",
    rewardPerPerson: 250,
    rewardSatang: 25000,
    headcount: 1,
    acceptedParticipants: 0,
    startDate: "2026-08-24",
    deadline: "2026-08-25",
    timeRange: "10:00–12:00",
    postedAt: "2026-08-12T09:10:00.000Z",
    location: "Student activity building",
    locationMode: "on-campus",
    participationMode: "single",
    candidateMode: "CANDIDATE",
    creator: { name: "Demo Hirer" },
    studentInterestMatch: false,
    ownerStudentId: "demo-hirer",
    prototypeOnly: true,
    prototypeScenario: "single-candidate-demo",
    translations: {
      th: {
        title: "เลือกผู้ช่วยในมหาวิทยาลัย",
        tags: ["ชีวิตในมหาวิทยาลัย"],
        description: "ตรวจสอบข้อเสนอจากผู้สมัครหลายคนสำหรับงานผู้ช่วย",
        completionCriteria: "ทำรายการตรวจสอบงานผู้ช่วยให้ครบถ้วน",
        location: "อาคารกิจกรรมนิสิต",
        creatorName: "ผู้ว่าจ้างตัวอย่าง",
      },
    },
  },
  {
    id: "partial-group-start-demo",
    title: "Start a partial campus crew",
    tags: ["campus-life"],
    description:
      "A direct Group Quest demonstrating the partial-start consent gate.",
    completionCriteria: "The campus support checklist is complete.",
    proofRequired: "none",
    rewardPerPerson: 180,
    rewardSatang: 18000,
    headcount: 3,
    acceptedParticipants: 2,
    startDate: "2026-08-26",
    deadline: "2026-08-27",
    timeRange: "10:00–12:00",
    postedAt: "2026-08-12T09:15:00.000Z",
    location: "Student activity building",
    locationMode: "on-campus",
    participationMode: "team",
    candidateMode: "NO_CANDIDATE",
    creator: { name: "Demo Hirer" },
    studentInterestMatch: false,
    ownerStudentId: "demo-hirer",
    prototypeOnly: true,
    prototypeScenario: "partial-group-start-demo",
    translations: {
      th: {
        title: "เริ่มทีมมหาวิทยาลัยแบบไม่เต็มจำนวน",
        tags: ["ชีวิตในมหาวิทยาลัย"],
        description:
          "ตัวอย่างเควสต์กลุ่มแบบมาก่อนได้ก่อนที่ใช้การยินยอมก่อนเริ่ม",
        completionCriteria: "ทำรายการตรวจสอบงานช่วยกิจกรรมให้ครบถ้วน",
        location: "อาคารกิจกรรมนิสิต",
        creatorName: "ผู้ว่าจ้างตัวอย่าง",
      },
    },
  },
];

export const questFixtures: QuestBoardQuest[] = questFixtureDefinitions.map(
  (quest) => {
    const imageUri = questImageByTag[quest.tags[0] ?? ""];
    return quest.imageUris?.length || !imageUri
      ? quest
      : { ...quest, imageUris: [imageUri] };
  }
);

export function getLocalizedQuest(
  quest: QuestBoardQuest,
  locale: SupportedLocale
): LocalizedQuest {
  if (locale !== "th") return quest;
  const fixture = questFixtureDefinitions.find((item) => item.id === quest.id);
  const translation = fixture?.translations?.[locale];
  if (!translation) return quest;

  const localizedTags =
    translation.tags ?? quest.tags.map((tag) => getLocalizedTag(tag, locale));
  return {
    ...quest,
    title: translation.title,
    tags: localizedTags,
    description: translation.description,
    completionCriteria: translation.completionCriteria,
    location: translation.location,
    creator: {
      ...quest.creator,
      name: translation.creatorName,
      faculty: translation.creatorFaculty ?? quest.creator.faculty,
    },
  };
}
