/* Hallmark · pre-emit critique: P4 H5 E4 S4 R5 V4
 * Hallmark · component: filter sheet · genre: editorial · theme: existing KUQuest soft-green tokens
 * states: default · pressed · focus/accessibility state · disabled-compatible · loading-compatible · error-compatible · success-compatible
 * contrast: pass (existing project tokens)
 */
import { StyleSheet } from 'react-native';

import { colors } from '@/theme/colors';
import { spacing } from '@/theme/spacing';
import { fontFamily } from '@/theme/typography';

const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: colors.background,
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 140,
    paddingHorizontal: spacing.lg,
  },
  searchField: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 56,
    paddingHorizontal: spacing.md,
  },
  searchInput: {
    color: colors.textStrong,
    flex: 1,
    fontFamily: fontFamily.regular,
    fontSize: 16,
    minHeight: 54,
    paddingHorizontal: spacing.sm,
  },
  iconButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  toolbar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.md,
  },
  toolbarButton: {
    alignItems: 'center',
    borderRadius: 999,
    flexDirection: 'row',
    minHeight: 44,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  toolbarButtonActive: {
    backgroundColor: colors.surfaceAccent,
  },
  toolbarButtonPressed: {
    backgroundColor: colors.surfaceMuted,
  },
  toolbarButtonRight: {
    justifyContent: 'flex-end',
  },
  toolbarText: {
    color: colors.textStrong,
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
    marginLeft: spacing.xs,
  },
  toolbarTextActive: {
    color: colors.primary,
  },
  filterCount: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 999,
    height: 20,
    justifyContent: 'center',
    marginLeft: spacing.xs,
    minWidth: 20,
    paddingHorizontal: 5,
  },
  filterCountText: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: 11,
    lineHeight: 14,
  },
  activeFilters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  filterChip: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAccent,
    borderColor: colors.borderAccent,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 32,
    paddingHorizontal: spacing.sm,
  },
  filterChipText: {
    color: colors.primary,
    fontFamily: fontFamily.medium,
    fontSize: 12,
  },
  cards: {
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  card: {
    backgroundColor: colors.white,
    borderColor: colors.borderSubtle,
    borderRadius: 16,
    borderWidth: 1,
    padding: spacing.md,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 5,
    elevation: 2,
  },
  cardBody: {
    borderRadius: 10,
  },
  cardTopRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardTitle: {
    color: colors.textStrong,
    flex: 1,
    fontFamily: fontFamily.semiBold,
    fontSize: 17,
    lineHeight: 22,
    marginRight: spacing.sm,
  },
  categoryRow: {
    marginTop: spacing.sm,
  },
  categoryTag: {
    alignSelf: 'flex-start',
    backgroundColor: colors.surfaceMuted,
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
  },
  categoryTagText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.medium,
    fontSize: 11,
  },
  creatorRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: spacing.sm,
    minHeight: 28,
  },
  creatorAvatar: {
    backgroundColor: colors.surfaceAccent,
    borderRadius: 14,
    height: 28,
    width: 28,
  },
  creatorAvatarFallback: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAccent,
    borderColor: colors.borderAccent,
    borderRadius: 14,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  creatorAvatarText: {
    color: colors.primary,
    fontFamily: fontFamily.bold,
    fontSize: 10,
  },
  creatorText: {
    color: colors.textSecondary,
    flex: 1,
    fontFamily: fontFamily.medium,
    fontSize: 11,
    marginLeft: spacing.sm,
  },
  creatorLabel: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
  },
  reward: {
    color: colors.primary,
    fontFamily: fontFamily.bold,
    flexShrink: 0,
    fontSize: 16,
    textAlign: 'right',
  },
  rewardUnit: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 10,
  },
  cardMeta: {
    gap: spacing.xs,
    marginTop: spacing.md,
  },
  metaItem: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    minHeight: 20,
  },
  metaInlineText: {
    flex: 1,
    marginLeft: spacing.xs,
  },
  metaLabel: {
    color: colors.textMuted,
    fontFamily: fontFamily.medium,
    fontSize: 11,
    lineHeight: 16,
  },
  metaValue: {
    color: colors.textSecondary,
    fontFamily: fontFamily.regular,
    fontSize: 12,
    lineHeight: 18,
  },
  metaText: {
    color: colors.textSecondary,
    flex: 1,
    fontFamily: fontFamily.regular,
    fontSize: 12,
    lineHeight: 18,
    marginLeft: spacing.xs,
  },
  endingSoon: {
    color: colors.dangerDark,
    fontFamily: fontFamily.semiBold,
  },
  actionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'flex-end',
    marginTop: spacing.md,
  },
  detailAction: {
    alignItems: 'center',
    borderColor: colors.textMuted,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 66,
    paddingHorizontal: spacing.md,
  },
  detailActionPressed: {
    backgroundColor: colors.surfaceMuted,
  },
  detailActionText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.medium,
    fontSize: 12,
  },
  takeAction: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 999,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: spacing.md,
  },
  takeActionPressed: {
    backgroundColor: colors.primaryDark,
  },
  takeActionText: {
    color: colors.white,
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
  },
  retryStatus: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 12,
    textAlign: 'center',
  },
  state: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 330,
    paddingHorizontal: spacing.lg,
  },
  stateIcon: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAccent,
    borderRadius: 999,
    height: 68,
    justifyContent: 'center',
    marginBottom: spacing.md,
    width: 68,
  },
  stateTitle: {
    color: colors.textStrong,
    fontFamily: fontFamily.semiBold,
    fontSize: 19,
    textAlign: 'center',
  },
  stateDescription: {
    color: colors.textSecondary,
    fontFamily: fontFamily.regular,
    fontSize: 14,
    lineHeight: 21,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  stateAction: {
    backgroundColor: colors.primary,
    borderRadius: 999,
    marginTop: spacing.md,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  stateActionText: {
    color: colors.white,
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
  },
  skeleton: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 16,
    height: 108,
  },
  previewButton: {
    alignSelf: 'flex-end',
    marginTop: spacing.sm,
    minHeight: 34,
  },
  previewButtonText: {
    color: colors.textMuted,
    fontFamily: fontFamily.medium,
    fontSize: 12,
    textDecorationLine: 'underline',
  },
  modalBackdrop: {
    backgroundColor: colors.overlay,
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '88%',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.border,
    borderRadius: 999,
    height: 4,
    marginBottom: spacing.md,
    width: 42,
  },
  sheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
  },
  sheetHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  sheetTitle: {
    color: colors.textStrong,
    fontFamily: fontFamily.bold,
    fontSize: 22,
  },
  sheetSummary: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 12,
    marginTop: 2,
  },
  sheetCloseButton: {
    alignItems: 'center',
    borderRadius: 999,
    height: 44,
    justifyContent: 'center',
    marginLeft: spacing.sm,
    width: 44,
  },
  sheetCloseButtonPressed: {
    backgroundColor: colors.surfaceMuted,
  },
  sheetScrollContent: {
    paddingBottom: spacing.sm,
  },
  sheetSection: {
    marginBottom: spacing.md,
  },
  sheetSectionTitle: {
    color: colors.textSecondary,
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    marginBottom: spacing.xs,
  },
  optionList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  option: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  optionSelected: {
    backgroundColor: colors.surfaceAccent,
    borderColor: colors.primary,
  },
  optionPressed: {
    backgroundColor: colors.surfaceMuted,
  },
  optionText: {
    color: colors.textSecondary,
    fontFamily: fontFamily.medium,
    fontSize: 13,
  },
  optionTextSelected: {
    color: colors.primary,
    fontFamily: fontFamily.semiBold,
  },
  sheetActions: {
    alignItems: 'center',
    borderTopColor: colors.borderSubtle,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
    paddingTop: spacing.md,
  },
  secondaryAction: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
  },
  secondaryActionText: {
    color: colors.textStrong,
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
  },
  primaryAction: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 999,
    flex: 1.4,
    justifyContent: 'center',
    minHeight: 48,
  },
  primaryActionText: {
    color: colors.white,
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
  },
  alertIcon: {
    backgroundColor: colors.surfaceDanger,
  },
});

export default styles;
