const styles = {
  safeArea: 'bg-ku-background flex-1',
  scrollContent: '',
  boardIntro: 'pb-[16px] pt-[8px]',
  boardTitle: 'text-ku-text-strong font-ku-bold text-ku-title',
  boardSubtitle: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[4px]',
  searchField: 'items-center bg-ku-surface border-ku-border-accent rounded-[18px] border flex-row min-h-[56px] px-[16px]',
  searchInput: 'text-ku-text-strong flex-1 font-ku-regular text-ku-body min-h-[54px] px-[8px]',
  iconButton: 'items-center h-[48px] justify-center w-[48px]',
  toolbar: 'items-center flex-row justify-between mt-[16px]',
  toolbarButton: 'items-center rounded-ku-pill flex-row min-h-[48px] px-[8px] py-[4px] active:bg-ku-surface-muted',
  toolbarButtonActive: 'bg-ku-primary',
  toolbarButtonRight: 'justify-end',
  toolbarText: 'text-ku-text-strong font-ku-semibold text-ku-control ml-[4px]',
  toolbarTextActive: 'text-ku-white',
  filterCount: 'items-center bg-ku-primary rounded-ku-pill h-[20px] justify-center ml-[4px] min-w-[20px] px-[5px]',
  filterCountText: 'text-ku-white font-ku-bold text-ku-caption',
  activeFilters: 'flex-row flex-wrap gap-[8px] mt-[4px]',
  filterChip: 'items-center bg-ku-surface-success border-ku-border-success rounded-ku-pill border flex-row min-h-[48px] px-[10px]',
  filterChipText: 'text-ku-success font-ku-medium text-ku-label',
  cards: 'gap-[8px] mt-[16px]',
  cardSeparator: 'h-[8px]',
  card: 'shadow-[0px_2px_5px_rgb(18_32_24_/0.06)] bg-ku-white border-ku-border-accent rounded-[16px] border p-[16px] active:bg-ku-surface-muted',
  cardBody: 'rounded-[10px]',
  cardTopRow: 'items-start flex-row justify-between',
  cardTitleColumn: 'flex-1 min-w-0 mr-[8px]',
  cardTitle: 'text-ku-text-strong font-ku-bold text-ku-subtitle',
  cardCategory: 'items-center bg-ku-surface-accent rounded-ku-pill flex-row self-start min-h-[32px] mt-[8px] px-[8px]',
  cardCategoryText: 'text-ku-primary font-ku-medium text-ku-label ml-[4px]',
  rewardBlock: 'bg-ku-surface-success border-ku-border-success rounded-[14px] border shrink-0 min-w-[88px] px-[10px] py-[8px]',
  rewardAmount: 'text-ku-primary font-ku-bold text-ku-emphasis-large',
  rewardUnit: 'text-ku-text-secondary font-ku-regular text-ku-caption',
  cardDescription: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[12px]',
  cardDivider: 'bg-ku-border-subtle h-[1px] mt-[16px] mb-[12px] w-full',
  infoList: 'gap-[4px]',
  infoRow: 'items-center flex-row min-h-[36px]',
  infoIcon: 'items-center bg-ku-surface-muted rounded-[11px] h-[36px] justify-center shrink-0 w-[36px]',
  infoIconMuted: 'bg-ku-surface-muted',
  infoText: 'text-ku-text-secondary font-ku-regular text-ku-body-small ml-[8px]',
  infoTextPrimary: 'text-ku-text-strong font-ku-medium',
  infoTextFlexible: 'flex-1 min-w-0',
  participantCount: 'items-center bg-ku-surface-accent rounded-[12px] justify-center min-h-[32px] min-w-[48px] ml-[8px] px-[8px]',
  participantCountText: 'text-ku-primary font-ku-medium text-ku-body-small',
  spotsLeftText: 'text-ku-success flex-1 font-ku-medium text-ku-label ml-[8px] text-right',
  locationContent: 'flex-1 min-w-0 ml-[8px]',
  locationText: 'text-ku-text-strong font-ku-regular text-ku-body-small min-w-0',
  cardFooter: 'items-center border-ku-border-subtle border-t flex-row justify-end mt-[12px] pt-[12px]',
  cardAccessibilityMeta: 'absolute h-0 opacity-0 w-0',
  retryStatus: 'text-ku-success font-ku-medium text-ku-meta text-center mt-[8px]',
  state: 'items-center justify-center min-h-[330px] px-[24px]',
  stateIcon: 'items-center bg-ku-surface-accent rounded-ku-pill h-[68px] justify-center mb-[16px] w-[68px]',
  stateTitle: 'text-ku-text-strong font-ku-semibold text-ku-emphasis-large text-center',
  stateDescription: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[4px] text-center',
  stateAction: 'bg-ku-primary rounded-ku-pill mt-[16px] min-h-[48px] justify-center px-[24px]',
  stateActionText: 'text-ku-white font-ku-semibold text-ku-body-small',
  skeleton: 'bg-ku-surface-muted rounded-[16px] h-[156px]',
  modalBackdrop: 'bg-ku-overlay flex-1 justify-end',
  sheet: 'bg-ku-background rounded-tl-[24px] rounded-tr-[24px] max-h-[88%] px-[24px] pt-[8px]',
  sheetScroll: 'flex-1',
  sheetHandle: 'self-center bg-ku-border rounded-ku-pill h-[4px] mb-[16px] w-[42px]',
  sheetHeader: 'items-center flex-row justify-between mb-[24px]',
  sheetHeaderCopy: 'flex-1 min-w-0',
  sheetTitle: 'text-ku-text-strong font-ku-bold text-ku-title-small',
  sheetSummary: 'text-ku-text-muted font-ku-regular text-ku-label mt-[2px]',
  sheetCloseButton: 'items-center rounded-ku-pill h-[48px] justify-center ml-[8px] w-[48px] active:bg-ku-surface-muted',
  sheetScrollContent: 'pb-[8px]',
  sheetSection: 'mb-[16px]',
  sheetSectionTitle: 'text-ku-text-secondary font-ku-semibold text-ku-meta mb-[4px]',
  selectedTags: 'flex-row flex-wrap gap-[4px] mb-[8px]',
  selectedTag: 'items-center bg-ku-surface-success border-ku-border-success rounded-ku-pill border flex-row min-h-[48px] px-[10px]',
  selectedTagText: 'text-ku-success font-ku-medium text-ku-label mr-[4px]',
  tagSearchField: 'items-center bg-ku-white border-ku-border-muted rounded-[8px] border flex-row min-h-[48px] px-[12px]',
  tagSearchInput: 'text-ku-text-strong flex-1 font-ku-regular text-ku-body-small min-h-[46px] px-[8px]',
  tagSuggestions: 'flex-row flex-wrap gap-[4px] mt-[8px]',
  noTagResults: 'text-ku-text-muted font-ku-regular text-ku-body-small mt-[8px]',
  optionList: 'flex-row flex-wrap gap-[4px]',
  option: 'bg-ku-white border-ku-border rounded-ku-pill border min-h-[48px] justify-center px-[16px] active:bg-ku-surface-muted',
  optionSelected: 'bg-ku-surface-accent border-ku-primary',
  optionText: 'text-ku-text-secondary font-ku-medium text-ku-meta',
  optionTextSelected: 'text-ku-primary font-ku-semibold',
  rewardInputs: 'flex-row gap-[8px]',
  rewardField: 'flex-1 gap-[4px]',
  rewardFieldLabel: 'text-ku-text-secondary font-ku-semibold text-ku-label',
  rewardInput: 'bg-ku-white border-ku-border-muted rounded-[8px] border font-ku-regular text-ku-text-strong min-h-[48px] px-[12px]',
  rewardError: 'text-ku-danger font-ku-regular text-ku-label mt-[4px]',
  sheetActions: 'items-center border-t-ku-border-subtle border-t flex-row gap-[8px] mt-[8px] pt-[16px]',
  cancelAction: 'items-center justify-center min-h-[48px] px-[8px]',
  cancelActionText: 'text-ku-text-secondary font-ku-semibold text-ku-meta',
  secondaryAction: 'items-center border-ku-border rounded-ku-pill border flex-[0.9] justify-center min-h-[48px] px-[8px]',
  secondaryActionText: 'text-ku-text-strong font-ku-semibold text-ku-meta',
  primaryAction: 'items-center bg-ku-primary rounded-ku-pill flex-[1.4] justify-center min-h-[48px] px-[8px]',
  primaryActionDisabled: 'opacity-[0.5]',
  primaryActionText: 'text-ku-white font-ku-semibold text-ku-body-small',
  alertIcon: 'bg-ku-surface-danger',
} as const;

export default styles;
