const styles = {
  safeArea: 'bg-ku-background flex-1',
  scrollContent: 'pb-[140px] px-[24px]',
  searchField: 'items-center bg-ku-surface border-ku-border rounded-[18px] border flex-row min-h-[56px] px-[16px]',
  searchInput: 'text-ku-text-strong flex-1 font-ku-regular text-[16px] min-h-[54px] px-[8px]',
  iconButton: 'items-center h-[40px] justify-center w-[40px]',
  toolbar: 'items-center flex-row justify-between mt-[16px]',
  toolbarButton: 'items-center rounded-ku-pill flex-row min-h-[44px] px-[8px] py-[4px] active:bg-ku-surface-muted',
  toolbarButtonActive: 'bg-ku-surface-accent',
  toolbarButtonRight: 'justify-end',
  toolbarText: 'text-ku-text-strong font-ku-semibold text-[16px] ml-[4px]',
  toolbarTextActive: 'text-ku-primary',
  filterCount: 'items-center bg-ku-primary rounded-ku-pill h-[20px] justify-center ml-[4px] min-w-[20px] px-[5px]',
  filterCountText: 'text-ku-white font-ku-bold text-[11px] leading-[14px]',
  activeFilters: 'flex-row flex-wrap gap-[4px] mt-[4px]',
  filterChip: 'items-center bg-ku-surface-accent border-ku-border-accent rounded-ku-pill border flex-row min-h-[32px] px-[8px]',
  filterChipText: 'text-ku-primary font-ku-medium text-[12px]',
  cards: 'gap-[8px] mt-[16px]',
  card: 'shadow-[0px_2px_5px_rgb(18_32_24_/0.06)] bg-ku-white border-ku-border-subtle rounded-[16px] border p-[16px]',
  cardBody: 'rounded-[10px]',
  cardTopRow: 'items-start flex-row justify-between',
  cardTitle: 'text-ku-text-strong flex-1 font-ku-semibold text-[17px] leading-[22px] mr-[8px]',
  categoryRow: 'mt-[8px]',
  categoryTag: 'self-start bg-ku-surface-muted rounded-ku-pill px-[8px] py-[4px]',
  categoryTagText: 'text-ku-text-secondary font-ku-medium text-[11px]',
  creatorRow: 'items-center flex-row mt-[8px] min-h-[28px]',
  creatorAvatar: 'bg-ku-surface-accent rounded-[14px] h-[28px] w-[28px]',
  creatorAvatarFallback: 'items-center bg-ku-surface-accent border-ku-border-accent rounded-[14px] border h-[28px] justify-center w-[28px]',
  creatorAvatarText: 'text-ku-primary font-ku-bold text-[10px]',
  creatorText: 'text-ku-text-secondary flex-1 font-ku-medium text-[11px] ml-[8px]',
  creatorLabel: 'text-ku-text-muted font-ku-regular',
  reward: 'text-ku-primary font-ku-bold shrink-0 text-[16px] text-right',
  rewardUnit: 'text-ku-text-muted font-ku-regular text-[10px]',
  cardMeta: 'gap-[4px] mt-[16px]',
  metaItem: 'items-start flex-row min-h-[20px]',
  metaInlineText: 'flex-1 ml-[4px]',
  metaLabel: 'text-ku-text-muted font-ku-medium text-[11px] leading-[16px]',
  metaValue: 'text-ku-text-secondary font-ku-regular text-[12px] leading-[18px]',
  metaText: 'text-ku-text-secondary flex-1 font-ku-regular text-[12px] leading-[18px] ml-[4px]',
  endingSoon: 'text-ku-danger-dark font-ku-semibold',
  actionRow: 'items-center flex-row gap-[8px] justify-end mt-[16px]',
  detailAction: 'items-center border-ku-text-muted rounded-ku-pill border justify-center min-h-[44px] min-w-[66px] px-[16px] active:bg-ku-surface-muted',
  detailActionText: 'text-ku-text-secondary font-ku-medium text-[12px]',
  takeAction: 'items-center bg-ku-primary rounded-ku-pill justify-center min-h-[44px] px-[16px] active:bg-ku-primary-dark',
  takeActionText: 'text-ku-white font-ku-semibold text-[12px]',
  retryStatus: 'text-ku-text-muted font-ku-regular text-[12px] text-center',
  state: 'items-center justify-center min-h-[330px] px-[24px]',
  stateIcon: 'items-center bg-ku-surface-accent rounded-ku-pill h-[68px] justify-center mb-[16px] w-[68px]',
  stateTitle: 'text-ku-text-strong font-ku-semibold text-[19px] text-center',
  stateDescription: 'text-ku-text-secondary font-ku-regular text-[14px] leading-[21px] mt-[4px] text-center',
  stateAction: 'bg-ku-primary rounded-ku-pill mt-[16px] min-h-[46px] justify-center px-[24px]',
  stateActionText: 'text-ku-white font-ku-semibold text-[14px]',
  skeleton: 'bg-ku-surface-muted rounded-[16px] h-[108px]',
  previewButton: 'self-end mt-[8px] min-h-[34px]',
  previewButtonText: 'text-ku-text-muted font-ku-medium text-[12px] underline',
  modalBackdrop: 'bg-ku-overlay flex-1 justify-end',
  sheet: 'bg-ku-background rounded-tl-[24px] rounded-tr-[24px] max-h-[88%] px-[24px] pt-[8px]',
  sheetScroll: 'flex-1',
  sheetHandle: 'self-center bg-ku-border rounded-ku-pill h-[4px] mb-[16px] w-[42px]',
  sheetHeader: 'items-center flex-row justify-between mb-[24px]',
  sheetHeaderCopy: 'flex-1 min-w-0',
  sheetTitle: 'text-ku-text-strong font-ku-bold text-[22px]',
  sheetSummary: 'text-ku-text-muted font-ku-regular text-[12px] mt-[2px]',
  sheetCloseButton: 'items-center rounded-ku-pill h-[44px] justify-center ml-[8px] w-[44px] active:bg-ku-surface-muted',
  sheetScrollContent: 'pb-[8px]',
  sheetSection: 'mb-[16px]',
  sheetSectionTitle: 'text-ku-text-secondary font-ku-semibold text-[13px] mb-[4px]',
  optionList: 'flex-row flex-wrap gap-[4px]',
  option: 'bg-ku-white border-ku-border rounded-ku-pill border min-h-[40px] justify-center px-[16px] active:bg-ku-surface-muted',
  optionSelected: 'bg-ku-surface-accent border-ku-primary',
  optionText: 'text-ku-text-secondary font-ku-medium text-[13px]',
  optionTextSelected: 'text-ku-primary font-ku-semibold',
  rewardInputs: 'flex-row gap-[8px]',
  rewardField: 'flex-1 gap-[4px]',
  rewardFieldLabel: 'text-ku-text-secondary font-ku-semibold text-[12px]',
  rewardInput: 'bg-ku-white border-ku-border-muted rounded-[8px] border font-ku-regular text-ku-text-strong min-h-[44px] px-[12px]',
  rewardError: 'text-ku-danger font-ku-regular text-[12px] mt-[4px]',
  sheetActions: 'items-center border-t-ku-border-subtle border-t flex-row gap-[8px] mt-[8px] pt-[16px]',
  secondaryAction: 'items-center border-ku-border rounded-ku-pill border flex-1 justify-center min-h-[48px]',
  secondaryActionText: 'text-ku-text-strong font-ku-semibold text-[14px]',
  primaryAction: 'items-center bg-ku-primary rounded-ku-pill flex-[1.4] justify-center min-h-[48px]',
  primaryActionDisabled: 'opacity-[0.5]',
  primaryActionText: 'text-ku-white font-ku-semibold text-[14px]',
  alertIcon: 'bg-ku-surface-danger',
} as const;

export default styles;
