const styles = {
  safeArea: 'bg-ku-background flex-1',
  scrollContent: 'pb-[132px] px-[24px]',
  header: 'pt-[16px]',
  tagRow: 'flex-row flex-wrap gap-[4px] mb-[8px]',
  tag: 'bg-ku-surface-accent rounded-ku-pill px-[8px] py-[4px] text-ku-primary font-ku-medium text-ku-label',
  title: 'text-ku-text-strong font-ku-bold text-ku-title-large mt-[4px]',
  creator: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[8px]',
  imageGallery: 'flex-row flex-wrap gap-[8px] mt-[16px]',
  questImage: 'bg-ku-surface-image rounded-[12px] flex-1 h-[120px] min-w-[120px]',
  questImageFallback: 'items-center bg-ku-surface-muted rounded-[12px] flex-1 h-[120px] justify-center min-w-[120px] p-[8px]',
  questImageFallbackText: 'text-ku-text-muted font-ku-regular text-ku-label text-center mt-[4px]',
  heroCard: 'bg-ku-surface-accent border-ku-border-accent rounded-[18px] border mt-[24px] p-[16px]',
  heroPrimary: 'pb-[12px]',
  heroDetails: 'flex-row',
  heroItem: 'flex-1 min-w-0',
  heroItemDivider: 'border-l-ku-border-accent border-l ml-[8px] pl-[12px]',
  heroLabel: 'text-ku-text-secondary font-ku-regular text-ku-label',
  heroValue: 'text-ku-primary font-ku-bold text-ku-subtitle mt-[2px]',
  heroDetail: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[2px]',
  heroLocation: 'items-start border-ku-border-accent border-t flex-row gap-[10px] mt-[14px] pt-[14px]',
  heroLocationCopy: 'flex-1 min-w-0',
  heroLocationValue: 'text-ku-text-strong font-ku-medium text-ku-body mt-[2px]',
  section: 'mt-[32px]',
  sectionTitle: 'text-ku-text-strong font-ku-bold text-ku-section mb-[8px]',
  body: 'text-ku-text-secondary font-ku-regular text-ku-body',
  requirementCard: 'bg-ku-white border-ku-border-subtle rounded-[14px] border gap-[12px] p-[16px]',
  requirementRow: 'gap-[2px]',
  requirementLabel: 'text-ku-text-muted font-ku-medium text-ku-label',
  requirementValue: 'text-ku-text-strong font-ku-medium text-ku-body-small',
  requirementDescription: 'text-ku-text-secondary font-ku-regular text-ku-meta mt-[2px]',
  confirmHeader: 'items-center flex-row justify-between',
  sheetCloseButton: 'items-center rounded-ku-pill h-[44px] justify-center ml-[8px] w-[44px] active:bg-ku-surface-muted',
  statusCard: 'items-center bg-ku-surface-success border-ku-border-success rounded-[16px] border mt-[24px] p-[16px]',
  statusCardBlocked: 'bg-ku-surface-muted border-ku-border-subtle',
  statusTitle: 'text-ku-primary font-ku-bold text-ku-emphasis text-center',
  statusDescription: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[4px] text-center',
  statusAction: 'items-center border-ku-primary rounded-ku-pill border mt-[12px] min-h-[48px] justify-center px-[16px]',
  statusActionText: 'text-ku-primary font-ku-semibold text-ku-body-small',
  actionBar: 'bg-ku-background border-t-ku-border-subtle border-t bottom-0 left-0 p-[16px] absolute right-0',
  primaryAction: 'items-center bg-ku-primary rounded-ku-pill justify-center min-h-[52px] px-[24px]',
  primaryActionText: 'text-ku-white font-ku-semibold text-ku-control',
  modalBackdrop: 'bg-ku-overlay flex-1 justify-end',
  confirmSheet: 'bg-ku-background rounded-tl-[24px] rounded-tr-[24px] p-[24px]',
  confirmTitle: 'text-ku-text-strong font-ku-bold text-ku-title-small',
  confirmDescription: 'text-ku-text-secondary font-ku-regular text-ku-control mt-[4px]',
  confirmSummary: 'bg-ku-surface-accent rounded-[14px] gap-[6px] mt-[16px] p-[16px]',
  confirmSummaryText: 'text-ku-text-strong font-ku-medium text-ku-body-small',
  confirmActions: 'flex-row gap-[8px] mt-[24px]',
  cancelAction: 'items-center border-ku-border rounded-ku-pill border flex-1 justify-center min-h-[50px]',
  cancelActionText: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  confirmAction: 'items-center bg-ku-primary rounded-ku-pill flex-[1.4] justify-center min-h-[50px]',
  confirmActionText: 'text-ku-white font-ku-semibold text-ku-body-small',
} as const;

export default styles;
