const styles = {
  safeArea: 'bg-ku-background flex-1',
  scrollContent: 'pb-[180px] px-[24px]',
  headerBlock: 'pb-[24px] pt-[16px]',
  eyebrow: 'text-ku-primary font-ku-bold text-[11px] tracking-[1.2px] mb-[4px]',
  title: 'text-ku-text-strong font-ku-bold text-[30px] leading-[38px]',
  progressHeader: 'items-baseline flex-row justify-between mt-[16px]',
  stepText: 'text-ku-text-strong font-ku-semibold text-[15px]',
  stepName: 'text-ku-text-muted font-ku-medium text-[13px]',
  progressTrack: 'flex-row gap-[4px] mt-[8px]',
  progressSegment: 'bg-ku-border-subtle rounded-[4px] flex-1 h-[5px]',
  progressSegmentActive: 'bg-ku-primary',
  sectionHeading: 'items-start flex-row gap-[8px] mb-[24px]',
  sectionNumber: 'items-center bg-ku-surface-accent border-ku-border-accent rounded-ku-pill border h-[32px] justify-center w-[32px]',
  sectionNumberText: 'text-ku-primary font-ku-bold text-[11px]',
  sectionHeadingText: 'flex-1',
  sectionTitle: 'text-ku-text-strong font-ku-bold text-[20px] leading-[26px]',
  sectionDescription: 'text-ku-text-secondary font-ku-regular text-[13px] leading-[19px] mt-[3px]',
  fieldGroup: 'mb-[16px] w-full',
  fieldLabel: 'text-ku-text-secondary font-ku-bold text-[13px] mb-[4px]',
  required: 'text-ku-danger',
  optional: 'text-ku-text-muted font-ku-regular text-[12px]',
  helperText: 'text-ku-text-muted font-ku-regular text-[12px] leading-[17px] mt-[4px]',
  errorText: 'text-ku-danger-dark font-ku-medium text-[12px] leading-[17px] mt-[4px]',
  fieldError: 'border-ku-danger',
  dateField: 'items-center bg-ku-white border-ku-border rounded-[8px] border flex-row justify-between min-h-[48px] px-[16px]',
  dateText: 'text-ku-text-strong font-ku-regular text-[15px]',
  placeholderText: 'text-ku-text-muted',
  inputWithIcon: 'items-center bg-ku-white border-ku-border rounded-[8px] border flex-row min-h-[48px] px-[16px]',
  iconInput: 'text-ku-text-strong flex-1 font-ku-regular text-[15px] ml-[8px] min-h-[46px]',
  imagePicker: 'items-center bg-ku-surface-accent border-ku-border-accent rounded-[12px] border-dashed border justify-center min-h-[144px] p-[16px]',
  imageTitle: 'text-ku-primary font-ku-semibold text-[15px] mt-[8px]',
  imageGrid: 'flex-row gap-[8px]',
  previewImage: 'rounded-[8px] h-[96px] w-[96px]',
  choiceGroup: 'gap-[8px]',
  choice: 'items-center bg-ku-white border-ku-border rounded-[8px] border flex-row justify-between min-h-[48px] px-[16px]',
  choiceSelected: 'bg-ku-surface-accent border-ku-primary',
  choiceText: 'text-ku-text-secondary flex-1 font-ku-medium text-[14px]',
  choiceTextSelected: 'text-ku-primary font-ku-semibold',
  choiceHint: 'text-ku-text-secondary font-ku-regular text-[12px] leading-[17px] mb-[24px] -mt-[8px]',
  currencyInput: 'items-center bg-ku-white border-ku-border rounded-[8px] border flex-row min-h-[48px] px-[16px]',
  currencySymbol: 'text-ku-primary font-ku-bold text-[17px]',
  currencyTextInput: 'text-ku-text-strong flex-1 font-ku-regular text-[15px] ml-[8px] min-h-[46px]',
  currencyUnit: 'text-ku-text-muted font-ku-medium text-[12px]',
  reviewHeading: 'items-center flex-row gap-[8px] mb-[8px] mt-[8px]',
  reviewTitle: 'text-ku-text-strong font-ku-semibold text-[16px]',
  reviewCard: 'bg-ku-surface border-ku-border-subtle rounded-[10px] border p-[16px]',
  summaryRow: 'border-b-ku-border-subtle border-b flex-row justify-between py-[8px]',
  summaryLabel: 'text-ku-text-muted font-ku-regular text-[13px]',
  summaryValue: 'text-ku-text-strong flex-1 font-ku-medium text-[13px] ml-[16px] text-right',
  actionBar: 'items-center bg-ku-background border-t-ku-border-subtle border-t flex-row gap-[8px] px-[24px] py-[8px]',
  backButton: 'flex-[0.85]',
  nextButton: 'flex-[1.4]',
  primaryButtonText: 'text-ku-white font-ku-semibold text-[16px]',
  buttonContent: 'items-center flex-row gap-[4px] justify-center',
  successState: 'items-center flex-1 justify-center p-[32px]',
  successIcon: 'items-center bg-ku-surface-success border-ku-border-success rounded-ku-pill border h-[72px] justify-center mb-[24px] w-[72px]',
  successTitle: 'text-ku-text-strong font-ku-bold text-[24px] text-center',
  successDescription: 'text-ku-text-secondary font-ku-regular text-[14px] leading-[21px] mt-[8px] max-w-[320px] text-center',
  fullButton: 'mt-[24px]',
} as const;

export default styles;
