import { StyleSheet } from 'react-native';

import { colors } from '@/theme/colors';
import { spacing } from '@/theme/spacing';
import { fontFamily } from '@/theme/typography';

const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: colors.background,
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 180,
    paddingHorizontal: spacing.lg,
  },
  headerBlock: {
    paddingBottom: spacing.lg,
    paddingTop: spacing.md,
  },
  eyebrow: {
    color: colors.primary,
    fontFamily: fontFamily.bold,
    fontSize: 11,
    letterSpacing: 1.2,
    marginBottom: spacing.xs,
  },
  title: {
    color: colors.textStrong,
    fontFamily: fontFamily.bold,
    fontSize: 30,
    lineHeight: 38,
  },
  progressHeader: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.md,
  },
  stepText: {
    color: colors.textStrong,
    fontFamily: fontFamily.semiBold,
    fontSize: 15,
  },
  stepName: {
    color: colors.textMuted,
    fontFamily: fontFamily.medium,
    fontSize: 13,
  },
  progressTrack: {
    flexDirection: 'row',
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  progressSegment: {
    backgroundColor: colors.borderSubtle,
    borderRadius: 4,
    flex: 1,
    height: 5,
  },
  progressSegmentActive: {
    backgroundColor: colors.primary,
  },
  sectionHeading: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  sectionNumber: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAccent,
    borderColor: colors.borderAccent,
    borderRadius: 999,
    borderWidth: 1,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  sectionNumberText: {
    color: colors.primary,
    fontFamily: fontFamily.bold,
    fontSize: 11,
  },
  sectionHeadingText: {
    flex: 1,
  },
  sectionTitle: {
    color: colors.textStrong,
    fontFamily: fontFamily.bold,
    fontSize: 20,
    lineHeight: 26,
  },
  sectionDescription: {
    color: colors.textSecondary,
    fontFamily: fontFamily.regular,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 3,
  },
  fieldGroup: {
    marginBottom: spacing.md,
    width: '100%',
  },
  fieldLabel: {
    color: colors.textSecondary,
    fontFamily: fontFamily.bold,
    fontSize: 13,
    marginBottom: spacing.xs,
  },
  required: {
    color: colors.danger,
  },
  optional: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 12,
  },
  helperText: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 12,
    lineHeight: 17,
    marginTop: spacing.xs,
  },
  errorText: {
    color: colors.dangerDark,
    fontFamily: fontFamily.medium,
    fontSize: 12,
    lineHeight: 17,
    marginTop: spacing.xs,
  },
  fieldError: {
    borderColor: colors.danger,
  },
  dateField: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: spacing.md,
  },
  dateText: {
    color: colors.textStrong,
    fontFamily: fontFamily.regular,
    fontSize: 15,
  },
  placeholderText: {
    color: colors.textMuted,
  },
  inputWithIcon: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 48,
    paddingHorizontal: spacing.md,
  },
  iconInput: {
    color: colors.textStrong,
    flex: 1,
    fontFamily: fontFamily.regular,
    fontSize: 15,
    marginLeft: spacing.sm,
    minHeight: 46,
  },
  imagePicker: {
    alignItems: 'center',
    backgroundColor: colors.surfaceAccent,
    borderColor: colors.borderAccent,
    borderRadius: 12,
    borderStyle: 'dashed',
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 144,
    padding: spacing.md,
  },
  imageTitle: {
    color: colors.primary,
    fontFamily: fontFamily.semiBold,
    fontSize: 15,
    marginTop: spacing.sm,
  },
  imageGrid: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  previewImage: {
    borderRadius: 8,
    height: 96,
    width: 96,
  },
  choiceGroup: {
    gap: spacing.sm,
  },
  choice: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: spacing.md,
  },
  choiceSelected: {
    backgroundColor: colors.surfaceAccent,
    borderColor: colors.primary,
  },
  choiceText: {
    color: colors.textSecondary,
    flex: 1,
    fontFamily: fontFamily.medium,
    fontSize: 14,
  },
  choiceTextSelected: {
    color: colors.primary,
    fontFamily: fontFamily.semiBold,
  },
  choiceHint: {
    color: colors.textSecondary,
    fontFamily: fontFamily.regular,
    fontSize: 12,
    lineHeight: 17,
    marginBottom: spacing.lg,
    marginTop: -spacing.sm,
  },
  currencyInput: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 48,
    paddingHorizontal: spacing.md,
  },
  currencySymbol: {
    color: colors.primary,
    fontFamily: fontFamily.bold,
    fontSize: 17,
  },
  currencyTextInput: {
    color: colors.textStrong,
    flex: 1,
    fontFamily: fontFamily.regular,
    fontSize: 15,
    marginLeft: spacing.sm,
    minHeight: 46,
  },
  currencyUnit: {
    color: colors.textMuted,
    fontFamily: fontFamily.medium,
    fontSize: 12,
  },
  reviewHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.sm,
    marginTop: spacing.sm,
  },
  reviewTitle: {
    color: colors.textStrong,
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
  },
  reviewCard: {
    backgroundColor: colors.surface,
    borderColor: colors.borderSubtle,
    borderRadius: 10,
    borderWidth: 1,
    padding: spacing.md,
  },
  summaryRow: {
    borderBottomColor: colors.borderSubtle,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: spacing.sm,
  },
  summaryLabel: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 13,
  },
  summaryValue: {
    color: colors.textStrong,
    flex: 1,
    fontFamily: fontFamily.medium,
    fontSize: 13,
    marginLeft: spacing.md,
    textAlign: 'right',
  },
  actionBar: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderTopColor: colors.borderSubtle,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  backButton: {
    flex: 0.85,
  },
  nextButton: {
    flex: 1.4,
  },
  primaryButtonText: {
    color: colors.white,
    fontFamily: fontFamily.semiBold,
    fontSize: 16,
  },
  buttonContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
    justifyContent: 'center',
  },
  successState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: spacing.xl,
  },
  successIcon: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSuccess,
    borderColor: colors.borderSuccess,
    borderRadius: 999,
    borderWidth: 1,
    height: 72,
    justifyContent: 'center',
    marginBottom: spacing.lg,
    width: 72,
  },
  successTitle: {
    color: colors.textStrong,
    fontFamily: fontFamily.bold,
    fontSize: 24,
    textAlign: 'center',
  },
  successDescription: {
    color: colors.textSecondary,
    fontFamily: fontFamily.regular,
    fontSize: 14,
    lineHeight: 21,
    marginTop: spacing.sm,
    maxWidth: 320,
    textAlign: 'center',
  },
  fullButton: {
    marginTop: spacing.lg,
  },
});

export default styles;
