const styles = {
  safeArea: 'bg-ku-background flex-1',
  headerBlock: 'pb-[28px] pt-[16px]',
  validationSummary: 'bg-ku-surface-danger border border-ku-border-danger rounded-[8px] px-[12px] py-[10px] mt-[16px]',
  validationSummaryText: 'text-ku-danger-dark font-ku-medium text-ku-meta',
  progressHeader: 'items-baseline flex-row justify-between mt-[16px]',
  stepText: 'text-ku-text-strong font-ku-semibold text-ku-control',
  stepName: 'text-ku-text-muted font-ku-medium text-ku-meta',
  progressTrack: 'flex-row gap-[4px] mt-[8px]',
  progressSegment: 'items-center flex-1 justify-center min-h-[44px]',
  progressSegmentBar: 'bg-ku-border-subtle rounded-[4px] h-[5px] w-full',
  progressSegmentActive: 'bg-ku-primary',
  stepLabels: 'flex-row justify-between mt-[6px]',
  stepLabel: 'text-ku-text-muted font-ku-medium text-ku-caption',
  stepLabelActive: 'text-ku-primary font-ku-bold',
  sectionHeading: 'mb-[24px]',
  sectionHeadingText: 'flex-1',
  sectionTitle: 'text-ku-text-strong font-ku-bold text-ku-section',
  sectionDescription: 'text-ku-text-secondary font-ku-regular text-ku-meta mt-[3px]',
  fieldGroup: 'mb-[16px] w-full',
  fieldLabel: 'text-ku-text-secondary font-ku-bold text-ku-meta mb-[4px]',
  required: 'text-ku-danger',
  optional: 'text-ku-text-muted font-ku-regular text-ku-label',
  helperText: 'text-ku-text-muted font-ku-regular text-ku-label mt-[4px]',
  autosaveStatus: 'items-center flex-row justify-between min-h-[28px] mt-[4px]',
  autosaveText: 'text-ku-text-muted font-ku-regular text-ku-label',
  errorText: 'text-ku-danger-dark font-ku-medium text-ku-label mt-[4px]',
  fieldError: 'border-ku-danger',
  dateField: 'items-center bg-ku-white border-ku-border rounded-[8px] border flex-row justify-between min-h-[48px] px-[16px]',
  dateText: 'text-ku-text-strong flex-1 font-ku-regular min-w-0 mr-[12px] text-ku-control',
  placeholderText: 'text-ku-text-muted',
  inputWithIcon: 'items-center bg-ku-white border-ku-border rounded-[8px] border flex-row min-h-[48px] px-[16px]',
  modalBackdrop: 'bg-ku-overlay flex-1 justify-end',
  pickerSheet: 'bg-ku-background rounded-tl-[24px] rounded-tr-[24px] px-[16px] pb-[24px] pt-[16px]',
  pickerHeader: 'items-center flex-row justify-between mb-[8px]',
  pickerTitle: 'text-ku-text-strong font-ku-bold text-ku-body',
  pickerDoneButton: 'items-center min-h-[44px] justify-center px-[8px]',
  pickerDoneText: 'text-ku-primary font-ku-semibold text-ku-body-small',
  iconInput: 'text-ku-text-strong flex-1 font-ku-regular text-ku-control ml-[8px] min-h-[46px]',
  onlineToggle: 'bg-ku-surface-subtle border-ku-border-subtle rounded-[12px] border flex-row items-center min-h-[64px] mb-[16px] p-[12px]',
  checkbox: 'border-ku-border bg-ku-white border h-[24px] items-center justify-center rounded-[6px] w-[24px]',
  checkboxChecked: 'bg-ku-primary border-ku-primary',
  onlineToggleCopy: 'flex-1 ml-[12px]',
  onlineToggleTitle: 'text-ku-text-strong font-ku-semibold text-ku-control',
  onlineToggleHint: 'text-ku-text-muted font-ku-regular text-ku-label mt-[1px]',
  imagePicker: 'items-center bg-ku-surface-accent border-ku-border-accent rounded-[12px] border-dashed border justify-center min-h-[144px] p-[16px]',
  imageTitle: 'text-ku-primary font-ku-semibold text-ku-control mt-[8px]',
  changeImagesButton: 'items-center min-h-[48px] justify-center mt-[8px] px-[12px]',
  imageGrid: 'flex-row flex-wrap gap-[8px]',
  imagePreviewContainer: 'relative',
  previewImage: 'rounded-[8px] h-[96px] w-[96px]',
  removeImageButton: 'absolute bg-ku-black items-center justify-center rounded-ku-pill h-[32px] right-[4px] top-[4px] w-[32px]',
  choiceGroup: 'gap-[8px]',
  choice: 'items-center bg-ku-white border-ku-border rounded-[8px] border flex-row justify-between min-h-[48px] px-[16px]',
  choiceSelected: 'bg-ku-surface-accent border-ku-primary',
  choiceText: 'text-ku-text-secondary flex-1 font-ku-medium text-ku-body-small',
  choiceTextSelected: 'text-ku-primary font-ku-semibold',
  choiceHint: 'text-ku-text-secondary font-ku-regular text-ku-meta mb-[24px] -mt-[8px]',
  currencyInput: 'items-center bg-ku-white border-ku-border rounded-[8px] border flex-row min-h-[48px] px-[16px]',
  currencySymbol: 'text-ku-primary font-ku-bold text-ku-emphasis',
  currencyTextInput: 'text-ku-text-strong flex-1 font-ku-regular text-ku-control ml-[8px] min-h-[46px]',
  currencyUnit: 'text-ku-text-muted font-ku-medium text-ku-label',
  readOnlyField: 'items-center bg-ku-surface-muted border-ku-border-muted rounded-[8px] border min-h-[48px] px-[12px]',
  readOnlyValue: 'text-ku-text-strong font-ku-medium text-ku-body-small',
  singleHeadcountHint: 'text-ku-text-muted font-ku-regular text-ku-label mt-[4px]',
  summaryHeading: 'items-center flex-row gap-[8px] mb-[8px] mt-[8px]',
  summaryTitle: 'text-ku-text-strong font-ku-semibold text-ku-body',
  summaryCard: 'bg-ku-surface border-ku-border-subtle rounded-[10px] border p-[16px]',
  summaryRow: 'border-b-ku-border-subtle border-b flex-row items-start py-[8px]',
  summaryLabel: 'text-ku-text-muted flex-[0.38] font-ku-regular text-ku-meta mr-[8px]',
  summaryValue: 'text-ku-text-strong flex-1 font-ku-medium text-ku-meta min-w-0',
  actionBar: 'items-center bg-ku-background border-t-ku-border-subtle border-t flex-row gap-[8px] px-[24px] pt-[8px]',
  nextButton: 'flex-1',
  finalActionButton: 'flex-1',
  primaryButtonText: 'text-ku-white font-ku-semibold text-ku-body',
  buttonContent: 'items-center flex-row gap-[4px] justify-center',
  loadingState: 'items-center flex-1 justify-center gap-[12px] p-[32px]',
  loadingText: 'text-ku-text-secondary font-ku-regular text-ku-body-small text-center',
  successState: 'items-center flex-1 justify-center p-[32px]',
  successIcon: 'items-center bg-ku-surface-success border-ku-border-success rounded-ku-pill border h-[72px] justify-center mb-[24px] w-[72px]',
  successTitle: 'text-ku-text-strong font-ku-bold text-ku-title text-center',
  successDescription: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[8px] max-w-[320px] text-center',
  fullButton: 'mt-[24px]',
} as const;

export default styles;
