import { StyleSheet } from "react-native";

import { fontFamily } from "@/theme/typography";

export const hirerHomeStyles = StyleSheet.create({
  screenContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  screenHeader: {
    paddingHorizontal: 4,
    paddingBottom: 22,
  },
  prototypeNotice: {
    alignSelf: "flex-start",
    borderRadius: 9999,
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  prototypeNoticeText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
    lineHeight: 18,
  },
  emptyState: {
    alignItems: "center",
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 220,
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  emptyTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 18,
    lineHeight: 24,
    textAlign: "center",
  },
  emptyDescription: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
    textAlign: "center",
  },
  screenTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 28,
    lineHeight: 36,
  },
  screenSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 4,
  },
  sectionTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 18,
    lineHeight: 24,
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  card: {
    borderRadius: 32,
    borderWidth: 2.5,
    overflow: "hidden",
    shadowOffset: { height: 4, width: 3 },
    shadowRadius: 4,
    shadowOpacity: 0.9,
    elevation: 3,
  },
  cardHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 24,
    paddingHorizontal: 28,
    paddingTop: 28,
  },
  cardHeaderCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 12,
  },
  statusLabel: {
    fontFamily: fontFamily.regular,
    fontSize: 16,
    letterSpacing: 0.4,
    lineHeight: 24,
  },
  cardTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 26,
    lineHeight: 34,
    marginTop: 10,
  },
  headerArrow: {
    alignItems: "center",
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  divider: {
    height: 1,
  },
  cardBody: {
    flexDirection: "row",
    gap: 22,
    paddingHorizontal: 28,
    paddingVertical: 32,
  },
  workerColumn: {
    flex: 0.88,
    minWidth: 0,
  },
  workerAvatarButton: {
    alignSelf: "flex-start",
  },
  workerAvatar: {
    alignItems: "center",
    borderRadius: 24,
    borderWidth: 1.5,
    justifyContent: "center",
    overflow: "hidden",
  },
  workerName: {
    fontFamily: fontFamily.bold,
    fontSize: 22,
    lineHeight: 30,
    marginTop: 16,
  },
  workerProfileButton: {
    alignSelf: "flex-start",
    justifyContent: "center",
    minHeight: 48,
    marginTop: 4,
  },
  workerProfileText: {
    fontFamily: fontFamily.bold,
    fontSize: 17,
    lineHeight: 24,
  },
  timelineColumn: {
    flex: 1.12,
    minWidth: 0,
  },
  timelineTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 19,
    letterSpacing: 1.2,
    lineHeight: 26,
    marginBottom: 14,
  },
  timelineRow: {
    alignItems: "center",
    flexDirection: "row",
    minHeight: 50,
  },
  timelineMarkerColumn: {
    alignItems: "center",
    alignSelf: "stretch",
    justifyContent: "center",
    position: "relative",
    width: 38,
  },
  timelineLine: {
    bottom: -12,
    position: "absolute",
    top: 31,
    width: 4,
  },
  marker: {
    borderRadius: 16,
    borderWidth: 3,
    height: 30,
    width: 30,
  },
  markerCurrentOuter: {
    alignItems: "center",
    borderRadius: 23,
    height: 46,
    justifyContent: "center",
    width: 46,
  },
  markerCurrentInner: {
    borderRadius: 16,
    height: 30,
    width: 30,
  },
  timelineLabel: {
    flex: 1,
    fontFamily: fontFamily.regular,
    fontSize: 16,
    lineHeight: 24,
    marginLeft: 12,
  },
  timelineLabelCurrent: {
    fontFamily: fontFamily.bold,
  },
  cardFooter: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 80,
    paddingHorizontal: 28,
    paddingVertical: 16,
  },
  dueLabel: {
    flex: 1,
    fontFamily: fontFamily.regular,
    fontSize: 15,
    lineHeight: 22,
    paddingRight: 12,
  },
  detailsButton: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 8,
  },
  detailsText: {
    fontFamily: fontFamily.bold,
    fontSize: 17,
    lineHeight: 24,
  },
});

export const hirerHomePalette = {
  light: {
    ink: "#2D286F",
    muted: "#77779D",
    surface: "#FFFEFD",
    workerSurface: "#E4F1EE",
    workerBorder: "#C9C8F4",
    completed: "#2B946E",
    current: "#F2A037",
    currentHalo: "#FFF0D5",
    pending: "#AAA9CB",
    connector: "#D9D7ED",
    footer: "#F8F7FF",
    footerBorder: "#E4E1EC",
    shadow: "#F5E7D0",
    terminal: "#C65A55",
  },
  dark: {
    ink: "#DCD9FF",
    muted: "#B4B1D2",
    surface: "#1B211E",
    workerSurface: "#203C35",
    workerBorder: "#7773B8",
    completed: "#55C698",
    current: "#FFB24C",
    currentHalo: "#4B3821",
    pending: "#8583A8",
    connector: "#4D4A68",
    footer: "#24232F",
    footerBorder: "#4A475B",
    shadow: "#0C120F",
    terminal: "#FF8B84",
  },
} as const;
