import { StyleSheet } from "react-native";

import { darkColors, lightColors } from "@/theme/colors";
import { fontFamily } from "@/theme/typography";

export const hirerHomeStyles = StyleSheet.create({
  screenContent: {
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  screenHeader: {
    paddingHorizontal: 4,
    paddingBottom: 22,
  },
  prototypeNotice: {
    alignSelf: "flex-start",
    borderRadius: 9999,
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  prototypeNoticeText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
    lineHeight: 18,
  },
  emptyState: {
    alignItems: "center",
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 220,
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  emptyTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 18,
    lineHeight: 24,
    textAlign: "center",
  },
  emptyDescription: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
    textAlign: "center",
  },
  screenTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 28,
    lineHeight: 36,
  },
  screenSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 4,
  },
  sectionHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  sectionTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 18,
    lineHeight: 24,
  },
  sectionCounterBadge: {
    borderRadius: 9999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  sectionCounterText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
    lineHeight: 16,
  },
  card: {
    borderRadius: 18,
    borderWidth: 1.5,
    overflow: "hidden",
    shadowOffset: { height: 4, width: 0 },
    shadowRadius: 10,
    shadowOpacity: 0.1,
    elevation: 4,
  },
  cardTopAccent: {
    height: 3.5,
    width: "100%",
  },
  cardHeader: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  cardHeaderMetaRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  tagBadge: {
    alignItems: "center",
    borderRadius: 9999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  tagText: {
    fontFamily: fontFamily.medium,
    fontSize: 11,
    lineHeight: 15,
  },
  statusBadge: {
    alignItems: "center",
    borderRadius: 9999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  statusBadgeDot: {
    borderRadius: 4,
    height: 6,
    width: 6,
  },
  statusLabel: {
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
    letterSpacing: 0.2,
    lineHeight: 16,
  },
  cardTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardTitle: {
    flex: 1,
    fontFamily: fontFamily.bold,
    fontSize: 17,
    lineHeight: 23,
    paddingRight: 8,
  },
  headerArrow: {
    alignItems: "center",
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  divider: {
    height: 1,
  },
  cardBody: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  workerBanner: {
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  workerLeading: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 10,
    minWidth: 0,
  },
  workerAvatar: {
    alignItems: "center",
    borderRadius: 9999,
    borderWidth: 1,
    height: 40,
    justifyContent: "center",
    overflow: "hidden",
    width: 40,
  },
  workerAvatarText: {
    fontFamily: fontFamily.bold,
    fontSize: 14,
  },
  workerCopy: {
    flex: 1,
    minWidth: 0,
  },
  workerName: {
    fontFamily: fontFamily.bold,
    fontSize: 14,
    lineHeight: 18,
  },
  workerRole: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 1,
  },
  workerProfileButton: {
    alignItems: "center",
    flexDirection: "row",
    gap: 2,
    justifyContent: "center",
    minHeight: 44,
    paddingLeft: 8,
  },
  workerProfileText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
    lineHeight: 16,
  },
  progressSection: {
    marginTop: 14,
  },
  progressHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  timelineTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
  stepProgressText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
    lineHeight: 16,
  },
  stagesTrack: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    position: "relative",
  },
  trackLine: {
    height: 2,
    left: 16,
    position: "absolute",
    right: 16,
    top: 9,
  },
  stageStep: {
    alignItems: "center",
    flex: 1,
  },
  stepDot: {
    alignItems: "center",
    borderRadius: 9999,
    borderWidth: 2,
    height: 20,
    justifyContent: "center",
    width: 20,
    zIndex: 2,
  },
  stepDotCurrentOuter: {
    alignItems: "center",
    borderRadius: 9999,
    height: 22,
    justifyContent: "center",
    width: 22,
    zIndex: 2,
  },
  stepDotCurrentInner: {
    borderRadius: 9999,
    height: 10,
    width: 10,
  },
  stepLabel: {
    fontFamily: fontFamily.regular,
    fontSize: 10,
    lineHeight: 14,
    marginTop: 6,
    textAlign: "center",
  },
  stepLabelCurrent: {
    fontFamily: fontFamily.bold,
  },
  cardFooter: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 44,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  dueRow: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 6,
    paddingRight: 8,
  },
  dueLabel: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    lineHeight: 16,
  },
  detailsButton: {
    alignItems: "center",
    flexDirection: "row",
    gap: 2,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 6,
  },
  detailsText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 12,
    lineHeight: 16,
  },
  carouselContainer: {
    marginBottom: 4,
  },
  carouselPagination: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    justifyContent: "center",
    marginTop: 12,
  },
  paginationDot: {
    borderRadius: 3,
    height: 6,
  },
  paginationDotActive: {
    width: 20,
  },
  paginationDotInactive: {
    width: 6,
  },
  quickAccessSection: {
    marginTop: 22,
  },
  quickAccessTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 18,
    lineHeight: 24,
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  quickAccessGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  quickAccessCard: {
    alignItems: "center",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 70,
    paddingHorizontal: 14,
    paddingVertical: 12,
    width: "48%",
    flexGrow: 1,
  },
  quickAccessIconBox: {
    alignItems: "center",
    borderRadius: 12,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  quickAccessCopy: {
    flex: 1,
    minWidth: 0,
  },
  quickAccessItemTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 14,
    lineHeight: 18,
  },
  quickAccessItemDesc: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 2,
  },
});

export const hirerHomePalette = {
  light: {
    cardBg: lightColors.surfaceSuccess,
    cardBorder: "#B0D7B8",
    cardTopAccent: lightColors.primary,
    cardShadow: "rgba(1, 73, 37, 0.12)",
    ink: lightColors.primaryDeep,
    secondaryText: "#264D33",
    muted: "#4C6D56",
    tagBg: "#FFFFFF",
    tagText: lightColors.primary,
    tagBorder: "#C0DECA",
    statusBg: lightColors.primary,
    statusText: "#FFFFFF",
    statusBorder: lightColors.primary,
    statusDot: lightColors.successLight,
    workerBg: "#FFFFFF",
    workerBorder: "#CDE4D4",
    avatarBg: lightColors.surfaceSuccess,
    avatarText: lightColors.primary,
    primary: lightColors.primary,
    primaryDeep: lightColors.primaryDeep,
    stepCompleted: lightColors.primary,
    stepCompletedCheck: "#FFFFFF",
    stepCurrentOuter: "#FFFFFF",
    stepCurrentInner: lightColors.primary,
    stepUpcoming: "#8EAD96",
    stepConnector: "#A8CFB2",
    footerBg: "#F4FAF5",
    footerBorder: "#C6E2CD",
    terminalBg: lightColors.surfaceDanger,
    terminalText: lightColors.danger,
    terminalBorder: lightColors.borderDanger,
  },
  dark: {
    cardBg: darkColors.surfaceSuccess,
    cardBorder: "#2E5B3C",
    cardTopAccent: darkColors.successBright,
    cardShadow: "rgba(0, 0, 0, 0.45)",
    ink: darkColors.textStrong,
    secondaryText: darkColors.textSecondary,
    muted: darkColors.textMuted,
    tagBg: "#102116",
    tagText: darkColors.primaryDeep,
    tagBorder: darkColors.borderAccent,
    statusBg: darkColors.primary,
    statusText: darkColors.textStrong,
    statusBorder: darkColors.primary,
    statusDot: "#A8F3AA",
    workerBg: "#102116",
    workerBorder: "#254430",
    avatarBg: darkColors.surfaceSuccess,
    avatarText: darkColors.success,
    primary: darkColors.successBright,
    primaryDeep: darkColors.primaryDeep,
    stepCompleted: darkColors.successBright,
    stepCompletedCheck: darkColors.black,
    stepCurrentOuter: "rgba(139, 224, 145, 0.3)",
    stepCurrentInner: darkColors.successBright,
    stepUpcoming: "#4A7056",
    stepConnector: "#2E5B3C",
    footerBg: "#102517",
    footerBorder: "#23452E",
    terminalBg: darkColors.surfaceDanger,
    terminalText: darkColors.danger,
    terminalBorder: darkColors.borderDanger,
  },
} as const;
