export const DEFAULT_PROTOTYPE_VIEWER_ID = "student-demo";
export const DEFAULT_PLATFORM_FEE_BASIS_POINTS = 500;
export const EDIT_CONSENT_WINDOW_MS = 5 * 60 * 1000;
export const PARTIAL_GROUP_START_CONSENT_WINDOW_MS = 5 * 60 * 1000;
export const PARTIAL_START_CONSENT_WINDOW_MS =
  PARTIAL_GROUP_START_CONSENT_WINDOW_MS;
export const INVITATION_WINDOW_MS = 24 * 60 * 60 * 1000;
export const DEFAULT_REWORK_LIMIT = 2;
export const PROTOTYPE_NOW = "2026-08-12T09:00:00.000Z";
