const styles = {
  safeArea: 'bg-ku-background flex-1',
  hero: 'bg-ku-surface px-[20px] pb-[12px] pt-[4px]',
  headerRow: 'items-center flex-row justify-between min-h-[48px]',
  headerSpacer: 'flex-1',
  heroIconButton: 'items-center border-ku-border-accent border rounded-[14px] h-[48px] justify-center w-[48px] active:bg-ku-surface-muted',
  heroTitle: 'text-ku-text-strong font-ku-bold text-ku-title mt-[2px] text-center',
  heroSubtitle: 'text-ku-text-secondary font-ku-regular text-ku-body-small text-center mt-[2px]',
  roleSwitch: 'bg-ku-surface border-ku-border-accent border rounded-[14px] flex-row mt-[12px] overflow-hidden p-[3px]',
  roleOption: 'items-center flex-1 justify-center min-h-[34px] px-[6px]',
  roleOptionActive: 'bg-ku-surface-accent rounded-[11px]',
  roleOptionText: 'text-ku-text-secondary font-ku-medium text-ku-caption text-center',
  roleOptionTextActive: 'text-ku-primary font-ku-semibold',
  statusTabs: 'bg-ku-surface border-ku-border-accent border rounded-[14px] flex-row mt-[10px] overflow-hidden p-[3px]',
  statusTab: 'items-center flex-1 flex-row gap-[5px] justify-center min-h-[42px] px-[4px]',
  statusTabActive: 'bg-ku-surface-accent rounded-[11px] border-b-ku-primary border-b-[2px]',
  statusTabText: 'text-ku-text-secondary font-ku-medium text-ku-label text-center',
  statusTabTextActive: 'text-ku-primary font-ku-bold',
  statusCount: 'items-center bg-ku-surface-muted rounded-ku-pill h-[20px] justify-center min-w-[20px] px-[5px]',
  statusCountActive: 'bg-ku-primary',
  statusCountText: 'text-ku-text-muted font-ku-semibold text-ku-caption',
  statusCountTextActive: 'text-ku-white',
  surface: 'bg-ku-background rounded-tl-[24px] rounded-tr-[24px] min-h-[640px] px-[16px] pb-[18px] pt-[16px]',
  list: 'gap-[8px]',
  card: 'bg-ku-card border-ku-border-subtle rounded-[16px] border p-[10px]',
  applicationCard: 'bg-ku-card border-ku-border-subtle rounded-[16px] border p-[10px]',
  cardRow: 'flex-row min-w-0',
  applicationRow: 'flex-row min-w-0',
  thumbnail: 'bg-ku-surface-image rounded-[12px] h-[104px] overflow-hidden shrink-0 w-[86px]',
  thumbnailImage: 'h-full w-full',
  thumbnailFallback: 'items-center h-full justify-center w-full',
  cardBody: 'flex-1 min-w-0 ml-[10px]',
  applicationMain: 'flex-1 min-w-0 ml-[10px] mr-[8px]',
  cardHeadingRow: 'items-start flex-row justify-between min-w-0',
  cardHeadingCopy: 'flex-1 min-w-0 mr-[5px]',
  categoryTag: 'items-center self-start rounded-ku-pill flex-row min-h-[24px] px-[7px] py-[2px]',
  categoryTagText: 'font-ku-medium text-ku-caption ml-[3px]',
  cardTitle: 'text-ku-text font-ku-semibold text-ku-body-small mt-[4px]',
  applicationTitle: 'text-ku-text font-ku-semibold text-ku-body-small mt-[4px]',
  statusPill: 'items-center border rounded-ku-pill flex-row min-h-[28px] max-w-full px-[7px] py-[3px] shrink-0',
  statusPillStretch: 'self-stretch justify-center min-w-0',
  statusText: 'font-ku-semibold text-ku-caption ml-[3px]',
  metaRow: 'items-center flex-row min-w-0 mt-[6px]',
  metaText: 'text-ku-text-secondary flex-shrink font-ku-regular text-ku-caption ml-[3px]',
  metaDivider: 'bg-ku-border-subtle h-[14px] mx-[5px] w-[1px]',
  cardDescription: 'text-ku-text-secondary font-ku-regular text-ku-caption mt-[6px]',
  applicationDescription: 'text-ku-text-secondary font-ku-regular text-ku-caption mt-[5px]',
  progressRow: 'items-center border-ku-border-subtle border-t flex-row min-w-0 mt-[10px] pt-[8px]',
  teamMetric: 'items-center flex-row min-w-0',
  metricLabel: 'text-ku-text-muted font-ku-regular text-[10px] leading-[14px] mr-[5px]',
  metricValue: 'font-ku-semibold text-[11px] leading-[15px] ml-[4px]',
  metricDivider: 'bg-ku-border-subtle h-[18px] mx-[8px] w-[1px]',
  progressMetric: 'items-center flex-1 flex-row min-w-0',
  progressTrack: 'bg-ku-border-subtle flex-1 h-[5px] min-w-[36px] overflow-hidden rounded-ku-pill',
  progressFill: 'h-full rounded-ku-pill',
  hostRow: 'items-center flex-row min-w-0 mt-[5px]',
  hostIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[22px] justify-center w-[22px]',
  hostText: 'text-ku-text-strong flex-1 font-ku-medium text-ku-caption ml-[5px]',
  applicationSide: 'items-stretch shrink-0 w-[94px]',
  sideLabel: 'text-ku-text-muted font-ku-regular text-[10px] leading-[13px] mt-[6px]',
  sideValue: 'text-ku-text-strong font-ku-semibold text-ku-caption mt-[1px]',
  sideTeam: 'items-center flex-row mt-[1px]',
  actionButton: 'items-center border-ku-primary border rounded-ku-pill flex-1 flex-row gap-[4px] justify-center min-h-[34px] px-[5px] active:bg-ku-surface-success',
  actionButtonCompact: 'min-h-[30px] mt-[8px] px-[3px]',
  actionButtonFull: 'flex-[1.01]',
  actionText: 'text-ku-primary font-ku-semibold text-ku-label text-center',
  actionTextCompact: 'text-[10px] leading-[13px]',
  actionsRow: 'flex-row gap-[8px] mt-[8px]',
  emptyState: 'items-center bg-ku-surface-muted border-ku-border-subtle border-dashed rounded-[16px] min-h-[214px] justify-center px-[24px] py-[28px]',
  emptyIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[48px] justify-center mb-[10px] w-[48px]',
  emptyTitle: 'text-ku-text-strong font-ku-semibold text-ku-body text-center',
  emptyDescription: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[4px] text-center',
  summaryStrip: 'bg-ku-surface-success border-ku-border-success rounded-[16px] border mt-[10px] px-[10px] py-[10px]',
  summaryMetrics: 'items-stretch flex-row',
  summaryMetric: 'items-center flex-1 flex-row min-w-0 px-[2px]',
  summaryIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[38px] justify-center shrink-0 w-[38px]',
  summaryCopy: 'flex-1 min-w-0 ml-[6px]',
  summaryLabel: 'text-ku-text-secondary font-ku-regular text-[10px] leading-[13px]',
  summaryValue: 'text-ku-text-strong font-ku-bold text-[18px] leading-[22px]',
  summaryDetail: 'text-ku-text-secondary font-ku-regular text-[10px] leading-[13px]',
  summaryDivider: 'bg-ku-border-accent mx-[4px] w-[1px]',
  tipCard: 'items-center bg-ku-surface-accent rounded-[12px] flex-row mt-[10px] px-[12px] py-[10px]',
  tipIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[38px] justify-center shrink-0 w-[38px]',
  tipCopy: 'flex-1 min-w-0 ml-[10px]',
  tipTitle: 'text-ku-text-strong font-ku-semibold text-ku-label',
  tipDescription: 'text-ku-text-secondary font-ku-regular text-ku-caption mt-[2px]',
} as const;

export default styles;
