const styles = {
  safeArea: 'bg-ku-background flex-1',
  hero: 'bg-ku-surface px-[20px] pb-[12px] pt-[4px] relative z-[20]',
  heroMenuOpen: 'z-[40]',
  headerRow: 'items-center flex-row justify-between min-h-[48px]',
  heroIconButton: 'items-center border-ku-border-accent border rounded-[14px] h-[48px] justify-center w-[48px] active:bg-ku-surface-muted',
  heroIconSpacer: 'h-[48px] w-[48px]',
  roleNavButton: 'items-center flex-row gap-[4px] justify-center min-h-[48px] px-[14px] rounded-ku-pill active:bg-ku-surface-muted',
  roleNavButtonOpen: 'bg-ku-surface-accent',
  roleNavText: 'text-ku-primary font-ku-bold text-ku-body',
  heroSubtitle: 'text-ku-text-secondary font-ku-regular text-ku-body-small text-center mt-[2px]',
  selectorSectionStatus: 'mt-[8px]',
  selectorLabelRow: 'items-center flex-row justify-between mb-[4px]',
  selectorLabel: 'text-ku-text-secondary font-ku-semibold text-ku-caption px-[2px]',
  selectorSwipeHint: 'items-center flex-row gap-[1px]',
  selectorSwipeHintText: 'text-ku-text-muted font-ku-medium text-[10px] leading-[14px]',
  roleMenu: 'absolute bg-ku-surface border-ku-border-accent border left-[20px] right-[20px] rounded-[16px] top-[60px] z-[50] p-[4px] shadow-[0px_4px_8px_rgb(18_32_24_/0.12)]',
  roleMenuTitle: 'text-ku-text-strong font-ku-semibold text-ku-label px-[10px] pb-[4px] pt-[6px]',
  roleMenuOption: 'items-center flex-row min-h-[60px] px-[8px] rounded-[12px]',
  roleMenuOptionActive: 'bg-ku-surface-accent',
  roleMenuIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[36px] justify-center shrink-0 w-[36px]',
  roleMenuCopy: 'flex-1 min-w-0 ml-[10px]',
  roleMenuOptionText: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  roleMenuOptionTextActive: 'text-ku-primary font-ku-bold',
  roleMenuOptionDescription: 'text-ku-text-secondary font-ku-regular text-ku-caption mt-[1px]',
  roleMenuCheck: 'items-center bg-ku-primary rounded-ku-pill h-[22px] justify-center ml-[8px] w-[22px]',
  statusTabsFrame: 'bg-ku-surface-muted border-ku-border-accent border rounded-[14px] items-center flex-row gap-[4px] min-h-[56px] overflow-hidden p-[4px]',
  statusArrow: 'items-center bg-ku-surface rounded-[10px] h-[48px] justify-center shrink-0 w-[48px] active:bg-ku-surface-accent',
  statusCurrent: 'items-center flex-1 flex-row gap-[8px] justify-center min-h-[48px] px-[6px]',
  statusCurrentText: 'text-ku-primary font-ku-bold text-ku-body-small text-center',
  statusCount: 'items-center bg-ku-surface rounded-ku-pill border-ku-border-subtle border h-[20px] justify-center min-w-[20px] px-[4px]',
  statusCountActive: 'bg-ku-primary border-ku-primary',
  statusCountText: 'text-ku-text-muted font-ku-semibold text-ku-caption',
  statusCountTextActive: 'text-ku-white',
  surface: 'bg-ku-background rounded-tl-[24px] rounded-tr-[24px] min-h-[640px] px-[16px] pb-[18px] pt-[16px]',
  list: 'gap-[8px]',
  card: 'bg-ku-card border-ku-border-subtle rounded-[16px] border p-[10px]',
  applicationCard: 'bg-ku-card border-ku-border-subtle rounded-[16px] border p-[10px]',
  cardHeadingRow: 'items-start flex-row justify-between min-w-0',
  cardHeadingCopy: 'flex-1 min-w-0 mr-[5px]',
  categoryTag: 'items-center self-start rounded-ku-pill flex-row min-h-[24px] px-[7px] py-[2px]',
  categoryTagText: 'font-ku-medium text-ku-caption ml-[3px]',
  cardTitle: 'text-ku-text font-ku-semibold text-ku-body-small mt-[4px]',
  applicationTitle: 'text-ku-text font-ku-semibold text-ku-body-small mt-[4px]',
  statusPill: 'items-center border rounded-ku-pill flex-row min-h-[28px] max-w-full px-[7px] py-[3px] shrink-0',
  statusPillStretch: 'self-stretch justify-center min-w-0',
  statusText: 'font-ku-semibold text-ku-caption ml-[3px]',
  metaRow: 'items-center flex-row min-w-0 mt-[6px]',
  metaText: 'text-ku-text-secondary flex-shrink font-ku-regular text-ku-caption ml-[3px]',
  metaDivider: 'bg-ku-border-subtle h-[14px] mx-[5px] w-[1px]',
  cardDescription: 'text-ku-text-secondary font-ku-regular text-ku-caption mt-[6px]',
  applicationDescription: 'text-ku-text-secondary font-ku-regular text-ku-caption mt-[5px]',
  teamRow: 'items-center border-ku-border-subtle border-t flex-row min-w-0 mt-[10px] pt-[8px]',
  teamMetric: 'items-center flex-row min-w-0',
  metricLabel: 'text-ku-text-muted font-ku-regular text-[10px] leading-[14px] mr-[5px]',
  metricValue: 'font-ku-semibold text-[11px] leading-[15px] ml-[4px]',
  hostRow: 'items-center flex-row min-w-0 mt-[5px]',
  hostIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[22px] justify-center w-[22px]',
  hostText: 'text-ku-text-strong flex-1 font-ku-medium text-ku-caption ml-[5px]',
  applicationFacts: 'border-ku-border-subtle border-t flex-row gap-[16px] mt-[10px] pt-[8px]',
  applicationFact: 'flex-1 min-w-0',
  sideLabel: 'text-ku-text-muted font-ku-regular text-[10px] leading-[13px] mt-[6px]',
  sideValue: 'text-ku-text-strong font-ku-semibold text-ku-caption mt-[1px]',
  sideTeam: 'items-center flex-row mt-[1px]',
  actionButton: 'items-center border-ku-primary border rounded-ku-pill flex-1 flex-row gap-[4px] justify-center min-h-[34px] px-[5px] active:bg-ku-surface-success',
  actionButtonCompact: 'min-h-[30px] mt-[8px] px-[3px]',
  actionButtonFull: 'flex-[1.01]',
  actionText: 'text-ku-primary font-ku-semibold text-ku-label text-center',
  actionTextCompact: 'text-[10px] leading-[13px]',
  actionsRow: 'flex-row gap-[8px] mt-[8px]',
  groupChatRow: 'flex-row mt-[8px]',
  actionButtonHighlighted: 'bg-ku-surface-success border-ku-border-success',
  applicantModalOverlay: 'bg-ku-overlay flex-1 justify-end',
  applicantModalBackdrop: 'absolute bottom-0 left-0 right-0 top-0',
  applicantModalSheet: 'bg-ku-card max-h-[86%] min-h-[58%] rounded-tl-[24px] rounded-tr-[24px] px-[20px] pt-[12px]',
  applicantModalHandle: 'self-center bg-ku-border-accent rounded-ku-pill h-[4px] mb-[14px] w-[40px]',
  applicantModalHeader: 'items-center flex-row justify-between',
  applicantModalHeading: 'flex-1 min-w-0 pr-[12px]',
  applicantModalTitle: 'text-ku-text-strong font-ku-bold text-ku-subtitle',
  applicantModalSubtitle: 'text-ku-text-secondary font-ku-regular text-ku-caption mt-[2px]',
  applicantModalClose: 'items-center bg-ku-surface-muted rounded-ku-pill h-[40px] justify-center w-[40px]',
  applicantContext: 'items-center bg-ku-surface-accent rounded-[14px] flex-row mt-[14px] px-[12px] py-[10px]',
  applicantContextIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[38px] justify-center shrink-0 w-[38px]',
  applicantContextCopy: 'flex-1 min-w-0 ml-[10px]',
  applicantContextLabel: 'text-ku-text-secondary font-ku-semibold text-ku-caption',
  applicantContextTitle: 'text-ku-text-strong font-ku-medium text-ku-label mt-[1px]',
  applicantModalScroll: 'flex-1',
  applicantModalContent: 'pb-[8px] pt-[16px]',
  applicantSectionLabel: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  applicantList: 'gap-[8px] mt-[8px]',
  applicantRow: 'bg-ku-surface-muted border-ku-border-subtle border rounded-[14px] px-[10px] py-[9px]',
  applicantRowSelected: 'bg-ku-surface-success border-ku-border-success',
  applicantSelectRow: 'items-center flex-row min-h-[58px]',
  applicantSelectionBox: 'items-center border-ku-border-accent border rounded-[7px] h-[24px] justify-center shrink-0 w-[24px]',
  applicantSelectionBoxSelected: 'bg-ku-primary border-ku-primary',
  applicantAvatar: 'items-center rounded-ku-pill h-[42px] justify-center shrink-0 w-[42px]',
  applicantAvatarText: 'text-ku-primary font-ku-bold text-ku-caption',
  applicantCopy: 'flex-1 min-w-0 ml-[10px]',
  applicantName: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  applicantDetail: 'text-ku-text-secondary font-ku-regular text-ku-caption mt-[1px]',
  applicantApplied: 'items-center flex-row gap-[3px] mt-[3px]',
  applicantAppliedText: 'text-ku-text-muted font-ku-regular text-[10px] leading-[13px]',
  applicantActionsRow: 'flex-row justify-end mt-[4px]',
  applicantProfileButton: 'items-center flex-row gap-[4px] min-h-[32px] px-[8px] rounded-ku-pill active:bg-ku-surface-accent',
  applicantProfileText: 'text-ku-primary font-ku-semibold text-ku-caption',
  applicantSectionHeader: 'items-center flex-row justify-between',
  selectedApplicantsText: 'text-ku-primary font-ku-semibold text-ku-caption',
  selectApplicantsHint: 'text-ku-text-secondary font-ku-regular text-ku-caption mt-[3px]',
  applicantConfirmFooter: 'items-center border-ku-border-subtle border-t flex-row gap-[10px] pt-[12px]',
  applicantConfirmCopy: 'flex-1 min-w-0',
  applicantConfirmCount: 'text-ku-text-strong font-ku-semibold text-ku-caption',
  applicantConfirmHint: 'text-ku-text-secondary font-ku-regular text-[10px] leading-[13px] mt-[2px]',
  applicantConfirmButton: 'items-center bg-ku-primary rounded-ku-pill flex-row gap-[5px] justify-center min-h-[46px] px-[14px] active:bg-ku-primary-deep',
  applicantConfirmButtonText: 'text-ku-white font-ku-semibold text-ku-caption',
  profileModalOverlay: 'bg-ku-overlay flex-1 justify-end',
  profileModalBackdrop: 'absolute bottom-0 left-0 right-0 top-0',
  profileModalSheet: 'bg-ku-card max-h-[72%] rounded-tl-[24px] rounded-tr-[24px] px-[20px] pt-[12px]',
  profileHero: 'items-center bg-ku-surface-success rounded-[16px] mt-[14px] px-[16px] py-[18px]',
  profileAvatar: 'items-center rounded-ku-pill h-[64px] justify-center mb-[10px] w-[64px]',
  profileAvatarText: 'text-ku-primary font-ku-bold text-ku-body',
  profileName: 'text-ku-text-strong font-ku-bold text-ku-subtitle text-center',
  profileDetail: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[2px] text-center',
  profileDetails: 'gap-[8px] mt-[12px] pb-[8px]',
  profileDetailRow: 'items-start bg-ku-surface-muted rounded-[14px] flex-row px-[12px] py-[11px]',
  profileDetailCopy: 'flex-1 min-w-0 ml-[10px]',
  profileDetailLabel: 'text-ku-text-muted font-ku-semibold text-ku-caption',
  profileDetailValue: 'text-ku-text-strong font-ku-medium text-ku-body-small mt-[2px]',
  noApplicantsState: 'items-center bg-ku-surface-muted border-ku-border-subtle border-dashed rounded-[16px] justify-center min-h-[210px] mt-[4px] px-[24px] py-[28px]',
  noApplicantsIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[52px] justify-center mb-[12px] w-[52px]',
  noApplicantsTitle: 'text-ku-text-strong font-ku-semibold text-ku-body text-center',
  noApplicantsDescription: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[5px] text-center',
  emptyState: 'items-center bg-ku-surface-muted border-ku-border-subtle border-dashed rounded-[16px] min-h-[214px] justify-center px-[24px] py-[28px]',
  emptyIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[48px] justify-center mb-[10px] w-[48px]',
  emptyTitle: 'text-ku-text-strong font-ku-semibold text-ku-body text-center',
  emptyDescription: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[4px] text-center',
  summaryStrip: 'bg-ku-surface-success border-ku-border-success rounded-[16px] border mt-[10px] px-[10px] py-[10px]',
  summaryMetrics: 'items-stretch flex-row',
  summaryMetric: 'items-center flex-1 flex-row min-w-0 px-[2px]',
  summaryIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[38px] justify-center shrink-0 w-[38px]',
  summaryCopy: 'flex-1 min-w-0 ml-[6px]',
  summaryLabel: 'text-ku-text-secondary font-ku-regular text-[10px] leading-[13px]',
  summaryValue: 'text-ku-text-strong font-ku-bold text-[18px] leading-[22px]',
  summaryDetail: 'text-ku-text-secondary font-ku-regular text-[10px] leading-[13px]',
  summaryDivider: 'bg-ku-border-accent mx-[4px] w-[1px]',
  tipCard: 'items-center bg-ku-surface-accent rounded-[12px] flex-row mt-[10px] px-[12px] py-[10px]',
  tipIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[38px] justify-center shrink-0 w-[38px]',
  tipCopy: 'flex-1 min-w-0 ml-[10px]',
  tipTitle: 'text-ku-text-strong font-ku-semibold text-ku-label',
  tipDescription: 'text-ku-text-secondary font-ku-regular text-ku-caption mt-[2px]',
} as const;

export default styles;
