const styles = {
  safeArea: 'bg-ku-background flex-1',
  content: 'px-[16px] pt-[16px]',
  intro: 'gap-[4px]',
  title: 'text-ku-text-strong font-ku-bold text-ku-title',
  subtitle: 'text-ku-text-secondary font-ku-regular text-ku-body-small',
  roleSwitch: 'bg-ku-surface-muted rounded-[14px] flex-row mt-[20px] p-[4px]',
  roleOption: 'items-center flex-1 justify-center min-h-[48px] px-[8px]',
  roleOptionActive: 'bg-ku-white rounded-[10px] shadow-[0px_2px_5px_rgb(18_32_24_/0.06)]',
  roleOptionText: 'text-ku-text-muted font-ku-semibold text-ku-meta',
  roleOptionTextActive: 'text-ku-primary',
  count: 'bg-ku-surface-accent rounded-ku-pill ml-[6px] min-w-[20px] px-[5px] py-[1px]',
  countActive: 'bg-ku-primary',
  countText: 'text-ku-primary font-ku-bold text-ku-caption',
  countTextActive: 'text-ku-white',
  section: 'mt-[28px]',
  sectionHeader: 'items-center flex-row justify-between mb-[10px]',
  sectionTitle: 'text-ku-text-strong font-ku-bold text-ku-subtitle',
  sectionSummary: 'text-ku-text-muted font-ku-regular text-ku-label',
  cards: 'gap-[8px]',
  card: 'bg-ku-white border-ku-border-accent rounded-[16px] border p-[16px]',
  cardTop: 'items-start flex-row justify-between',
  cardCopy: 'flex-1 min-w-0 mr-[8px]',
  cardTitle: 'text-ku-text-strong font-ku-bold text-ku-body mt-[6px]',
  tag: 'bg-ku-surface-accent rounded-ku-pill self-start min-h-[32px] justify-center px-[8px] py-[4px]',
  tagText: 'text-ku-primary font-ku-semibold text-ku-label',
  status: 'items-center bg-ku-surface-success rounded-ku-pill flex-row min-h-[32px] px-[8px] py-[4px] shrink-0',
  statusText: 'text-ku-success font-ku-semibold text-ku-label ml-[4px]',
  cardMeta: 'items-center border-ku-border-subtle border-t flex-row gap-[12px] justify-between mt-[14px] pt-[12px]',
  metaCopy: 'flex-1 gap-[2px] min-w-0',
  metaText: 'text-ku-text-secondary font-ku-regular text-ku-label',
  action: 'items-center active:opacity-[0.72] bg-ku-primary rounded-ku-pill justify-center min-h-[48px] px-[12px] shrink-0',
  actionText: 'text-ku-white font-ku-semibold text-ku-label text-center',
  completedCard: 'bg-ku-surface active:opacity-[0.72] rounded-[12px] flex-row items-center min-h-[68px] p-[12px]',
  completedIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[36px] justify-center mr-[10px] w-[36px]',
  completedCopy: 'flex-1 min-w-0',
  completedTitle: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  completedMeta: 'text-ku-text-muted font-ku-regular text-ku-label mt-[2px]',
} as const;

export default styles;
