const { withAppBuildGradle } = require('@expo/config-plugins');

const SIGNING_MARKER = '// KUQuest release signing (generated by Expo config plugin)';

const RELEASE_SIGNING_ENVIRONMENT = `${SIGNING_MARKER}
def kuquestReleaseSigning = [
    'KUQUEST_ANDROID_KEYSTORE_FILE': System.getenv('KUQUEST_ANDROID_KEYSTORE_FILE'),
    'KUQUEST_ANDROID_KEYSTORE_PASSWORD': System.getenv('KUQUEST_ANDROID_KEYSTORE_PASSWORD'),
    'KUQUEST_ANDROID_KEY_ALIAS': System.getenv('KUQUEST_ANDROID_KEY_ALIAS'),
    'KUQUEST_ANDROID_KEY_PASSWORD': System.getenv('KUQUEST_ANDROID_KEY_PASSWORD'),
]
def kuquestIsReleaseTask = gradle.startParameter.taskNames.any {
    it.toLowerCase().contains('release')
}
if (kuquestIsReleaseTask) {
    def missingSigningValues = kuquestReleaseSigning.findAll { !it.value }.collect { it.key }
    if (!missingSigningValues.isEmpty()) {
        throw new GradleException("Missing release signing environment: " + missingSigningValues.join(', '))
    }
}
`;

const RELEASE_SIGNING_CONFIG = `
        release {
            if (kuquestReleaseSigning.values().every { it }) {
                storeFile file(kuquestReleaseSigning['KUQUEST_ANDROID_KEYSTORE_FILE'])
                storePassword kuquestReleaseSigning['KUQUEST_ANDROID_KEYSTORE_PASSWORD']
                keyAlias kuquestReleaseSigning['KUQUEST_ANDROID_KEY_ALIAS']
                keyPassword kuquestReleaseSigning['KUQUEST_ANDROID_KEY_PASSWORD']
            }
        }`;

function addReleaseSigning(contents) {
  if (contents.includes(SIGNING_MARKER)) {
    return contents;
  }

  const androidAnchor = '\nandroid {\n';
  const androidIndex = contents.indexOf(androidAnchor);
  if (androidIndex === -1) {
    throw new Error('Unable to add Android signing: android block was not found');
  }

  let nextContents = `${contents.slice(0, androidIndex + 1)}${RELEASE_SIGNING_ENVIRONMENT}\n${contents.slice(androidIndex + 1)}`;
  const signingStart = nextContents.indexOf('    signingConfigs {', androidIndex);
  const signingEndAnchor = '\n    }\n    buildTypes {';
  const signingEnd = nextContents.indexOf(signingEndAnchor, signingStart);
  if (signingStart === -1 || signingEnd === -1) {
    throw new Error('Unable to add Android signing: signingConfigs block was not found');
  }

  nextContents = `${nextContents.slice(0, signingEnd)}${RELEASE_SIGNING_CONFIG}${nextContents.slice(signingEnd)}`;

  const buildTypesStart = nextContents.indexOf('    buildTypes {', signingEnd);
  const releaseStart = nextContents.indexOf('        release {', buildTypesStart);
  const releaseEnd = nextContents.indexOf('\n        }', releaseStart);
  if (buildTypesStart === -1 || releaseStart === -1 || releaseEnd === -1) {
    throw new Error('Unable to add Android signing: release build type was not found');
  }

  const releaseBlock = nextContents.slice(releaseStart, releaseEnd);
  if (!releaseBlock.includes('signingConfig signingConfigs.debug')) {
    throw new Error('Unable to add Android signing: Expo release signing default changed');
  }

  const signedReleaseBlock = releaseBlock.replace(
    'signingConfig signingConfigs.debug',
    'signingConfig signingConfigs.release',
  );
  return `${nextContents.slice(0, releaseStart)}${signedReleaseBlock}${nextContents.slice(releaseEnd)}`;
}

function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error('KUQuest Android signing requires a Groovy app/build.gradle');
    }

    gradleConfig.modResults.contents = addReleaseSigning(gradleConfig.modResults.contents);
    return gradleConfig;
  });
}

module.exports = withAndroidReleaseSigning;
module.exports.addReleaseSigning = addReleaseSigning;
