import { StyleSheet } from "react-native";
import { fontFamily } from "@/theme/typography";

export const walletStyles = StyleSheet.create({
  card: {
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 16,
    padding: 16,
  },
  headerRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  headerLeading: {
    alignItems: "center",
    flexDirection: "row",
    flex: 1,
  },
  iconBox: {
    alignItems: "center",
    borderRadius: 12,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  headerTextWrap: {
    marginLeft: 10,
    flex: 1,
  },
  headerTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 15,
    lineHeight: 20,
  },
  headerSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    lineHeight: 16,
  },
  refreshButton: {
    alignItems: "center",
    borderRadius: 9999,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  balanceSection: {
    borderRadius: 14,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  balanceLabel: {
    fontFamily: fontFamily.medium,
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 2,
  },
  spendingAmount: {
    fontFamily: fontFamily.bold,
    fontSize: 26,
    lineHeight: 32,
  },
  compartmentRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
  },
  compartmentCol: {
    borderRadius: 12,
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  compartmentLabel: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    lineHeight: 14,
    marginBottom: 2,
  },
  compartmentValue: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    lineHeight: 18,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 10,
  },
  actionButtonPrimary: {
    alignItems: "center",
    borderRadius: 12,
    flex: 1,
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  actionButtonSecondary: {
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    height: 48,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  actionButtonLabelPrimary: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    marginLeft: 6,
  },
  actionButtonLabelSecondary: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    marginLeft: 6,
  },
  modalOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.55)",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 24,
  },
  modalCard: {
    borderRadius: 24,
    borderWidth: 1,
    maxHeight: "85%",
    padding: 20,
    width: "100%",
  },
  modalHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  modalTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 18,
    lineHeight: 24,
  },
  closeBtn: {
    alignItems: "center",
    borderRadius: 9999,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  quickAmountRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  quickAmountBtn: {
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  quickAmountLabel: {
    fontFamily: fontFamily.semiBold,
    fontSize: 14,
  },
  input: {
    borderRadius: 12,
    borderWidth: 1,
    fontFamily: fontFamily.semiBold,
    fontSize: 18,
    height: 48,
    marginBottom: 8,
    paddingHorizontal: 14,
  },
  hintText: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    marginBottom: 16,
  },
  qrWrapper: {
    alignItems: "center",
    borderRadius: 16,
    borderWidth: 1,
    marginVertical: 12,
    padding: 16,
  },
  qrImage: {
    borderRadius: 8,
    height: 220,
    width: 220,
  },
  noticeBanner: {
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 14,
    padding: 12,
  },
  noticeTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 13,
    marginBottom: 4,
  },
  noticeBody: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    lineHeight: 17,
  },
  txItem: {
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    padding: 12,
  },
  txLeading: {
    flex: 1,
    marginRight: 8,
  },
  txTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: 13,
    lineHeight: 18,
  },
  txDate: {
    fontFamily: fontFamily.regular,
    fontSize: 11,
    marginTop: 2,
  },
  txTrailing: {
    alignItems: "flex-end",
  },
  txAmount: {
    fontFamily: fontFamily.bold,
    fontSize: 14,
  },
  txBadge: {
    borderRadius: 6,
    marginTop: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  txBadgeText: {
    fontFamily: fontFamily.semiBold,
    fontSize: 10,
  },
});
