export const walletStyles = {
  card: "rounded-[20px] border border-ku-border-subtle mb-ku-md p-ku-md",
  headerRow: "items-center flex-row justify-between mb-ku-sm",
  headerLeading: "items-center flex-1 flex-row",
  iconBox: "items-center justify-center h-[38px] w-[38px] rounded-[12px]",
  headerTextWrap: "ml-ku-10 flex-1",
  headerTitle: "font-ku-bold text-ku-control leading-[20px]",
  headerSubtitle: "font-ku-regular text-ku-label leading-[16px]",
  refreshButton:
    "items-center justify-center h-[48px] w-[48px] rounded-ku-pill",
  balanceSection: "mb-ku-sm rounded-[14px] px-ku-14 py-ku-12",
  balanceLabel: "mb-ku-2 font-ku-medium text-ku-label leading-[16px]",
  spendingAmount: "font-ku-bold text-[26px] leading-[32px]",
  compartmentRow: "mb-ku-14 flex-row gap-ku-sm",
  compartmentCol: "flex-1 rounded-[12px] px-ku-10 py-ku-sm",
  compartmentLabel: "mb-ku-2 font-ku-regular text-ku-caption leading-[14px]",
  compartmentValue: "font-ku-semibold text-ku-meta leading-[18px]",
  actionsRow: "flex-row gap-ku-10",
  actionButtonPrimary:
    "h-[48px] flex-1 flex-row items-center justify-center rounded-[12px] px-ku-12",
  actionButtonSecondary:
    "h-[48px] flex-1 flex-row items-center justify-center rounded-[12px] border px-ku-12",
  actionButtonLabelPrimary: "ml-ku-6 font-ku-semibold text-ku-meta",
  actionButtonLabelSecondary: "ml-ku-6 font-ku-semibold text-ku-meta",
  modalOverlay:
    "flex-1 items-center justify-center bg-ku-overlay px-ku-md py-ku-lg",
  modalCard: "w-full max-h-[85%] rounded-[24px] border p-ku-md",
  modalHeader: "items-center flex-row justify-between mb-ku-md",
  modalTitle: "font-ku-bold text-ku-subtitle leading-[24px]",
  closeBtn: "items-center justify-center h-[38px] w-[38px] rounded-ku-pill",
  quickAmountRow: "mb-ku-md flex-row flex-wrap gap-ku-sm",
  quickAmountBtn: "rounded-[12px] border px-ku-14 py-ku-sm",
  quickAmountLabel: "font-ku-semibold text-ku-body-small",
  input:
    "h-[48px] mb-ku-sm rounded-[12px] border px-ku-14 font-ku-semibold text-ku-subtitle",
  hintText: "mb-ku-md font-ku-regular text-ku-label",
  qrWrapper: "my-ku-12 items-center rounded-[16px] border p-ku-md",
  qrImage: "h-[220px] w-[220px] rounded-[8px]",
  noticeBanner: "mb-ku-14 rounded-[14px] border p-ku-12",
  noticeTitle: "mb-ku-xs font-ku-bold text-ku-meta",
  noticeBody: "font-ku-regular text-ku-label leading-[17px]",
  txItem: "mb-ku-sm flex-row justify-between rounded-[14px] border p-ku-12",
  txLeading: "mr-ku-sm flex-1",
  txTitle: "font-ku-semibold text-ku-meta leading-[18px]",
  txDate: "mt-ku-2 font-ku-regular text-ku-caption",
  txTrailing: "items-end",
  txAmount: "font-ku-bold text-ku-body-small",
  txBadge: "mt-ku-xs rounded-[6px] px-ku-6 py-ku-2",
  txBadgeText: "font-ku-semibold text-ku-nav",
} as const;
