export const walletStyles = {
  card: "rounded-[20px] border border-ku-border-subtle mb-ku-md p-ku-md",
  headerRow: "items-center flex-row justify-between mb-[12px]",
  headerLeading: "items-center flex-1 flex-row",
  iconBox: "items-center justify-center h-[38px] w-[38px] rounded-[12px]",
  headerTextWrap: "ml-[10px] flex-1",
  headerTitle: "font-ku-bold text-ku-control leading-[20px]",
  headerSubtitle: "font-ku-regular text-ku-label leading-[16px]",
  refreshButton:
    "items-center justify-center h-[48px] w-[48px] rounded-ku-pill",
  balanceSection: "mb-[12px] rounded-[14px] px-[14px] py-[12px]",
  balanceLabel: "mb-[2px] font-ku-medium text-ku-label leading-[16px]",
  spendingAmount: "font-ku-bold text-[26px] leading-[32px]",
  compartmentRow: "mb-[14px] flex-row gap-ku-sm",
  compartmentCol: "flex-1 rounded-[12px] px-[10px] py-[8px]",
  compartmentLabel: "mb-[2px] font-ku-regular text-ku-caption leading-[14px]",
  compartmentValue: "font-ku-semibold text-ku-meta leading-[18px]",
  actionsRow: "flex-row gap-[10px]",
  actionButtonPrimary:
    "h-[48px] flex-1 flex-row items-center justify-center rounded-[12px] px-[12px]",
  actionButtonSecondary:
    "h-[48px] flex-1 flex-row items-center justify-center rounded-[12px] border px-[12px]",
  actionButtonLabelPrimary: "ml-[6px] font-ku-semibold text-ku-meta",
  actionButtonLabelSecondary: "ml-[6px] font-ku-semibold text-ku-meta",
  modalOverlay:
    "flex-1 items-center justify-center bg-ku-overlay px-ku-md py-ku-lg",
  modalCard: "w-full max-h-[85%] rounded-[24px] border p-ku-md",
  modalHeader: "items-center flex-row justify-between mb-ku-md",
  modalTitle: "font-ku-bold text-ku-subtitle leading-[24px]",
  closeBtn: "items-center justify-center h-[38px] w-[38px] rounded-ku-pill",
  quickAmountRow: "mb-ku-md flex-row flex-wrap gap-ku-sm",
  quickAmountBtn: "rounded-[12px] border px-[14px] py-ku-sm",
  quickAmountLabel: "font-ku-semibold text-ku-body-small",
  input:
    "h-[48px] mb-ku-sm rounded-[12px] border px-[14px] font-ku-semibold text-ku-subtitle",
  hintText: "mb-ku-md font-ku-regular text-ku-label",
  qrWrapper: "my-[12px] items-center rounded-[16px] border p-ku-md",
  qrImage: "h-[220px] w-[220px] rounded-[8px]",
  noticeBanner: "mb-[14px] rounded-[14px] border p-[12px]",
  noticeTitle: "mb-[4px] font-ku-bold text-ku-meta",
  noticeBody: "font-ku-regular text-ku-label leading-[17px]",
  txItem: "mb-ku-sm flex-row justify-between rounded-[14px] border p-[12px]",
  txLeading: "mr-ku-sm flex-1",
  txTitle: "font-ku-semibold text-ku-meta leading-[18px]",
  txDate: "mt-[2px] font-ku-regular text-ku-caption",
  txTrailing: "items-end",
  txAmount: "font-ku-bold text-ku-body-small",
  txBadge: "mt-ku-xs rounded-[6px] px-[6px] py-[2px]",
  txBadgeText: "font-ku-semibold text-ku-nav",
} as const;
