import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';
import { spacing } from '@/theme/spacing';
import { fontFamily } from '@/theme/typography';
const styles = StyleSheet.create({
  loadingText: {
    fontFamily: fontFamily.regular,
    color: colors.primary,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: 136,
    alignItems: 'center',
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
  },
  langToggle: {
    alignSelf: 'flex-end',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: colors.surfaceAccent,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    marginBottom: spacing.md,
  },
  langToggleText: {
    fontFamily: fontFamily.bold,
    fontSize: 12,
    color: colors.primary,
  },
  headerSection: {
    alignItems: 'flex-start',
    marginBottom: 20,
    width: '100%',
  },
  title: {
    fontFamily: fontFamily.bold,
    fontSize: 24,
    color: colors.primary,
    letterSpacing: -0.5,
  },
  stepTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 18,
    color: colors.textStrong,
    marginTop: 12,
  },
  stepIndicator: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textMuted,
    marginTop: 2,
  },
  progressContainer: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 16,
    width: '100%',
  },
  progressBarActive: {
    height: 6,
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: 4,
  },
  progressBarInactive: {
    height: 6,
    flex: 1,
    backgroundColor: colors.borderSubtle,
    borderRadius: 4,
  },
  avatarPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.surfacePlaceholder,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    borderWidth: 1,
    borderColor: colors.borderMuted,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 40,
  },
  editBadge: {
    position: 'absolute',
    right: -4,
    bottom: -4,
    backgroundColor: colors.successBright,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.white,
    elevation: 2, // shadow for Android
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  formSection: {
    width: '100%',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  termsLabel: {
    fontFamily: fontFamily.bold,
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 6,
  },
  termsBox: {
    backgroundColor: colors.surfaceSubtle,
    borderWidth: 1,
    borderColor: colors.borderMuted,
    borderRadius: 8,
    marginBottom: 16,
    height: 120,
  },
  termsBoxContent: {
    padding: 12,
    paddingBottom: 24,
  },
  termsTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 12,
    color: colors.textStrong,
    marginBottom: 4,
  },
  termsText: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.textMuted,
    lineHeight: 18,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 16,
  },
  submitErrorCard: {
    backgroundColor: colors.surfaceDanger,
    borderColor: colors.borderDanger,
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 16,
  },
  submitErrorText: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.dangerDark,
    flex: 1,
  },
  halfBtn: {
    flex: 1,
  },
  step2Card: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    // Add shadow
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  step2CardTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 18,
    color: colors.primary,
    marginBottom: 8,
  },
  step2CardSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.textMuted,
    lineHeight: 18,
  },
  step2Intro: {
    marginBottom: 20,
  },
  skipButtonContainer: {
    alignItems: 'center',
    marginBottom: 8,
  },
  skipButton: {
    minHeight: 44,
    minWidth: 44,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  skipButtonText: {
    fontFamily: fontFamily.bold,
    fontSize: 14,
    color: colors.textMuted,
    textDecorationLine: 'underline',
  },
  step3Section: {
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderMuted,
    paddingBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 32,
    marginBottom: 10,
  },
  badgeSuccess: {
    backgroundColor: colors.successLight,
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  sectionTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 18,
    color: colors.textStrong,
  },
  sectionTitleNormal: {
    fontFamily: fontFamily.bold,
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  sectionDesc: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.textMuted,
    marginBottom: 16,
    lineHeight: 18,
  },
  itemCard: {
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSubtle,
    paddingBottom: 16,
    marginBottom: 16,
  },
  itemCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  removeButton: {
    minHeight: 48,
    minWidth: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemLabel: {
    fontFamily: fontFamily.bold,
    fontSize: 10,
    color: colors.textSecondary,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  importLinkBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.textFaint,
    borderStyle: 'dashed',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 16,
  },
  importLinkInput: {
    flex: 1,
    marginLeft: 8,
    fontFamily: fontFamily.bold,
    fontSize: 14,
    color: colors.textSecondary,
    padding: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
  },
  addMoreBtn: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 24,
    paddingVertical: 10,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  addMoreBtnText: {
    fontFamily: fontFamily.bold,
    fontSize: 14,
    color: colors.primary,
  },
  dateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 12,
  },
  dateInputWrapper: {
    flex: 1,
  },
  dateInputLabel: {
    fontFamily: fontFamily.bold,
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 6,
  },
  dateInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.borderMuted,
    borderRadius: 10,
    backgroundColor: colors.surfaceSubtle,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 48,
  },
  dateInputError: {
    borderColor: colors.danger,
    borderWidth: 1,
  },
  fieldErrorText: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.danger,
    marginTop: 4,
  },
  dateInputTextActive: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textStrong,
  },
  dateInputTextPlaceholder: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textFaint,
  },
  imageUploadBox: {
    borderWidth: 1,
    borderColor: colors.textFaint,
    borderStyle: 'dashed',
    borderRadius: 12,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    backgroundColor: colors.surfaceSubtle,
    overflow: 'hidden',
  },
  certificateImageBox: {
    height: 104,
  },
  imagePlaceholderContent: {
    alignItems: 'center',
  },
  addImgText: {
    fontFamily: fontFamily.bold,
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 4,
  },
  uploadedImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  loadErrorCard: {
    margin: spacing.lg,
    padding: spacing.lg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderDanger,
    backgroundColor: colors.surfaceDanger,
    alignItems: 'center',
    gap: spacing.md,
  },
  policySummary: {
    backgroundColor: colors.surfaceAccent,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  policySummaryTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 12,
    color: colors.textStrong,
    marginBottom: 4,
  },
  policySummaryText: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  policyReadAction: {
    minHeight: 48,
    justifyContent: 'center',
    marginTop: 8,
  },
  policyReadActionText: {
    fontFamily: fontFamily.bold,
    fontSize: 14,
    color: colors.primary,
    textDecorationLine: 'underline',
  },
  actionBar: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.borderSubtle,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 16,
  },
  actionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    width: '100%',
  },
  actionButton: {
    flex: 1,
    minWidth: 0,
  },
  savingStatus: {
    fontFamily: fontFamily.regular,
    fontSize: 12,
    color: colors.primary,
    textAlign: 'center',
    marginBottom: 8,
  },
  emptySection: {
    backgroundColor: colors.surfaceAccent,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    borderRadius: 12,
    minHeight: 64,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  emptySectionText: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  policyModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  policyModalContent: {
    height: '88%',
    maxHeight: '88%',
    backgroundColor: colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
  },
  policyModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSubtle,
  },
  policyModalTitle: {
    fontFamily: fontFamily.bold,
    fontSize: 18,
    color: colors.textStrong,
  },
  policyModalClose: {
    minHeight: 48,
    minWidth: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  policyModalScroll: {
    flex: 1,
  },
  policyModalScrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    paddingBottom: 28,
  },
  policyModalText: {
    fontFamily: fontFamily.regular,
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  policyModalFooter: {
    borderTopWidth: 1,
    borderTopColor: colors.borderSubtle,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
  },
});

export default styles;
