const styles = {
  loadingState: 'flex-row items-center gap-[10px] px-[24px] py-[16px] rounded-[16px] bg-ku-surface-accent',
  loadingText: 'font-ku-regular text-ku-primary',
  safeArea: 'flex-1 bg-ku-background',
  scrollContent: 'px-[20px] pt-[20px] pb-[128px] items-center w-full max-w-[720px] self-center',
  headerSection: 'items-start mb-[24px] w-full',
  title: 'font-ku-bold text-ku-title-large text-ku-primary -tracking-[0.5px]',
  stepTitle: 'font-ku-bold text-ku-title-small text-ku-text-strong mt-[12px]',
  stepIndicator: 'font-ku-regular text-ku-body-small text-ku-text-muted mt-[2px]',
  progressContainer: 'flex-row gap-[6px] mt-[16px] w-full',
  progressBarActive: 'h-[6px] flex-1 bg-ku-primary rounded-[4px]',
  progressBarInactive: 'h-[6px] flex-1 bg-ku-border-subtle rounded-[4px]',
  avatarPlaceholder: 'w-[80px] h-[80px] rounded-[40px] bg-ku-surface-placeholder justify-center items-center relative border border-ku-border-muted',
  avatarImage: 'w-full h-full rounded-[40px]',
  editBadge: 'shadow-[0px_1px_1.5px_rgb(18_32_24_/0.2)] absolute -right-[4px] -bottom-[4px] bg-ku-success-bright w-[28px] h-[28px] rounded-[14px] justify-center items-center border-2 border-ku-white',
  formSection: 'w-full',
  termsLabel: 'font-ku-bold text-ku-label text-ku-text-secondary mb-[6px]',
  termsBox: 'bg-ku-surface-subtle border border-ku-border-muted rounded-[12px] mb-[16px] h-[168px]',
  termsBoxContent: 'p-[16px] pb-[24px]',
  termsTitle: 'font-ku-bold text-ku-label text-ku-text-strong mb-[4px]',
  termsText: 'font-ku-regular text-ku-body-small text-ku-text-muted',
  actionBar: 'items-center bg-ku-surface border-t border-t-ku-border-subtle flex-row gap-[10px] px-[20px] pt-[10px] pb-[16px]',
  actionButton: 'flex-1 min-w-0',
  submitErrorCard: 'bg-ku-surface-danger border-ku-border-danger border rounded-[12px] p-[12px] flex-row items-center gap-[8px] mt-[16px]',
  submitErrorText: 'font-ku-regular text-ku-label text-ku-danger-dark flex-1',
  halfBtn: 'flex-1',
  step2Card: 'shadow-[0px_2px_5px_rgb(18_32_24_/0.06)] bg-ku-card border border-ku-border-subtle rounded-[16px] p-[20px] mb-[16px]',
  step2CardTitle: 'font-ku-bold text-ku-subtitle text-ku-primary mb-[8px]',
  step2CardSubtitle: 'font-ku-regular text-ku-label text-ku-text-muted mb-[24px]',
  skipButtonContainer: 'items-center mb-[8px]',
  skipButton: 'min-h-[48px] min-w-[48px] py-[8px] px-[16px]',
  skipButtonText: 'font-ku-bold text-ku-body-small text-ku-text-muted underline',
  step3Section: 'mb-[28px]',
  sectionHeader: 'flex-row items-center mb-[10px] min-h-[32px]',
  badgeSuccess: 'bg-ku-primary w-[28px] h-[28px] rounded-[14px] justify-center items-center mr-[8px]',
  sectionTitle: 'font-ku-bold text-ku-subtitle text-ku-text-strong',
  sectionTitleNormal: 'font-ku-bold text-ku-subtitle text-ku-text-strong mb-[12px]',
  sectionDesc: 'font-ku-regular text-ku-label text-ku-text-muted mb-[16px]',
  itemCard: 'shadow-[0px_2px_5px_rgb(18_32_24_/0.06)] bg-ku-card border border-ku-border-subtle rounded-[16px] p-[16px] mb-[16px]',
  itemCardHeader: 'flex-row items-center justify-between',
  removeButton: 'min-h-[48px] min-w-[48px] items-center justify-center',
  itemLabel: 'font-ku-bold text-ku-label text-ku-text-muted mb-[8px] uppercase',
  emptySection: 'bg-ku-surface-accent border border-ku-border-accent rounded-[12px] min-h-[64px] px-[16px] py-[12px] items-center justify-center mb-[12px]',
  emptySectionText: 'font-ku-regular text-ku-body-small text-ku-text-secondary text-center',
  addMoreBtn: 'border border-ku-primary rounded-[24px] py-[10px] min-h-[48px] items-center justify-center mt-[8px]',
  addMoreBtnText: 'font-ku-bold text-ku-body-small text-ku-primary',
  dateInputWrapper: 'flex-1',
  dateInputLabel: 'font-ku-bold text-ku-label text-ku-text-secondary mb-[6px]',
  dateInputBox: 'flex-row items-center justify-between border border-ku-border-muted rounded-[10px] bg-ku-surface-subtle px-[12px] py-[10px] min-h-[48px]',
  dateInputError: 'border-ku-danger border',
  fieldErrorText: 'font-ku-regular text-ku-label text-ku-danger mt-[4px]',
  dateInputTextActive: 'font-ku-regular text-ku-body-small text-ku-text-strong',
  dateInputTextPlaceholder: 'font-ku-regular text-ku-body-small text-ku-text-faint',
  imageUploadBox: 'border border-ku-border rounded-[12px] border-dashed h-[120px] justify-center items-center mb-[16px] bg-ku-surface-subtle overflow-hidden',
  certificateImageBox: 'h-[104px]',
  imagePlaceholderContent: 'items-center',
  addImgText: 'font-ku-bold text-ku-label text-ku-text-muted mt-[4px]',
  uploadedImage: 'w-full h-full object-cover',
  loadErrorCard: 'm-[20px] p-[24px] rounded-[16px] border border-ku-border-danger bg-ku-surface-danger items-center gap-[16px]',
} as const;

export default styles;
