import { StyleSheet } from 'react-native';
import { colors } from '@/theme/colors';
const styles = StyleSheet.create({
  loadingText: {
    fontFamily: 'NotoSansThai_400Regular',
    color: colors.primary,
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F2F0', // Slightly warm grey/pinkish background from the mockup
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingVertical: 24,
    alignItems: 'center',
    backgroundColor: colors.background,
    margin: 16,
    borderRadius: 16,
    // Add shadow
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  langToggle: {
    alignSelf: 'flex-end',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: '#F0F4F1',
    borderWidth: 1,
    borderColor: '#D0E3D5',
    marginBottom: 16,
  },
  langToggleText: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 12,
    color: colors.primary,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 32,
    width: '100%',
  },
  title: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 24,
    color: colors.primary,
    letterSpacing: -0.5,
  },
  stepTitle: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 18,
    color: '#111111',
    marginTop: 16,
  },
  stepIndicator: {
    fontFamily: 'NotoSansThai',
    fontSize: 14,
    color: '#666666',
    marginTop: 4,
  },
  progressContainer: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
    marginBottom: 24,
  },
  progressBarActive: {
    height: 4,
    width: 40,
    backgroundColor: '#014925',
    borderRadius: 2,
  },
  progressBarInactive: {
    height: 4,
    width: 40,
    backgroundColor: '#E0E0E0',
    borderRadius: 2,
  },
  avatarPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#E8E8E8',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#D0D0D0',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 40,
  },
  editBadge: {
    position: 'absolute',
    right: -4,
    bottom: -4,
    backgroundColor: '#4CAF50', // Brighter green to indicate editability
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    elevation: 2, // shadow for Android
    shadowColor: '#000', // shadow for iOS
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  formSection: {
    width: '100%',
  },
  termsLabel: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 12,
    color: '#333333',
    marginBottom: 6,
  },
  termsBox: {
    backgroundColor: '#F9F9F9',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    marginBottom: 16,
    height: 120,
  },
  termsBoxContent: {
    padding: 12,
    paddingBottom: 24,
  },
  termsTitle: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 12,
    color: '#111111',
    marginBottom: 4,
  },
  termsText: {
    fontFamily: 'NotoSansThai',
    fontSize: 12,
    color: '#666666',
    lineHeight: 18,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 16,
  },
  submitErrorCard: {
    backgroundColor: '#FDECEF',
    borderColor: '#F5C2C7',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 16,
  },
  submitErrorText: {
    fontFamily: 'NotoSansThai',
    fontSize: 12,
    color: '#842029',
    flex: 1,
  },
  halfBtn: {
    flex: 1,
  },
  step2Card: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EFEFEF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    // Add shadow
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  step2CardTitle: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 18,
    color: '#014925',
    marginBottom: 8,
  },
  step2CardSubtitle: {
    fontFamily: 'NotoSansThai',
    fontSize: 12,
    color: '#666666',
    marginBottom: 24,
    lineHeight: 18,
  },
  skipButtonContainer: {
    alignItems: 'center',
    marginBottom: 8,
  },
  skipButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  skipButtonText: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 14,
    color: '#666666',
    textDecorationLine: 'underline',
  },
  step3Section: {
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    paddingBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  badgeSuccess: {
    backgroundColor: '#95E3A0',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  sectionTitle: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 18,
    color: '#111',
  },
  sectionTitleNormal: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 12,
    color: '#333',
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  sectionDesc: {
    fontFamily: 'NotoSansThai',
    fontSize: 12,
    color: '#666',
    marginBottom: 16,
    lineHeight: 18,
  },
  itemCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EFEFEF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  itemLabel: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 10,
    color: '#333',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  importLinkBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#999',
    borderStyle: 'dashed',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 16,
  },
  importLinkInput: {
    flex: 1,
    marginLeft: 8,
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 14,
    color: '#333',
    padding: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
  },
  addMoreBtn: {
    borderWidth: 1,
    borderColor: '#014925',
    borderRadius: 24,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  addMoreBtnText: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 14,
    color: '#014925',
  },
  dateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 12,
  },
  dateInputWrapper: {
    flex: 1,
  },
  dateInputLabel: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 12,
    color: '#333',
    marginBottom: 6,
  },
  dateInputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    backgroundColor: '#F9F9F9',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  fieldErrorText: {
    fontFamily: 'NotoSansThai',
    fontSize: 12,
    color: '#D32F2F',
    marginTop: 4,
  },
  dateInputTextActive: {
    fontFamily: 'NotoSansThai',
    fontSize: 14,
    color: '#111',
  },
  dateInputTextPlaceholder: {
    fontFamily: 'NotoSansThai',
    fontSize: 14,
    color: '#999',
  },
  imageUploadBox: {
    borderWidth: 1,
    borderColor: '#999',
    borderStyle: 'dashed',
    borderRadius: 8,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    backgroundColor: '#F9F9F9',
    overflow: 'hidden',
  },
  imagePlaceholderContent: {
    alignItems: 'center',
  },
  addImgText: {
    fontFamily: 'NotoSansThai-Bold',
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  uploadedImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
});

export default styles;
