const styles = {
  container: 'mb-[16px] w-full',
  label: 'font-ku-bold text-[12px] text-ku-text-secondary mb-[6px]',
  selectBox: 'flex-row justify-between items-center border border-ku-border-muted rounded-[8px] px-[12px] py-[10px] bg-ku-white min-h-[44px]',
  selectBoxError: 'border-ku-danger',
  selectBoxSuccess: 'border-ku-success',
  selectBoxDisabled: 'bg-ku-surface-muted opacity-[0.6]',
  selectText: 'font-ku-regular text-[14px] text-ku-text-strong',
  placeholderText: 'text-ku-text-faint',
  errorText: 'font-ku-regular text-[12px] text-ku-danger mt-[4px]',
  helperSlot: 'min-h-[18px] mt-[4px]',
  modalOverlay: 'flex-1 justify-end bg-ku-overlay',
  keyboardAvoidingView: 'flex-1 justify-end w-full',
  modalDismissArea: 'flex-1 justify-end',
  modalContent: 'bg-ku-white rounded-tl-[16px] rounded-tr-[16px] max-h-[80%]',
  modalHeader: 'flex-row justify-between items-center p-[16px] border-b border-b-ku-border-muted',
  modalTitle: 'font-ku-bold text-[16px] text-ku-text-strong',
  closeButton: 'items-center justify-center min-h-[44px] min-w-[44px]',
  clearButton: 'items-center justify-center min-h-[44px] min-w-[44px]',
  searchContainer: 'flex-row items-center mx-[16px] my-[8px] px-[8px] border border-ku-border-muted rounded-[8px] bg-ku-surface-subtle min-h-[44px]',
  searchInput: 'flex-1 px-[8px] py-[8px] font-ku-regular text-[14px] text-ku-text-strong',
  optionItem: 'flex-row justify-between items-center py-[14px] px-[16px] border-b border-b-ku-surface-muted',
  optionText: 'font-ku-regular text-[16px] text-ku-text-secondary',
  optionTextSelected: 'font-ku-bold text-ku-primary',
  emptyText: 'p-[24px] text-center font-ku-regular text-[14px] text-ku-text-muted',
} as const;

export default styles;
