const styles = {
  container: 'mb-[16px] w-full',
  label: 'font-ku-bold text-ku-label text-ku-text-secondary mb-[6px]',
  selectBox: 'flex-row justify-between items-center border border-ku-border-muted rounded-[10px] px-[12px] py-[10px] bg-ku-card min-h-[48px]',
  selectBoxError: 'border-ku-danger',
  selectBoxSuccess: 'border-ku-success',
  selectBoxDisabled: 'bg-ku-surface-muted opacity-[0.6]',
  selectText: 'font-ku-regular text-ku-body-small text-ku-text-strong',
  placeholderText: 'text-ku-text-faint',
  errorText: 'font-ku-regular text-ku-label text-ku-danger mt-[4px]',
  helperSlot: 'min-h-[18px] mt-[4px]',
  modalOverlay: 'flex-1 justify-end bg-ku-overlay',
  keyboardAvoidingView: 'flex-1 justify-end w-full',
  modalDismissArea: 'flex-1 justify-end',
  modalContent: 'bg-ku-card rounded-tl-[24px] rounded-tr-[24px] max-h-[82%] overflow-hidden',
  modalHandle: 'self-center w-[36px] h-[4px] rounded-[2px] bg-ku-border-muted mt-[10px]',
  modalHeader: 'flex-row justify-between items-center px-[20px] pt-[20px] pb-[12px] border-b border-b-ku-border-muted',
  modalTitle: 'font-ku-bold text-ku-body text-ku-text-strong',
  closeButton: 'items-center justify-center min-h-[48px] min-w-[48px]',
  clearButton: 'items-center justify-center min-h-[48px] min-w-[48px]',
  searchContainer: 'flex-row items-center mx-[20px] my-[12px] px-[8px] border border-ku-border-muted rounded-[10px] bg-ku-surface-subtle min-h-[48px]',
  searchInput: 'flex-1 px-[8px] py-[8px] font-ku-regular text-ku-body-small text-ku-text-strong',
  optionItem: 'flex-row justify-between items-center min-h-[52px] py-[14px] px-[20px] border-b border-b-ku-surface-muted',
  optionText: 'font-ku-regular text-ku-body text-ku-text-secondary',
  optionTextSelected: 'font-ku-bold text-ku-primary',
  emptyText: 'p-[24px] text-center font-ku-regular text-ku-body-small text-ku-text-muted',
} as const;

export default styles;
