const styles = {
  safeArea: 'flex-1 bg-ku-surface',
  screen: 'flex-1',
  scrollContent: 'px-ku-lg pt-ku-md pb-[120px] gap-ku-md self-center w-full max-w-[720px]',
  header: 'flex-row items-center justify-between mb-ku-sm',
  headerTitle: 'font-ku-bold text-ku-title text-ku-text-strong',
  backButton: 'min-h-[48px] min-w-[48px] items-center justify-center',
  headerAction: 'min-h-[48px] min-w-[48px] items-center justify-center',
  intro: 'font-ku-regular text-ku-text-secondary text-ku-body-small mb-ku-sm',
  sectionList: 'gap-ku-sm',
  sectionRow: 'flex-row items-center bg-ku-card border border-ku-border-subtle rounded-ku-card px-ku-md min-h-[76px]',
  sectionRowContent: 'flex-1 py-ku-md',
  sectionRowTitle: 'font-ku-semibold text-ku-text-strong text-ku-body',
  sectionRowSummary: 'font-ku-regular text-ku-text-muted text-ku-meta mt-[2px]',
  chevron: 'ml-ku-sm',
  statusCard: 'bg-ku-surface-danger border border-ku-border-danger rounded-ku-field p-ku-md gap-ku-sm',
  statusText: 'font-ku-regular text-ku-danger-dark text-ku-body-small flex-1',
  retryButton: 'min-h-[48px] self-start px-ku-md items-center justify-center rounded-ku-pill bg-ku-primary',
  retryButtonText: 'font-ku-semibold text-ku-white',
  emptyState: 'bg-ku-surface-subtle border border-ku-border-subtle rounded-ku-card p-ku-lg items-center gap-ku-sm',
  emptyText: 'font-ku-regular text-ku-text-secondary text-ku-body-small text-center',
  addButton: 'mt-ku-sm',
  addButtonText: 'font-ku-semibold text-ku-primary text-ku-body',
  itemRow: 'flex-row items-center bg-ku-card border border-ku-border-subtle rounded-ku-card p-ku-md gap-ku-md',
  itemRowContent: 'flex-1 gap-[3px]',
  itemTitle: 'font-ku-semibold text-ku-text-strong text-ku-body',
  itemMeta: 'font-ku-regular text-ku-text-secondary text-ku-body-small',
  itemDescription: 'font-ku-regular text-ku-text-muted text-ku-meta',
  itemImage: 'w-[64px] h-[64px] rounded-ku-field bg-ku-surface-image',
  itemImageFallback: 'w-[64px] h-[64px] rounded-ku-field bg-ku-surface-placeholder items-center justify-center',
  itemImageFallbackText: 'font-ku-regular text-ku-text-faint text-ku-nav text-center px-[4px]',
  formScroll: 'flex-1',
  formContent: 'px-ku-lg pt-ku-md pb-[132px] gap-ku-md self-center w-full max-w-[720px]',
  formGroup: 'bg-ku-card border border-ku-border-subtle rounded-ku-card p-ku-md gap-ku-sm',
  formGroupTitle: 'font-ku-bold text-ku-text-strong text-ku-subtitle mb-[4px]',
  formGroupHint: 'font-ku-regular text-ku-text-secondary text-ku-body-small',
  avatarPicker: 'items-center gap-ku-sm py-ku-sm',
  avatar: 'w-[96px] h-[96px] rounded-[48px] bg-ku-surface-image border border-ku-border-accent',
  avatarFallback: 'w-[96px] h-[96px] rounded-[48px] bg-ku-surface-accent border border-ku-border-accent items-center justify-center',
  avatarInitials: 'font-ku-bold text-ku-title-large text-ku-primary',
  avatarButton: 'min-h-[48px] px-ku-md items-center justify-center rounded-ku-pill border border-ku-primary',
  avatarButtonText: 'font-ku-semibold text-ku-primary text-ku-body-small',
  avatarHelp: 'font-ku-regular text-ku-text-muted text-ku-label text-center',
  avatarError: 'font-ku-regular text-ku-danger-dark text-ku-label text-center',
  imagePicker: 'w-full border border-ku-border-muted border-dashed rounded-ku-field items-center justify-center overflow-hidden bg-ku-surface-subtle',
  imagePreview: 'h-full w-full',
  imagePickerText: 'font-ku-semibold text-ku-text-muted text-ku-meta',
  dateRow: 'flex-row gap-ku-md',
  dateField: 'flex-1',
  dateButton: 'min-h-[48px] flex-row items-center justify-between border border-ku-border-muted rounded-ku-field bg-ku-card px-ku-md',
  dateText: 'font-ku-regular text-ku-text-strong text-ku-body-small',
  datePlaceholder: 'font-ku-regular text-ku-text-faint text-ku-body-small',
  clearDate: 'min-h-[48px] items-center justify-center px-[4px]',
  clearDateText: 'font-ku-semibold text-ku-primary text-ku-label',
  errorCard: 'flex-row items-center bg-ku-surface-danger border border-ku-border-danger rounded-ku-field p-ku-md gap-ku-sm',
  errorText: 'font-ku-regular text-ku-danger-dark text-ku-meta flex-1',
  saveBar: 'absolute bottom-0 left-0 right-0 bg-ku-surface-nav-translucent border-t border-ku-border-nav px-ku-lg pt-ku-sm pb-0',
  saveBarInner: 'self-center w-full max-w-[720px]',
} as const;

export default styles;
