const styles = {
  safeArea: 'flex-1 bg-ku-surface',
  screen: 'flex-1',
  scrollContent: 'px-ku-lg pt-ku-md pb-[120px] gap-ku-md self-center w-full max-w-[720px]',
  header: 'flex-row items-center justify-between mb-ku-sm',
  headerTitle: 'font-ku-bold text-[24px] leading-[30px] text-ku-text-strong',
  backButton: 'min-h-[48px] min-w-[48px] items-center justify-center',
  headerAction: 'min-h-[48px] min-w-[48px] items-center justify-center',
  intro: 'font-ku-regular text-ku-text-secondary text-[14px] leading-[21px] mb-ku-sm',
  sectionList: 'gap-ku-sm',
  sectionRow: 'flex-row items-center bg-ku-card border border-ku-border-subtle rounded-ku-card px-ku-md min-h-[76px]',
  sectionRowContent: 'flex-1 py-ku-md',
  sectionRowTitle: 'font-ku-semibold text-ku-text-strong text-[16px] leading-[22px]',
  sectionRowSummary: 'font-ku-regular text-ku-text-muted text-[13px] leading-[19px] mt-[2px]',
  chevron: 'ml-ku-sm',
  statusCard: 'bg-ku-surface-danger border border-ku-border-danger rounded-ku-field p-ku-md gap-ku-sm',
  statusText: 'font-ku-regular text-ku-danger-dark text-[14px] leading-[21px] flex-1',
  retryButton: 'min-h-[48px] self-start px-ku-md items-center justify-center rounded-ku-pill bg-ku-primary',
  retryButtonText: 'font-ku-semibold text-ku-white',
  emptyState: 'bg-ku-surface-subtle border border-ku-border-subtle rounded-ku-card p-ku-lg items-center gap-ku-sm',
  emptyText: 'font-ku-regular text-ku-text-secondary text-[14px] text-center leading-[21px]',
  addButton: 'min-h-[48px] border-2 border-ku-primary rounded-ku-pill px-ku-md items-center justify-center mt-ku-sm',
  addButtonText: 'font-ku-semibold text-ku-primary text-[15px]',
  itemRow: 'flex-row items-center bg-ku-card border border-ku-border-subtle rounded-ku-card p-ku-md gap-ku-md',
  itemRowContent: 'flex-1 gap-[3px]',
  itemTitle: 'font-ku-semibold text-ku-text-strong text-[16px] leading-[22px]',
  itemMeta: 'font-ku-regular text-ku-text-secondary text-[14px] leading-[20px]',
  itemDescription: 'font-ku-regular text-ku-text-muted text-[13px] leading-[19px]',
  itemImage: 'w-[64px] h-[64px] rounded-ku-field bg-ku-surface-image',
  itemImageFallback: 'w-[64px] h-[64px] rounded-ku-field bg-ku-surface-placeholder items-center justify-center',
  itemImageFallbackText: 'font-ku-regular text-ku-text-faint text-[10px] text-center px-[4px]',
  formScroll: 'flex-1',
  formContent: 'px-ku-lg pt-ku-md pb-[132px] gap-ku-md self-center w-full max-w-[720px]',
  formGroup: 'bg-ku-card border border-ku-border-subtle rounded-ku-card p-ku-md gap-ku-sm',
  formGroupTitle: 'font-ku-bold text-ku-text-strong text-[18px] leading-[24px] mb-[4px]',
  avatarPicker: 'items-center gap-ku-sm py-ku-sm',
  avatar: 'w-[96px] h-[96px] rounded-[48px] bg-ku-surface-image border border-ku-border-accent',
  avatarFallback: 'w-[96px] h-[96px] rounded-[48px] bg-ku-surface-accent border border-ku-border-accent items-center justify-center',
  avatarInitials: 'font-ku-bold text-[28px] text-ku-primary',
  avatarButton: 'min-h-[48px] px-ku-md items-center justify-center rounded-ku-pill border border-ku-primary',
  avatarButtonText: 'font-ku-semibold text-ku-primary text-[14px]',
  imagePicker: 'border border-ku-border-muted border-dashed rounded-ku-field min-h-[128px] items-center justify-center overflow-hidden bg-ku-surface-subtle',
  imagePreview: 'w-full h-full min-h-[128px]',
  imagePickerText: 'font-ku-semibold text-ku-text-muted text-[13px]',
  dateRow: 'flex-row gap-ku-md',
  dateField: 'flex-1',
  dateButton: 'min-h-[48px] flex-row items-center justify-between border border-ku-border-muted rounded-ku-field bg-ku-card px-ku-md',
  dateText: 'font-ku-regular text-ku-text-strong text-[14px]',
  datePlaceholder: 'font-ku-regular text-ku-text-faint text-[14px]',
  clearDate: 'min-h-[48px] items-center justify-center px-[4px]',
  clearDateText: 'font-ku-semibold text-ku-primary text-[12px]',
  errorCard: 'flex-row items-center bg-ku-surface-danger border border-ku-border-danger rounded-ku-field p-ku-md gap-ku-sm',
  errorText: 'font-ku-regular text-ku-danger-dark text-[13px] leading-[19px] flex-1',
  saveBar: 'absolute bottom-0 left-0 right-0 bg-ku-surface-nav-translucent border-t border-ku-border-nav px-ku-lg pt-ku-sm pb-0',
  saveBarInner: 'self-center w-full max-w-[720px]',
  tagsList: 'flex-row flex-wrap gap-ku-sm',
  tag: 'min-h-[48px] px-[12px] items-center justify-center rounded-ku-pill bg-ku-surface-accent border border-ku-border-accent',
  tagSelected: 'bg-ku-primary border-ku-primary',
  tagText: 'font-ku-semibold text-ku-primary text-[13px]',
  tagTextSelected: 'text-ku-white',
} as const;

export default styles;
