const styles = {
  sheetOverlay: 'bg-ku-overlay flex-1 justify-end',
  sheetOverlayFullScreen: 'bg-ku-card flex-1',
  sheetBackdrop: 'absolute bottom-0 left-0 right-0 top-0',
  sheet: 'bg-ku-card max-h-[92%] min-h-[360px] rounded-tl-[24px] rounded-tr-[24px] px-[20px] pt-[12px]',
  sheetFullScreen: 'bg-ku-card flex-1 px-[20px] pt-[12px]',
  sheetHandle: 'self-center bg-ku-border-accent rounded-ku-pill h-[4px] mb-[14px] w-[40px]',
  sheetHeader: 'items-start flex-row justify-between',
  sheetHeading: 'flex-1 min-w-0 pr-[12px]',
  sheetTitle: 'text-ku-text-strong font-ku-bold text-ku-title-small',
  sheetSubtitle: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[3px]',
  sheetClose: 'items-center bg-ku-surface-muted rounded-ku-pill h-[44px] justify-center w-[44px]',
  sheetScroll: 'flex-1',
  sheetContent: 'pb-[8px] pt-[16px]',
  section: 'mt-[16px]',
  sectionFirst: 'mt-0',
  sectionHeader: 'items-center flex-row justify-between',
  sectionTitle: 'text-ku-text-strong font-ku-semibold text-ku-body',
  sectionMeta: 'text-ku-primary font-ku-semibold text-ku-body-small',
  helper: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[4px]',
  notice: 'bg-ku-surface-accent border-ku-border-accent rounded-[14px] border flex-row items-start px-[12px] py-[11px]',
  noticeSuccess: 'bg-ku-surface-success border-ku-border-success',
  noticeDanger: 'bg-ku-surface-danger border-ku-border-danger',
  noticeIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[32px] justify-center shrink-0 w-[32px]',
  noticeIconDanger: 'bg-ku-surface-danger',
  noticeCopy: 'flex-1 min-w-0 ml-[9px]',
  noticeTitle: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  noticeText: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[2px]',
  searchField: 'items-center bg-ku-surface border-ku-border rounded-[18px] border flex-row min-h-[56px] px-[14px] mt-[8px]',
  searchInput: 'text-ku-text-strong flex-1 font-ku-regular text-ku-body ml-[9px] min-h-[52px]',
  searchClear: 'items-center rounded-ku-pill h-[44px] justify-center ml-[4px] w-[44px]',
  memberList: 'gap-[8px] mt-[10px]',
  memberRow: 'bg-ku-surface-muted border-ku-border-subtle border rounded-[14px] flex-row items-center min-h-[64px] px-[10px] py-[7px]',
  memberRowSelected: 'bg-ku-surface-success border-ku-border-success',
  memberRowDisabled: 'opacity-60',
  memberSelect: 'items-center flex-1 flex-row min-h-[48px] min-w-0',
  memberSelectionBox: 'items-center border-ku-border-accent border rounded-[7px] h-[24px] justify-center shrink-0 w-[24px]',
  memberSelectionBoxSelected: 'bg-ku-primary border-ku-primary',
  memberAvatar: 'items-center bg-ku-surface-success rounded-ku-pill h-[40px] justify-center ml-[9px] w-[40px]',
  memberAvatarText: 'text-ku-primary font-ku-bold text-ku-label',
  memberCopy: 'flex-1 min-w-0 ml-[9px]',
  memberName: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  memberHandle: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[1px]',
  memberInvite: 'items-center border-ku-primary rounded-ku-pill border min-h-[44px] justify-center ml-[8px] px-[11px]',
  memberInviteText: 'text-ku-primary font-ku-semibold text-ku-label',
  bulkInviteBar: 'items-center bg-ku-surface-accent border-ku-border-accent border rounded-[14px] flex-row mt-[10px] px-[12px] py-[8px]',
  bulkInviteCopy: 'flex-1 min-w-0',
  bulkInviteText: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  bulkInviteButton: 'items-center bg-ku-primary rounded-ku-pill min-h-[48px] justify-center ml-[10px] px-[14px]',
  bulkInviteButtonText: 'text-ku-white font-ku-semibold text-ku-label',
  emptyState: 'items-center bg-ku-surface-muted border-ku-border-subtle border-dashed rounded-[16px] justify-center min-h-[190px] px-[24px] py-[24px]',
  emptyIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[52px] justify-center mb-[10px] w-[52px]',
  emptyTitle: 'text-ku-text-strong font-ku-semibold text-ku-body text-center',
  emptyText: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[5px] text-center',
  retryButton: 'items-center bg-ku-primary rounded-ku-pill min-h-[48px] justify-center mt-[12px] px-[20px]',
  retryButtonText: 'text-ku-white font-ku-semibold text-ku-body-small',
  rosterCard: 'bg-ku-surface border-ku-border-subtle border rounded-[16px] mt-[8px] p-[12px]',
  rosterHeader: 'items-center flex-row justify-between',
  rosterCount: 'text-ku-primary font-ku-bold text-ku-body-small',
  rosterList: 'gap-[4px] mt-[8px]',
  rosterRow: 'items-center flex-row min-h-[44px] px-[2px]',
  rosterAvatar: 'items-center bg-ku-surface-success rounded-ku-pill h-[32px] justify-center w-[32px]',
  rosterAvatarText: 'text-ku-primary font-ku-bold text-ku-caption',
  rosterCopy: 'flex-1 min-w-0 ml-[8px]',
  rosterName: 'text-ku-text-strong font-ku-medium text-ku-body-small',
  rosterRole: 'text-ku-text-muted font-ku-regular text-ku-label mt-[1px]',
  rosterStatus: 'text-ku-success font-ku-semibold text-ku-label ml-[8px]',
  invitationList: 'gap-[8px] mt-[8px]',
  invitationRow: 'bg-ku-surface-muted border-ku-border-subtle border rounded-[14px] px-[12px] py-[10px]',
  invitationHeader: 'items-start flex-row',
  invitationCopy: 'flex-1 min-w-0',
  invitationName: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  invitationStatus: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[2px]',
  invitationExpiry: 'text-ku-text-muted font-ku-regular text-ku-label mt-[1px]',
  invitationActions: 'flex-row gap-[8px] mt-[8px]',
  invitationAction: 'items-center border-ku-primary rounded-ku-pill border flex-1 min-h-[44px] justify-center px-[8px]',
  invitationActionAccept: 'bg-ku-primary',
  invitationActionDecline: 'border-ku-danger-dark',
  invitationActionText: 'text-ku-primary font-ku-semibold text-ku-label text-center',
  invitationActionTextAccept: 'text-ku-white',
  invitationActionTextDecline: 'text-ku-danger-dark',
  reviewCard: 'bg-ku-surface-accent border-ku-border-accent rounded-[16px] border mt-[8px] p-[14px]',
  reviewHeader: 'items-center flex-row gap-[9px]',
  reviewIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[38px] justify-center w-[38px]',
  reviewHeaderCopy: 'flex-1 min-w-0',
  reviewHeading: 'text-ku-text-strong font-ku-semibold text-ku-body',
  reviewCopy: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[2px]',
  reviewRows: 'gap-[6px] mt-[12px]',
  reviewRow: 'flex-row items-start',
  reviewLabel: 'text-ku-text-secondary flex-1 font-ku-regular text-ku-body-small',
  reviewValue: 'text-ku-text-strong font-ku-semibold text-ku-body-small text-right',
  submitButton: 'items-center bg-ku-primary rounded-ku-pill flex-row gap-[7px] justify-center min-h-[52px] mt-[16px] px-[16px]',
  submitButtonDisabled: 'bg-ku-surface-muted border-ku-border-muted border',
  submitButtonText: 'text-ku-white font-ku-semibold text-ku-body text-center',
  submitButtonTextDisabled: 'text-ku-text-muted',
  proposalSummary: 'bg-ku-surface-accent border-ku-border-accent rounded-[16px] border mt-[12px] p-[12px]',
  proposalSummaryHeader: 'items-center flex-row justify-between',
  proposalSummaryTitle: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  proposalSummaryCount: 'text-ku-primary font-ku-semibold text-ku-label',
  settlement: 'bg-ku-surface border-ku-border-subtle border rounded-[16px] mt-[12px] p-[12px]',
  settlementHeader: 'items-center flex-row justify-between',
  settlementTitle: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  settlementRows: 'gap-[5px] mt-[8px]',
  settlementRow: 'flex-row items-start',
  settlementLabel: 'text-ku-text-secondary flex-1 font-ku-regular text-ku-label',
  settlementValue: 'text-ku-text-strong font-ku-semibold text-ku-label text-right',
  settlementRefund: 'text-ku-success',
  proposalList: 'gap-[8px] mt-[10px]',
  proposalRow: 'bg-ku-surface-muted border-ku-border-subtle border rounded-[16px] p-[12px]',
  proposalHeaderRow: 'items-start flex-row',
  proposalRowSelected: 'bg-ku-surface-success border-ku-primary',
  proposalRowRejected: 'bg-ku-surface-danger border-ku-border-danger',
  proposalRowSelectedStatus: 'bg-ku-primary border-ku-primary',
  proposalRowStatus: 'items-center border rounded-ku-pill flex-row min-h-[28px] px-[8px]',
  proposalRowStatusText: 'font-ku-semibold text-ku-label',
  proposalSelect: 'items-start flex-row min-h-[48px]',
  proposalSelectionBox: 'items-center border-ku-border-accent border rounded-ku-pill h-[24px] justify-center mt-[1px] w-[24px]',
  proposalSelectionBoxSelected: 'bg-ku-primary border-ku-primary',
  proposalCopy: 'flex-1 min-w-0 ml-[9px]',
  proposalName: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  proposalDetail: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[2px]',
  proposalMembers: 'gap-[2px] mt-[6px]',
  proposalMember: 'text-ku-text-secondary font-ku-regular text-ku-label',
  proposalActions: 'flex-row gap-[8px] mt-[8px]',
  proposalAction: 'items-center border-ku-primary rounded-ku-pill border flex-1 min-h-[44px] justify-center px-[8px]',
  proposalActionAccept: 'bg-ku-primary',
  proposalActionReject: 'border-ku-danger-dark',
  proposalActionText: 'text-ku-primary font-ku-semibold text-ku-label text-center',
  proposalActionTextAccept: 'text-ku-white',
  proposalActionTextReject: 'text-ku-danger-dark',
  consentStatusCard: 'bg-ku-surface-accent border-ku-border-accent rounded-[16px] border mt-[12px] p-[14px]',
  consentStatusCardApproved: 'bg-ku-surface-success border-ku-border-success',
  consentStatusCardCancelled: 'bg-ku-surface-danger border-ku-border-danger',
  consentStatusHeader: 'items-center flex-row gap-[9px]',
  consentStatusIcon: 'items-center bg-ku-surface-success rounded-ku-pill h-[38px] justify-center w-[38px]',
  consentStatusIconCancelled: 'bg-ku-surface-danger',
  consentStatusCopy: 'flex-1 min-w-0',
  consentStatusTitle: 'text-ku-text-strong font-ku-semibold text-ku-body',
  consentStatusDescription: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[3px]',
  countdownCard: 'items-center bg-ku-card border-ku-border-accent border rounded-[14px] flex-row justify-between mt-[12px] px-[12px] py-[10px]',
  countdownLabel: 'text-ku-text-secondary font-ku-regular text-ku-body-small',
  countdownValue: 'text-ku-primary font-ku-bold text-ku-title-small',
  progressTrack: 'bg-ku-border-accent rounded-ku-pill h-[6px] mt-[10px] overflow-hidden w-full',
  progressFill: 'bg-ku-primary h-full',
  voterSection: 'mt-[16px]',
  voterList: 'gap-[6px] mt-[8px]',
  voterRow: 'items-center bg-ku-surface border-ku-border-subtle border rounded-[12px] flex-row min-h-[52px] px-[10px]',
  voterAvatar: 'items-center bg-ku-surface-success rounded-ku-pill h-[32px] justify-center w-[32px]',
  voterAvatarText: 'text-ku-primary font-ku-bold text-ku-caption',
  voterCopy: 'flex-1 min-w-0 ml-[8px]',
  voterName: 'text-ku-text-strong font-ku-medium text-ku-body-small',
  voterRole: 'text-ku-text-muted font-ku-regular text-ku-label mt-[1px]',
  voterStatus: 'font-ku-semibold text-ku-label ml-[6px]',
  voterStatusPending: 'text-ku-text-muted',
  voterStatusApproved: 'text-ku-success',
  voterStatusRejected: 'text-ku-danger-dark',
  consentActions: 'flex-row gap-[8px] mt-[16px]',
  consentAction: 'items-center border rounded-ku-pill flex-1 min-h-[52px] justify-center px-[10px]',
  consentActionApprove: 'bg-ku-primary border-ku-primary',
  consentActionReject: 'border-ku-danger-dark',
  consentActionText: 'font-ku-semibold text-ku-body-small text-center',
  consentActionTextApprove: 'text-ku-white',
  consentActionTextReject: 'text-ku-danger-dark',
  chatHint: 'bg-ku-surface-accent rounded-[12px] flex-row items-start mt-[12px] px-[11px] py-[9px]',
  chatHintText: 'text-ku-text-secondary flex-1 font-ku-regular text-ku-label ml-[8px]',
} as const;

export default styles;
