const styles = {
  brandRow: 'h-[48px] items-end justify-end px-[24px] w-full',
  brandLogo: 'h-[32px] w-[60px]',
  heroCard: 'self-stretch rounded-[16px] bg-ku-white border-ku-border-subtle border',
  headerRow: 'flex-row items-start w-full',
  identityContent: 'flex-1 ml-[16px] min-w-0',
  photoFrame: 'overflow-hidden border-[4px] border-ku-border-subtle bg-ku-surface-image items-center justify-center',
  photo: 'h-full w-full',
  initials: 'text-ku-primary-dark text-[32px] font-ku-bold font-bold',
  name: 'text-ku-text font-ku-bold font-bold',
  metaRow: 'flex-row items-center gap-[8px] mt-[5px] min-w-0',
  meta: 'text-ku-text font-ku-regular text-[14px] flex-1',
  subtleMeta: 'text-ku-text-subtle font-ku-regular text-[13px]',
  tagList: 'flex-row flex-wrap gap-[6px] mt-[10px]',
  tag: 'rounded-ku-pill bg-ku-surface-accent px-[10px] py-[4px]',
  tagText: 'text-ku-primary-dark font-ku-semibold text-[12px]',
  editButton: 'min-h-[44px] mt-[18px] w-full',
  editButtonText: 'text-ku-white font-ku-semibold text-[14px]',
  section: 'self-stretch rounded-[16px] bg-ku-white border-ku-border-subtle border',
  statsCard: 'self-stretch rounded-[16px] bg-ku-white border-ku-border-subtle border p-[16px]',
  statsTopRow: 'items-center flex-row justify-around',
  statItem: 'items-center flex-1',
  statValue: 'text-ku-primary-dark font-ku-bold text-[24px] font-bold',
  statLabel: 'text-ku-text-secondary font-ku-semibold text-[12px] mt-[2px] text-center',
  statValueRow: 'items-center flex-row gap-[3px]',
  statStar: 'text-ku-primary-dark text-[15px]',
  statDivider: 'bg-ku-border-subtle h-[44px] w-[1px]',
  sectionNotice: 'items-center bg-ku-surface-danger border-ku-border-danger rounded-[8px] border gap-[8px] mb-[16px] p-[8px]',
  sectionNoticeText: 'text-ku-danger-dark font-ku-regular text-[13px] text-center',
  sectionRetry: 'min-h-[44px] justify-center px-[16px]',
  sectionRetryText: 'text-ku-primary-dark font-ku-semibold text-[13px] underline',
  ratingDistribution: 'flex-1 mt-[16px]',
  ratingDistributionRow: 'items-center flex-row gap-[8px] mt-[4px]',
  ratingDistributionLabel: 'text-ku-text-secondary text-[12px] w-[12px]',
  ratingDistributionTrack: 'bg-ku-border-subtle rounded-ku-pill flex-1 h-[6px] overflow-hidden',
  ratingDistributionFill: 'bg-ku-primary rounded-ku-pill h-full',
  ratingDistributionCount: 'text-ku-text-muted text-[12px] text-right w-[22px]',
  sectionTitle: 'text-ku-text text-[20px] font-ku-semibold font-semibold',
  rule: 'h-[1px] bg-ku-border-subtle mt-[12px] mb-[20px]',
  body: 'text-ku-text-secondary font-ku-regular text-[16px] leading-[22px]',
  emptyText: 'text-ku-text-muted font-ku-regular text-[14px]',
  tabsScroll: 'self-stretch',
  tabList: 'bg-ku-white border-ku-border-subtle rounded-[16px] border flex-row px-[4px]',
  tab: 'items-center justify-center min-h-[72px] min-w-[70px] px-[8px] py-[8px] border-b-[3px] border-b-transparent',
  tabSelected: 'border-b-ku-primary',
  tabText: 'text-ku-text-secondary font-ku-semibold text-[11px] mt-[5px] text-center',
  tabTextSelected: 'text-ku-primary',
  experience: 'flex-row border-l-[2px] border-l-ku-border-subtle pl-[20px] pb-[20px]',
  timelineIcon: 'items-center bg-ku-white h-[22px] justify-center -ml-[31px] mr-[10px] w-[22px]',
  experienceContent: 'flex-1',
  itemTitle: 'text-ku-text text-[15px] font-ku-semibold font-semibold',
  itemMeta: 'text-ku-text-subtle font-ku-regular text-[13px] leading-[20px] mt-[2px]',
  itemDescription: 'text-ku-text-secondary font-ku-regular text-[14px] leading-[22px] mt-[6px]',
  previewOverlay: 'items-center bg-ku-overlay flex-1 justify-center p-[24px]',
  previewCard: 'items-center bg-ku-white rounded-[16px] max-h-[90%] p-[16px] w-full',
  previewClose: 'self-end min-h-[44px] min-w-[44px] items-center justify-center',
  previewImage: 'h-[360px] max-w-full w-full',
  previewTitle: 'text-ku-text font-ku-semibold text-[16px] mt-[8px] text-center',
  grid: 'gap-[16px]',
  gridRow: 'flex-row gap-[16px]',
  gridSpacer: 'flex-1',
  certificateCard: 'flex-1 min-w-0',
  certificateImageFrame: 'bg-ku-surface-placeholder border-ku-border-subtle rounded-[10px] border h-[112px] items-center justify-center mb-[8px] overflow-hidden',
  certificateImage: 'h-full w-full',
  certificateIssuer: 'text-ku-success font-ku-regular text-[13px] mt-[2px]',
  workCard: 'flex-1 min-w-0',
  workImage: 'w-full h-[112px] rounded-[10px] mb-[8px]',
  imageFallback: 'items-center bg-ku-surface-placeholder justify-center',
  imageFallbackText: 'text-ku-text-muted font-ku-regular text-[13px] text-center',
  filterList: 'flex-row flex-wrap gap-[8px] mb-[16px]',
  filterChip: 'border-ku-border rounded-ku-pill border min-h-[36px] justify-center px-[12px]',
  filterChipSelected: 'bg-ku-primary border-ku-primary',
  filterChipText: 'text-ku-text-secondary font-ku-semibold text-[13px]',
  filterChipTextSelected: 'text-ku-white',
  reviewCard: 'bg-ku-surface-subtle rounded-[8px] mt-[8px] p-[16px]',
  reviewHeader: 'flex-row items-center gap-[8px]',
  reviewAvatar: 'bg-ku-surface-image rounded-[18px] h-[36px] w-[36px]',
  reviewAvatarFallback: 'items-center bg-ku-surface-accent rounded-[18px] h-[36px] justify-center w-[36px]',
  reviewAvatarInitials: 'text-ku-primary-dark font-ku-semibold text-[12px]',
  reviewHeaderText: 'flex-1',
  reviewRating: 'text-ku-primary-dark text-[14px] mt-[3px]',
  reviewSummary: 'items-center flex-row gap-[16px] mb-[16px]',
  reviewScore: 'items-center min-w-[86px]',
  reviewScoreRow: 'items-center flex-row gap-[2px]',
  reviewScoreValue: 'text-ku-primary-dark font-ku-bold text-[32px] font-bold',
  reviewScoreStar: 'text-ku-primary-dark text-[18px]',
  reviewScoreStars: 'text-ku-primary-dark text-[11px] tracking-[1px] -mt-[2px]',
  reviewCount: 'text-ku-text-muted font-ku-regular text-[11px] mt-[2px]',
} as const;

export default styles;
