const styles = {
  heroCard: 'self-stretch rounded-[16px] bg-ku-card border-ku-border-accent border',
  profileSettingsRow: 'items-end w-full border-b border-ku-border-subtle mb-[16px] pb-[8px]',
  profileSettingsButton: 'items-center flex-row gap-[8px] min-h-[48px] rounded-[10px] bg-ku-surface-muted px-[12px]',
  profileSettingsText: 'text-ku-primary font-ku-semibold text-ku-body-small',
  headerRow: 'flex-row items-start w-full',
  identityContent: 'flex-1 ml-[16px] min-w-0',
  photoFrame: 'overflow-hidden border-[4px] border-ku-border-subtle bg-ku-surface-image items-center justify-center',
  photo: 'h-full w-full',
  initials: 'text-ku-primary-dark text-ku-display-small font-ku-bold',
  name: 'text-ku-text font-ku-bold',
  metaRow: 'flex-row items-center gap-[8px] mt-[5px] min-w-0',
  meta: 'text-ku-text font-ku-regular text-ku-body-small flex-1',
  subtleMeta: 'text-ku-text-subtle font-ku-regular text-ku-meta',
  tagGroup: 'self-stretch gap-[6px] mt-[16px]',
  tagGroupLabel: 'text-ku-text-secondary font-ku-semibold text-ku-label',
  tagList: 'flex-row flex-wrap gap-[6px]',
  tag: 'rounded-ku-pill bg-ku-surface-accent border-ku-border-accent border px-[10px] py-[4px]',
  tagText: 'text-ku-primary-dark font-ku-semibold text-ku-label',
  editButton: 'min-h-[48px] mt-[18px] w-full',
  editButtonText: 'text-ku-white font-ku-semibold text-ku-body-small',
  section: 'self-stretch rounded-[16px] bg-ku-card border-ku-border-subtle border',
  statsCard: 'self-stretch rounded-[16px] bg-ku-surface-success border-ku-border-success border p-[16px]',
  statsTopRow: 'items-center flex-row justify-around',
  statItem: 'items-center flex-1',
  statValue: 'text-ku-primary-deep font-ku-bold text-ku-title font-ku-bold',
  statEmptyValue: 'text-ku-meta text-center',
  statLabel: 'text-ku-text-secondary font-ku-semibold text-ku-label mt-[2px] text-center',
  statValueRow: 'items-center flex-row gap-[3px]',
  statStar: 'text-ku-success text-ku-control',
  statDivider: 'bg-ku-border-success h-[44px] w-[1px]',
  sectionNotice: 'items-center bg-ku-surface-danger border-ku-border-danger rounded-[8px] border gap-[8px] mb-[16px] p-[8px]',
  sectionNoticeText: 'text-ku-danger-dark font-ku-regular text-ku-meta text-center',
  sectionRetry: 'min-h-[48px] justify-center px-[16px]',
  sectionRetryText: 'text-ku-primary-dark font-ku-semibold text-ku-meta underline',
  emptyState: 'items-center gap-[12px]',
  emptyAction: 'min-h-[48px] justify-center rounded-ku-pill bg-ku-surface-accent border-ku-border-accent border px-[16px]',
  emptyActionText: 'text-ku-primary-dark font-ku-semibold text-ku-meta',
  reviewContext: 'text-ku-text-secondary font-ku-regular text-ku-body-small',
  ratingDistribution: 'self-stretch mt-[10px]',
  ratingDistributionRow: 'items-center flex-row gap-[8px] mt-[4px] min-h-[44px]',
  ratingDistributionRowSelected: 'bg-ku-surface-accent rounded-[8px] px-[8px]',
  ratingDistributionLabel: 'text-ku-text-secondary text-ku-label w-[12px]',
  ratingDistributionTrack: 'bg-ku-border-subtle rounded-ku-pill flex-1 h-[6px] overflow-hidden',
  ratingDistributionFill: 'bg-ku-primary rounded-ku-pill h-full',
  ratingDistributionCount: 'text-ku-text-muted text-ku-label text-right w-[22px]',
  sectionTitle: 'text-ku-text text-ku-section font-ku-semibold',
  rule: 'h-[1px] bg-ku-border-subtle mt-[12px] mb-[20px]',
  body: 'text-ku-text-secondary font-ku-regular text-ku-body',
  emptyText: 'text-ku-text-muted font-ku-regular text-ku-body-small',
  tabsScroll: 'self-stretch',
  tabList: 'bg-ku-surface border-ku-border-accent rounded-[16px] border flex-row px-[4px]',
  tab: 'items-center justify-center min-h-[72px] min-w-[70px] px-[10px] py-[8px] border-b-[3px] border-b-transparent',
  tabSelected: 'bg-ku-surface-accent border-b-ku-primary',
  tabText: 'text-ku-text-secondary font-ku-semibold text-ku-label mt-[4px] text-center',
  tabTextSelected: 'text-ku-primary',
  experience: 'flex-row border-l-[2px] border-l-ku-border-subtle pl-[20px] pb-[20px]',
  timelineIcon: 'items-center bg-ku-card h-[22px] justify-center -ml-[31px] mr-[10px] w-[22px]',
  experienceContent: 'flex-1',
  itemTitle: 'text-ku-text text-ku-control font-ku-semibold',
  itemMeta: 'text-ku-text-subtle font-ku-regular text-ku-meta mt-[2px]',
  itemDescription: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[6px]',
  previewOverlay: 'items-center bg-ku-overlay flex-1 justify-center p-[24px]',
  previewCard: 'items-center bg-ku-card rounded-[16px] max-h-[90%] p-[16px] w-full',
  previewClose: 'self-end min-h-[48px] min-w-[48px] items-center justify-center',
  previewScroll: 'max-w-full w-full',
  previewImage: 'max-w-full w-full',
  previewTitle: 'text-ku-text font-ku-semibold text-ku-body mt-[8px] text-center',
  grid: 'gap-[16px]',
  gridRow: 'flex-row gap-[16px]',
  gridSpacer: 'flex-1',
  certificateCard: 'flex-1 min-w-0',
  certificateImageFrame: 'bg-ku-surface-placeholder border-ku-border-subtle rounded-[10px] border w-full items-center justify-center mb-[8px] overflow-hidden',
  certificateImage: 'h-full w-full',
  certificateIssuer: 'text-ku-success font-ku-regular text-ku-meta mt-[2px]',
  previewHint: 'text-ku-primary font-ku-semibold text-ku-label mt-[2px]',
  workCard: 'flex-1 min-w-0',
  workImage: 'w-full rounded-[10px] mb-[8px]',
  workDetailSheet: 'bg-ku-card rounded-t-[20px] max-h-[88%] mt-auto w-full',
  workDetailScroll: 'w-full',
  workDetailContent: 'gap-[16px] p-[20px] pb-[36px]',
  workDetailTitle: 'text-ku-text font-ku-bold text-ku-title',
  workDetailDescription: 'text-ku-text-secondary font-ku-regular text-ku-body',
  workGallery: 'self-stretch',
  workGalleryImage: 'bg-ku-surface-placeholder rounded-[12px]',
  showAllReviews: 'self-start min-h-[48px] justify-center mt-[4px] px-[8px]',
  showAllReviewsText: 'text-ku-primary font-ku-semibold text-ku-meta underline',
  imageFallback: 'items-center bg-ku-surface-placeholder justify-center',
  imageFallbackText: 'text-ku-text-muted font-ku-regular text-ku-meta text-center',
  filterScroll: 'self-stretch mb-[16px]',
  filterList: 'flex-row gap-[8px]',
  filterChip: 'border-ku-border rounded-ku-pill border min-h-[48px] justify-center px-[12px]',
  filterChipSelected: 'bg-ku-primary border-ku-primary',
  filterChipText: 'text-ku-text-secondary font-ku-semibold text-ku-meta',
  filterChipTextSelected: 'text-ku-white',
  profileListContent: 'gap-[16px]',
  reviewCard: 'bg-ku-surface-subtle border-ku-border-subtle rounded-[8px] border mt-[8px] p-[16px]',
  reviewHeader: 'flex-row items-center gap-[8px]',
  reviewAvatar: 'bg-ku-surface-image rounded-[18px] h-[36px] w-[36px]',
  reviewAvatarFallback: 'items-center bg-ku-surface-accent rounded-[18px] h-[36px] justify-center w-[36px]',
  reviewAvatarInitials: 'text-ku-primary-dark font-ku-semibold text-ku-label',
  reviewHeaderText: 'flex-1',
  reviewRating: 'items-center flex-row gap-[1px] mt-[3px]',
  reviewSummary: 'items-center flex-row gap-[16px] mb-[16px]',
  reviewScore: 'items-center min-w-[96px]',
  reviewScoreValue: 'text-ku-primary-dark font-ku-bold text-ku-display-small',
  reviewScoreEmpty: 'text-ku-text-secondary font-ku-semibold text-ku-body-small text-center',
  reviewScoreStars: 'items-center flex-row gap-[1px] mt-[4px]',
  reviewCount: 'text-ku-text-muted font-ku-regular text-ku-caption mt-[4px] text-center',
  reviewTotalQuests: 'text-ku-text-subtle font-ku-regular text-ku-caption mt-[2px] text-center',
  reviewDistribution: 'flex-1',
} as const;

export default styles;
