const styles = {
  trigger: 'items-center bg-ku-surface-accent border-ku-border-accent border flex-row min-h-[44px] justify-center px-[12px] rounded-ku-pill',
  triggerCompact: 'px-0 w-[44px]',
  triggerText: 'text-ku-primary font-ku-semibold text-ku-label ml-[6px]',
  overlay: 'bg-ku-overlay flex-1 justify-end',
  backdrop: 'absolute bottom-0 left-0 right-0 top-0',
  sheet: 'bg-ku-card max-h-[92%] min-h-[360px] rounded-tl-[24px] rounded-tr-[24px] px-[20px] pt-[12px]',
  handle: 'self-center bg-ku-border-accent rounded-ku-pill h-[4px] mb-[14px] w-[40px]',
  header: 'items-start flex-row justify-between',
  heading: 'flex-1 min-w-0 pr-[12px]',
  title: 'text-ku-text-strong font-ku-bold text-ku-title-small',
  subtitle: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[3px]',
  close: 'items-center bg-ku-surface-muted rounded-ku-pill h-[44px] justify-center w-[44px]',
  scroll: 'flex-1',
  content: 'pb-[8px] pt-[16px]',
  section: 'mt-[20px]',
  sectionFirst: 'mt-0',
  sectionTitle: 'text-ku-text-strong font-ku-semibold text-ku-body',
  sectionHint: 'text-ku-text-secondary font-ku-regular text-ku-body-small mt-[3px]',
  optionList: 'gap-[8px] mt-[8px]',
  personaOption: 'bg-ku-surface-muted border-ku-border-subtle border rounded-[12px] flex-row items-center min-h-[56px] px-[12px] py-[6px]',
  personaOptionSelected: 'bg-ku-surface-success border-ku-border-success',
  optionControl: 'items-center border-ku-border-accent border rounded-ku-pill h-[24px] justify-center shrink-0 w-[24px]',
  optionControlSelected: 'bg-ku-primary border-ku-primary',
  optionCopy: 'flex-1 min-w-0 ml-[10px]',
  optionLabel: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  optionRoute: 'text-ku-text-secondary font-ku-regular text-ku-label mt-[1px]',
  scenarioOption: 'bg-ku-surface border-ku-border-subtle border rounded-[12px] flex-row items-center min-h-[56px] px-[12px] py-[6px]',
  scenarioOptionSelected: 'bg-ku-surface-accent border-ku-border-accent',
  scenarioCopy: 'flex-1 min-w-0',
  scenarioLabel: 'text-ku-text-strong font-ku-semibold text-ku-body-small',
  scenarioRoute: 'text-ku-primary font-ku-regular text-ku-label mt-[1px]',
  resetSection: 'border-t-ku-border-subtle border-t mt-[24px] pt-[16px]',
  resetList: 'gap-[8px] mt-[8px]',
  resetOption: 'items-center border-ku-primary rounded-ku-pill border min-h-[44px] justify-center px-[12px]',
  resetOptionAll: 'bg-ku-primary',
  resetOptionText: 'text-ku-primary font-ku-semibold text-ku-body-small text-center',
  resetOptionTextAll: 'text-ku-white',
} as const;

export default styles;
